Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Timeline");
(function(a,b,c,d){var j=60000,i=j*60,h=i*24,e=3,g=4,f=1;
d.ModelBase=function(k){this._owner=k;
this._settings=this._owner.get_timelineViewSettings()||{};
this._defaultHeaderDateFormat="d";
this._contentTable=null;
};
d.ModelBase.prototype={get_visibleRangeStart:function(){return b.add(this._owner.get_selectedDate(),this._getStartTime());
},get_visibleRangeEnd:function(){var k=new b(this.get_visibleRangeStart());
return k.add(this._getTimeViewDuration()).toDate();
},get_headerDateFormat:function(){if(!this._settings){return this._defaultHeaderDateFormat;
}return this._settings.headerDateFormat||this._defaultHeaderDateFormat;
},get_columnHeaderDateFormat:function(){return this._settings.columnHeaderDateFormat||"d";
},get_nextPeriodDate:function(){return b.add(this._owner.get_selectedDate(),this._getTimeViewDuration().get_ticks());
},get_previousPeriodDate:function(){return b.add(this._owner.get_selectedDate(),-this._getTimeViewDuration().get_ticks());
},get_isAllDayAppointment:function(k){return((b.getTimeOfDay(k.get_start())==0)&&(k._isAllDay()));
},get_startOfMovedAppointment:function(k,n,m){var l=b.subtract(k.get_start(),m.get_startTime());
return b.add(n.get_startTime(),l);
},getDurationOfMovedAppointment:function(k){return b.subtract(k.get_end(),k.get_start());
},_getContentTable:function(){if(!this._contentTable){this._contentTable=a("div.rsTopWrap table.rsAllDayTable",this._owner.get_element())[0];
}return this._contentTable;
},_getSourceCellOffsetOfMovedAppointment:function(l,m){var k=Math.floor(parseInt(l.style.left,10)/100)||0;
return m.cellIndex-k;
},_getSourceRowOffsetOfMovedAppointment:function(k,l){return 0;
},updateDraggingAppointmentSize:function(k,r,m){var q=this._owner,s=r.parentNode,n=s.cells[s.cells.length-1],o=n.offsetLeft+n.offsetWidth,p=Math.min(o-r.offsetLeft-k.offsetLeft,q._draggingAppointmentWidth),l=Math.max(0,q._draggingSourceCellOffset-m.cellIndex);
if(l>0){p-=l*r.offsetWidth;
}k.style.width=p+"px";
},updateResizingAppointmentSize:function(w,v){var l=v.resizingElement,t=l.parentNode.parentNode,q=w.offsetLeft+w.offsetWidth,m=l.offsetLeft,u=v.resizeFromStart,x,o=0,k=a(w);
while(!k.hasClass("rsFirstCell")){k=k.prev();
o++;
}if(t!=k.get(0)){return;
}if(u){var p=k.get(0).offsetLeft,n=m+l.offsetWidth+p,r=l.style.left,s=l.style.marginLeft;
l.style.left=o+"00%";
l.style.marginLeft=o+"px";
x=n-l.offsetLeft-p;
if(x<=1){l.style.left=r;
l.style.marginLeft=s;
return;
}}else{x=Math.max(q-t.offsetLeft-m,t.offsetWidth-m);
}if(x<=1){return;
}l.style.width=x+"px";
},_getResizingAppointmentOriginalSize:function(m,l){var k=a(m);
return{width:k.width(),left:k.get(0).style.left,marginLeft:k.get(0).style.marginLeft};
},restoreResizingAppointmentSize:function(p){var n=p.originalSize,o=n.width,l=n.left,m=n.marginLeft;
if($telerik.isIE6||$telerik.quirksMode){o-=g;
}var k=a(p.resizingElement);
k.width(o);
k.get(0).style.left=l;
k.get(0).style.marginLeft=m;
},_getMaxAppointmentGrowth:function(){return this._getNumberOfSlots();
},_getNumberOfSlots:function(){return this._settings.numberOfSlots||e;
},_getTimeLabelSpan:function(){return this._settings.timeLabelSpan||f;
},_getSlotDuration:function(){return this._settings.slotDuration||h;
},_getStartTime:function(){return this._settings.startTime||0;
},isVisible:function(k){return k._isInRange(this.get_visibleRangeStart(),this.get_visibleRangeEnd());
},_getTimeViewDuration:function(){return new c(this._getNumberOfSlots()*this._getSlotDuration());
},get_supportsSlotSelection:function(){return false;
},get_supportsFullTime:function(){return false;
},_getFirstTimeSlot:function(){var k=this._getContentTable().rows[0].cells[0];
return this.getTimeSlotFromDomElement(k);
},_getResizingPlaneDelta:function(){return 0;
}};
d.ModelBase.registerClass("Telerik.Web.UI.Scheduler.Views.Timeline.ModelBase",null,Telerik.Web.UI.ISchedulerModel);
d.Model=function(k){d.Model.initializeBase(this,[k]);
this._slotDurationInMinutes=this._getSlotDuration()/j;
if(Telerik.Web.UI.Scheduler.Rendering.HorizontalBlockCollection){this._allDayBlocks=new Telerik.Web.UI.Scheduler.Rendering.HorizontalBlockCollection();
}};
d.Model.prototype={initialize:function(){},addToBlocks:function(k){this._allDayBlocks.add(k);
},removeFromBlock:function(k){this._allDayBlocks.remove(k);
},resetBlocks:function(){if(Telerik.Web.UI.Scheduler.Rendering.HorizontalBlockCollection){this._allDayBlocks=new Telerik.Web.UI.Scheduler.Rendering.HorizontalBlockCollection();
}},getTimeSlotFromDomElement:function(k){var l=this._getRawIndexFromDomElement(k),m=this._getTimeFromIndex(l);
return new d.TimeSlot(l,m,this._slotDurationInMinutes,k);
},_getTimeFromDomElement:function(k){var l=this._getRawIndexFromDomElement(k);
return this._getTimeFromIndex(l);
},_getTimeFromIndex:function(l){var k=this.get_visibleRangeStart();
Telerik.Web.UI.RadScheduler._incrementTime(k,0,this._slotDurationInMinutes*l.intervalIndex);
return k;
},_getRawIndexFromDomElement:function(k){while(k&&(k.tagName.toUpperCase()!="TD")){k=k.parentNode;
}if(k){return{intervalIndex:k.cellIndex};
}return null;
},_getRawIndexFromStartTime:function(l){var k=b.subtract(new Date(l),this.get_visibleRangeStart());
return{intervalIndex:Math.max(0,Math.floor(k/this._getSlotDuration()))};
},_getAllDayTimeSlotForAppointmentPart:function(k){return this._getTimeSlotFromStartTime(k.start);
},_getTimeSlotFromStartTime:function(m){var l=this._getRawIndexFromStartTime(m),k=this._getDomElementFromRawIndex(l.intervalIndex);
return this.getTimeSlotFromDomElement(k);
},getTimeSlotForAppointment:function(k){return this._getTimeSlotFromStartTime(k.get_start());
},_getDomElementFromRawIndex:function(k){return a(".rsTimelineView .rsAllDayRow",this._owner.get_element()).children()[k];
},_getRenderer:function(){if(!this._renderer){this._renderer=new Telerik.Web.UI.Scheduler.Rendering.TimelineViewRenderer(this);
}return this._renderer;
}};
d.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Timeline.Model",d.ModelBase);
d.TimeSlot=function(m,n,l,k){this._rawIndex=m;
this._startTime=n;
this._durationInMinutes=l;
this._domElement=k;
};
d.TimeSlot.prototype={get_index:function(){var k=this.get_rawIndex();
return String.format("{0}",k.intervalIndex);
},get_rawIndex:function(){return this._rawIndex;
},get_startTime:function(){return this._startTime;
},get_endTime:function(){return b.add(this.get_startTime(),this.get_duration());
},get_duration:function(){return this.get_durationInMinutes()*j;
},get_durationInMinutes:function(){return this._durationInMinutes;
},get_isAllDay:function(){return true;
},get_domElement:function(){return this._domElement;
}};
d.TimeSlot.registerClass("Telerik.Web.UI.Scheduler.Views.Timeline.TimeSlot",null,Telerik.Web.UI.ISchedulerTimeSlot);
})($telerik.$,Telerik.Web.UI.Scheduler.DateTime,Telerik.Web.UI.Scheduler.TimeSpan,Telerik.Web.UI.Scheduler.Views.Timeline);
