Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
(function(){var a=$telerik.$;
var b=Telerik.Web.UI;
$telerik.toColorPicker=function(c){return c;
};
$telerik.findColorPicker=$find;
a.registerEnum(b,"PaletteModes",{WebPalette:1,RGBSliders:2,HSB:4,HSV:8,All:(1+2+4+8)});
b.ColorPickerColorChangeEventArgs=function(c){b.ColorPickerColorChangeEventArgs.initializeBase(this);
this._oldColor=c;
};
b.ColorPickerColorChangeEventArgs.prototype={get_oldColor:function(){return this._oldColor;
}};
b.ColorPickerColorChangeEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorChangeEventArgs",Sys.EventArgs);
b.ColorPickerColorPreviewEventArgs=function(c){b.ColorPickerColorPreviewEventArgs.initializeBase(this);
this._color=c;
};
b.ColorPickerColorPreviewEventArgs.prototype={get_color:function(){return this._color;
}};
b.ColorPickerColorPreviewEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorPreviewEventArgs",Sys.EventArgs);
b.ColorPickerColorSelectingEventArgs=b.ColorPickerColorPreviewEventArgs;
b.RadColorPicker=function(c){b.RadColorPicker.initializeBase(this,[c]);
this._selectedColor=null;
this._selectedColorName="";
this._autoPostBack=false;
this._enabled=true;
this._previewColor=true;
this._showIcon=false;
this._showEmptyColor=true;
this._lastPreviewColor="";
this._elementsByColor=[];
this._indexByColor=[];
this._mouseUpHandler=null;
this._localization=null;
this._popupBehavior=null;
this._paletteDisplayed=false;
this._uniqueID=null;
this._columns=18;
this._items=null;
this._width=0;
this._skin="Default";
this._overlay=false;
this._keepInScreenBounds=true;
this._isTouchSkin=false;
this._paletteModes=b.PaletteModes.WebPalette;
this._selectedTab=null;
this._selectedContainer=null;
this._tabStrip=null;
this._multiPage=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this._rgbSlidersDefaultValue=255;
this._rgbSlidersDefaultSize=217;
this._redInput=null;
this._greenInput=null;
this._blueInput=null;
this._hexColorInput=null;
this._applyButton=null;
this._defaultRGBWidth=270;
this._rgbSlidersMinSize=115;
this._eventStartedInControl=false;
this._inputAvoidRecursion=false;
this._sliderAvoidRecursion=false;
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this._millionColorsSliderWidth="22px";
this._millionColorsSliderHeight="162px";
this._defaultHSBWidth=345;
this._defaultHSVWidth=249;
this._millionColorsInputs=null;
this._millionColorsResizeExtender=null;
this._millionColorsAvoidRecursion=false;
this._millionColorsSliderAvoidRecursion=false;
this._hsbPaletteRange={x:255,y:159};
this._customPaletteRange={x:255,y:159};
this._hsvPalettePoints={x:159,y:159};
this._rightToLeft=false;
this._enableCustomColor=false;
this._customColorOkButton=null;
this._customColorCancelButton=null;
this._customColorPalette=null;
this._customColorPopupBehavior=null;
this._customColorModalExtender=null;
this._customColorPreviewElement=null;
this._hexCustomColorInput=null;
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
this._millionCustomColorsInputs={r:null,g:null,b:null,h:null,s:null,l:null};
this._millionCustomColorsResizeExtender=null;
this._showRecentColors=false;
this._recentColorsWrapper=null;
this._recentColors=[];
this._recentElementsByColor=[];
this._accessKey="";
this._tabIndex=0;
this._iconLink=null;
this._paletteSizes={};
this.ShowPalette=this.showPalette;
this.HidePalette=this.hidePalette;
this.GetIconContainer=this.getIconContainer;
this.GetPaletteContainer=this.getPaletteContainer;
};
b.RadColorPicker.prototype={initialize:function(){b.RadColorPicker.callBaseMethod(this,"initialize");
this._calculateRenderSettings();
var c=this.get_element();
if($telerik.isRightToLeft(c)){Sys.UI.DomElement.addCssClass(c,"RadColorPickerRTL");
Sys.UI.DomElement.addCssClass(c,"RadColorPickerRTL_"+this._skin);
this._rightToLeft=true;
}this._initializeFields();
this._localization=eval(this._localization);
if(!this._showIcon){this._paletteDisplayed=true;
this._initializeColorElementsArray();
this._setElementsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
}this._initializeEventHandlers();
this._applyAccessKey();
this.set_selectedColor(this._selectedColor,false,true);
if(this._items){this._items=eval(this._items);
}this.raiseEvent("load");
},isSkin:function(c){return Sys.UI.DomElement.containsCssClass(this.get_element(),"RadColorPicker_"+c);
},_initializeFields:function(){var d=this.get_id();
this._wrapperElement=$get(d);
this._previewElement=$get(d+"_preview");
this._emptyColorElement=$get(d+"_emptycolor");
this._iconElement=$get(d+"_icon");
var m=this._iconWrapperElement=$get(d+"_label");
if(m){this._iconLink=$telerik.getChildrenByTagName(m,"a")[0];
}var r=this._paletteWrapperElement=$get(d+"_palette");
if(r){var u=this._tabStrip=$telerik.getChildByClassName(r,"rcpTabs");
this._multiPage=$telerik.getChildByClassName(r,"rcpViews");
var v=this._webPalettePageView=$get(d+"_webPalette");
this._webPaletteWrapper=(v)?$telerik.getChildByClassName(v,"rcpWebPalette"):null;
var s=this._rgbPageView=$get(d+"_rgbSliders");
this._millionColorsPageView=$get(d+"_millionColors");
this._selectedContainer=(v)?v:(s?s:this._millionColorsPageView);
if(u){var w=this.isModeEnabled(b.PaletteModes.WebPalette);
var t=this.isModeEnabled(b.PaletteModes.RGBSliders);
var h=this.isModeEnabled(b.PaletteModes.HSB);
var k=this.isModeEnabled(b.PaletteModes.HSV);
var p=u.getElementsByTagName("a");
for(var l=0;
l<p.length;
l++){if(w){this._addRelAttribute(p[l],"_webPalette",d);
w=false;
continue;
}if(t){this._addRelAttribute(p[l],"_rgbSliders",d);
t=false;
continue;
}if(h){this._addRelAttribute(p[l],"_millionColors",d);
h=false;
continue;
}if(k){this._addRelAttribute(p[l],"_millionColors",d);
k=false;
}}for(var n=0,o=p.length;
n<o;
n++){this._initializeTabHandler(p[n]);
}this._selectedTab=$telerik.getElementByClassName(u,"rcpSelectedTab","li");
}this._recentColorsWrapper=$get(d+"_recentColors");
var f=this._header=$telerik.getChildByClassName(r,"rcpHeader");
if(f){var c=this._applyButton=$telerik.getChildByClassName(f,"rcpApplyButton");
if(c){this._initializeApplyHandler(c);
}var e=this._customColorButton=$telerik.getChildByClassName(f,"rcpCustomColorButton");
if(e){this._initializeCustomColorHandler(e);
}}}this._redInput=$get(d+"_redInput");
this._greenInput=$get(d+"_greenInput");
this._blueInput=$get(d+"_blueInput");
var g=this._hexColorInput=$get(d+"_hexInput");
if(this.get_redSlider()){this._initializeRgbInputHandler(this._redInput);
this._initializeRgbInputHandler(this._greenInput);
this._initializeRgbInputHandler(this._blueInput);
this._initializeRgbSliderHandler(this.get_redSlider());
this._initializeRgbSliderHandler(this.get_greenSlider());
this._initializeRgbSliderHandler(this.get_blueSlider());
}if(g){this._initializeHexHandler(g);
}this._millionColorsPalette=$get(d+"_millionColorsPalette");
this._initializeMillionColorsPaletteHandler();
this._millionColorsHandle=$get(d+"_millionColorsHandle");
this._createHandleResizeExtender();
this._initializeMillionColorsSliderHandler();
var q=this._millionColorsInputs={r:$get(d+"_rInput"),g:$get(d+"_gInput"),b:$get(d+"_bInput"),h:$get(d+"_hInput"),s:$get(d+"_sInput"),l:$get(d+"_lInput"),v:$get(d+"_vInput")};
this._initializeMillionColorsRgbInputHandler(q.r);
this._initializeMillionColorsRgbInputHandler(q.g);
this._initializeMillionColorsRgbInputHandler(q.b);
this._initializeMillionColorsInputHandler(q.h);
this._initializeMillionColorsInputHandler(q.s);
this._initializeMillionColorsInputHandler(q.l);
this._initializeMillionColorsInputHandler(q.v);
},_addRelAttribute:function(d,e,c){if(d){d.rel=c+e;
}},dispose:function(){this._disposeControl("_millionColorsResizeExtender");
this._disposeControl("_popupBehavior");
this._disposeControl("_customColorPopupBehavior");
this._disposeControl("_customColorModalExtender");
this._disposeControl("_millionCustomColorsResizeExtender");
this._disposeHandlers();
this._selectedTab=null;
this._selectedContainer=null;
var j=this._tabStrip;
if(j){var g=j.getElementsByTagName("a");
for(var e=0,f=g.length;
e<f;
e++){$clearHandlers(g[e]);
}}var c=this._accessKeyTextbox;
if(c){$clearHandlers(c);
c.removeAttribute("accessKey");
this._accessKeyTextbox=null;
}this._tabStrip=null;
this._multiPage=null;
this._webPaletteWrapper=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this.set_redSlider(null);
this.set_greenSlider(null);
this.set_blueSlider(null);
this.set_hiddenSlider(null);
this._clearHandlers("_redInput");
this._clearHandlers("_greenInput");
this._clearHandlers("_blueInput");
this._clearHandlers("_hexColorInput");
this._clearHandlers("_applyButton");
this._clearHandlers("_customColorButton");
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this.set_millionColorsSlider(null);
var h=this._millionColorsInputs;
this._clearHandlers(null,h.r);
this._clearHandlers(null,h.g);
this._clearHandlers(null,h.b);
this._clearHandlers(null,h.h);
this._clearHandlers(null,h.s);
this._clearHandlers(null,h.l);
this._clearHandlers(null,h.v);
this._millionColorsInputs=null;
this._paletteSizes=null;
this._elementsByColor=null;
this._indexByColor=null;
this._recentColors=null;
this._recentElementsByColor=null;
this._clearHandlers("_recentColorsWrapper");
this._customColorPreviewElement=null;
this._clearHandlers("_customColorOkButton");
this._clearHandlers("_customColorCancelButton");
this._clearHandlers("_hexCustomColorInput");
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
if(this.get_millionCustomColorsSlider()){this.get_millionCustomColorsSlider().dispose();
}this.set_millionCustomColorsSlider(null);
h=this._millionCustomColorsInputs;
this._clearHandlers(null,h.r);
this._clearHandlers(null,h.g);
this._clearHandlers(null,h.b);
this._clearHandlers(null,h.h);
this._clearHandlers(null,h.s);
this._clearHandlers(null,h.l);
this._millionCustomColorsInputs=null;
var d=this._customColorPalette;
if(d){if(d.parentNode){d.parentNode.removeChild(d);
}this._customColorPalette=null;
}b.RadColorPicker.callBaseMethod(this,"dispose");
},repaint:function(){this._setElementsSize();
var c=this._paletteWrapperElement;
if(c){this._setRightRoundedCornerAndShadowHeight(c);
}},_disposeControl:function(d){var c=this[d];
if(c){c.dispose();
this[d]=null;
}},_clearHandlers:function(e,c){var f=(!c);
var d=f?this[e]:c;
if(d){$clearHandlers(d);
if(f){this[e]=null;
}}},_initializeColorElementsArray:function(){var k=this._webPaletteWrapper;
if(!k){return;
}var f=[];
var h=[];
var e=k.getElementsByTagName("a");
for(var g=0,j=e.length;
g<j;
g++){var d=e[g];
if(this._getColorBoxElement(d)){var c=this._getElementColor(d);
f[c]=d;
h[c]=g;
if(g>0){d.setAttribute("tabindex","-1");
}}}this._elementsByColor=f;
this._indexByColor=h;
},_setElementsSize:function(){if($telerik.getInvisibleParent(this.get_element())){return;
}var e=this._selectedContainer;
var d=b.PaletteModes.WebPalette;
var f="_setWebPaletteSize";
if(e==this._rgbPageView){d=b.PaletteModes.RGBSliders;
f="_setRGBSize";
}else{if(e==this._millionColorsPageView){d=(b.PaletteModes.HSB+b.PaletteModes.HSV);
f="_setMillionColorsSize";
}}var g=this._showIcon;
var k=g?this._paletteWrapperElement:this._wrapperElement;
if(!k){return;
}var c=this._getElementsSize(d);
var j=c.width;
if(parseInt(k.style.width,10)!=j){k.style.width=j+"px";
}this[f](c);
if(!g){var h=this._tabStrip;
if(h){var i=$telerik.getSize(h).height-1;
if(i>0&&parseInt(k.style.paddingBottom,10)!=i){k.style.paddingBottom=i+"px";
}}}},_setWebPaletteSize:function(e){var n=this._webPaletteWrapper;
if(!n){return;
}if(this.isModeEnabled(b.PaletteModes.WebPalette)){var m=e.colorBoxSize;
var g=$telerik.isOpera;
var j=e.colorBoxSizeOpera;
var d=n.getElementsByTagName("li");
for(var f=0,h=d.length;
f<h;
f++){var c=d[f];
var l=c.getElementsByTagName("span");
if(l.length>0){var k=l[0];
if(parseInt(k.style.width,10)!=m){k.style.width=m+"px";
k.style.height=m+"px";
}}if(g){c.style.width=j+"px";
}}}},_setRecentColorsSize:function(){var c=this._recentColorsWrapper;
if(this._showRecentColors&&c){c.style.height=this._getRecentColorWrapperSize()+"px";
}},_setRGBSize:function(c){var d=c.sliderSize;
this.get_redSlider().set_width(d);
this.get_greenSlider().set_width(d);
this.get_blueSlider().set_width(d);
},_setMillionColorsSize:function(c){},_getElementsSize:function(l){var n=this._paletteSizes;
var o=this._width;
var r=(o>0);
var m=this.getElementContentBox(this._paletteWrapperElement).horizontal;
var s=this._showIcon;
var w=s?m:this.getElementBox(this._wrapperElement).horizontal;
var v=m+this.getElementContentBox(this._multiPage).horizontal;
if(!s){v+=w;
}var k=v+this._getMinimumPaletteWidth();
var c,d,t;
if(this.isModeEnabled(b.PaletteModes.WebPalette)&&(l==b.PaletteModes.WebPalette)){var u=this._getWebPaletteElemenentsSize(o,k,v);
c=u.colorSize;
d=u.colorSizeOpera;
o=u.width-w;
n.webPalette=o;
}else{if(this.isModeEnabled(b.PaletteModes.RGBSliders)&&(l==b.PaletteModes.RGBSliders)){var q=this._defaultRGBWidth;
var p=Math.max(this._rgbSlidersMinSize,k);
if(!r){o=q;
}if(o<p){o=p;
}t=this._getRGBElemenentsSize(o,v);
o-=w;
n.rgbSliders=o;
}else{var g=this.isModeEnabled(b.PaletteModes.HSB)&&this.isPaletteMode(l,"HSB");
var h=this.isModeEnabled(b.PaletteModes.HSV)&&this.isPaletteMode(l,"HSV");
if(g||h){var i=Math.max(this._defaultHSBWidth,k);
var e=o;
if(!r||(r&&o<i)){e=i;
}e-=w;
n.hsb=e;
var j=Math.max(this._defaultHSVWidth,k);
var f=o;
if(!r||(r&&o<j)){f=j;
}f-=w;
n.hsv=f;
o=g?e:f;
}}}this._paletteSizes=n;
return{colorBoxSize:c,colorBoxSizeOpera:d,sliderSize:t,width:o};
},_getMinimumPaletteWidth:function(){var e=0;
var c=this._header;
if(c){e+=this.getElementBox(c).horizontal;
a(c).children(":visible").each(function(i,h){e+=h.offsetWidth+$telerik.getMarginBox(h).horizontal;
});
}var f=0;
var g=this._tabStrip;
if(g){f+=this.getElementBox(g).horizontal;
var d=parseInt($telerik.getCurrentStyle(g,"left",0),10);
if(!isNaN(d)){f+=d;
}a(g).children("ul").children(":visible").each(function(i,h){f+=h.offsetWidth+$telerik.getMarginBox(h).horizontal;
});
}return Math.max(0,Math.max(e,f));
},_getRecentColorWrapperSize:function(){var e=0;
var d=this._recentColorsWrapper;
if(d&&this._showRecentColors){var c=d.getElementsByTagName("li");
if(c.length>1&&d.style.height){return d.style.height;
}var g;
if(c.length==1){var f=c[0].getElementsByTagName("span");
if(f.length==1&&((a.trim(f[0].innerHTML)=="")||(a.trim(f[0].innerHTML)=="&nbsp;"))){g=c[0];
}}if(!g){g=this._createColorElement({},true);
d.appendChild(g);
}e=$telerik.getContentSize(d).height;
d.removeChild(g);
}return e;
},_getWebPaletteElemenentsSize:function(d,c,e){e+=this.getElementContentBox(this._webPalettePageView).horizontal;
return this._getColorBoxSize(d,c,e,this._webPaletteWrapper);
},_getColorBoxSize:function(l,k,q,o){var d=0;
var e=0;
var p=o;
if(p){q+=this.getElementContentBox(p).horizontal;
var j=$telerik.getFirstChildByTagName(p,"li");
if(j){e=$telerik.getOuterSize(j).width;
d+=this.getElementContentBox(j).horizontal;
var c=$telerik.getFirstChildByTagName(j,"a");
if(c){d+=this.getElementContentBox(c).horizontal;
var n=$telerik.getFirstChildByTagName(c,"span");
d+=this.getElementContentBox(n).horizontal;
}}}var i=this._columns;
var m=l;
if(!m){l=q+i*e;
}l=Math.max(k,l);
if(m){var h=l-q;
h=(h<1)?1:h;
e=parseInt(h/i,10);
e=(e<1)?1:e;
}var g=e;
var f=e-d;
f=(f<1)?1:f;
return{colorSize:f,colorSizeOpera:g,width:l};
},_getRGBElemenentsSize:function(d,h){h+=this.getElementContentBox(this._rgbPageView).horizontal;
var g=this._rgbSlidersDefaultSize-h;
var c=this._defaultRGBWidth;
if(d!=c){var e=this._redInput;
var f=$telerik.getChildrenByTagName(e.parentNode,"label")[0];
g=d-h;
g-=$telerik.getOuterSize(e).width;
g-=$telerik.getOuterSize(f).width;
if(g<50){g=50;
}}return g;
},_createPalette:function(k){if(this._webPaletteWrapper){return;
}var l=this._webPaletteWrapper=this._createElement("ul",null,{className:"rcpWebPalette"});
k.appendChild(l);
var g=0;
var e=this._columns;
var h=this._items;
if(this._tabIndex&&h.length>0){h[0].tabIndex=this._tabIndex;
}for(var f=0,j=h.length;
f<j;
f++){if(g==e){g=0;
var c=this._createElement("li",null,{className:"rcpBreakLine"});
l.appendChild(c);
}g++;
var d=this._createColorElement(h[f]);
l.appendChild(d);
}},_createColorElement:function(c,g){var f=(this._selectedColor==c.value)&&!g?"rcpSelectedColor":"rcpColorBox";
var d=this._createElement("li");
var e=this._createA(c.title,f,null,c.value);
if(c.tabIndex){e.setAttribute("tabindex",c.tabIndex);
}var h=this._createElement("span",c.value);
e.appendChild(h);
d.appendChild(e);
return d;
},_createHeader:function(j,f){if(!j){return;
}var g=this.isModeEnabled(b.PaletteModes.WebPalette);
var i=(this.isModeEnabled(b.PaletteModes.RGBSliders)||this.isModeEnabled(b.PaletteModes.HSB)||this.isModeEnabled(b.PaletteModes.HSV));
var e="rcpHeader";
var d=this._enableCustomColor;
if(!f){if(!this._previewColor&&!this._showEmptyColor&&!(g&&d)&&g){e+=" rcpEmptyHeader";
}}var l=f?$telerik.getChildByClassName(j,"rcpHeader"):this._header;
if(!l){l=this._createDiv(e);
j.appendChild(l);
if(!f){this._header=l;
}}this._createPreviewElement(l,f);
var h,k;
if(!f){this._createEmptyColorElement(l);
if(g&&d&&!this._customColorButton){var c=this._localization[14];
h=this._customColorButton=this._createA(c,"rcpImageButton rcpCustomColorButton");
if(this._tabIndex){h.setAttribute("tabindex",this._tabIndex);
}l.appendChild(h);
this._initializeCustomColorHandler(h);
k=this._createElement("span",c);
h.appendChild(k);
}this._createApplyButton((!g&&i),l);
}else{if(this._customColorOkButton){return;
}h=this._customColorCancelButton=this._createA(null,"rcpButton rcpCancelButton");
l.appendChild(h);
$addHandler(h,"click",Function.createDelegate(this,this._cancelClick));
k=this._createElement("span",this._localization[17]);
h.appendChild(k);
h=this._customColorOkButton=this._createA(null,"rcpButton rcpOkButton");
l.appendChild(h);
$addHandler(h,"click",Function.createDelegate(this,this._okClick));
k=this._createElement("span",this._localization[16]);
h.appendChild(k);
}},_createApplyButton:function(f,c){if(f&&!this._applyButton){var g=c?c:this._header;
if(!g){return;
}var d=this._applyButton=this._createA(null,"rcpButton rcpApplyButton");
if(this._tabIndex){d.setAttribute("tabindex",this._tabIndex);
}g.appendChild(d);
this._initializeApplyHandler(d);
var e=this._createElement("span",this._localization[7]);
d.appendChild(e);
}},_createRoundedCornersAndShadow:function(e,d){var c=this._createDiv("rcpRoundedRight");
e.appendChild(c);
c=this._createDiv("rcpRoundedBottomRight");
e.appendChild(c);
c=this._createDiv("rcpRoundedBottomLeft");
e.appendChild(c);
if($telerik.isIE6){return;
}if(d||this._showIcon){c=this._createDiv("rcpRightShadow");
e.appendChild(c);
c=this._createDiv("rcpCornerShadow");
e.appendChild(c);
c=this._createDiv("rcpBottomShadow");
e.appendChild(c);
}},_setRightRoundedCornerAndShadowHeight:function(d){var c=$telerik.getContentSize(d).height+"px";
a(d).children(".rcpRoundedRight").css("height",c);
a(d).children(".rcpRightShadow").css("height",c);
},_createRgbSliders:function(g){if(this.get_redSlider()){return;
}var f=this._createElement("ul");
g.appendChild(f);
var c=this.get_id();
var e=c+"_redSlider";
var d=c+"_redInput";
this._createRgbSliderWithInput(e,"rcpSlider rcpRedSlider","_redSlider",d,"rcpInput rcpRedInput","_redInput","R:",f);
e=c+"_greenSlider";
d=c+"_greenInput";
this._createRgbSliderWithInput(e,"rcpSlider rcpGreenSlider","_greenSlider",d,"rcpInput rcpGreenInput","_greenInput","G:",f);
e=c+"_blueSlider";
d=c+"_blueInput";
this._createRgbSliderWithInput(e,"rcpSlider rcpBlueSlider","_blueSlider",d,"rcpInput rcpBlueInput","_blueInput","B:",f);
this._updateRgbSlidersUI(this._getRgbFromHex());
},_createRgbSliderWithInput:function(k,j,l,e,d,f,h,n){var i=this._createElement("li");
n.appendChild(i);
var g=this._createElement("label",h,{htmlFor:e});
i.appendChild(g);
var m=this._createDiv(j,k);
i.appendChild(m);
this[l]=this._createSlider(m);
var c=this._createInput(d,this._rgbSlidersDefaultValue,e);
if(this._tabIndex){c.setAttribute("tabindex",this._tabIndex);
}i.appendChild(c);
this._initializeRgbInputHandler(c);
this[f]=c;
},_createSlider:function(c){var e=this._rgbSlidersDefaultValue;
var d=this._rgbSlidersDefaultSize+"px";
var g={itemData:[],_width:d,_skin:this._skin,maximumValue:e,value:e,_increaseText:this._localization[8],_decreaseText:this._localization[9],_tabIndex:-1,showIncreaseHandle:false,showDecreaseHandle:false,_dragText:this._localization[10]};
var f=$create(b.RadSlider,g,null,null,c);
this._initializeRgbSliderHandler(f);
return f;
},_rgbValuesToHex:function(g,e,c){var f="#";
var d=function(i){var h=parseInt(i,10).toString(16);
f=f+(h.length==1?"0"+h:h);
};
d(g);
d(e);
d(c);
d=null;
return f;
},_createHexColorInput:function(g,f){var c=f?null:this._selectedColor;
if(!c){var h=this._rgbSlidersDefaultValue;
c=this._rgbValuesToHex(h,h,h);
}var d=f?"_hexCustomColorInput":"_hexColorInput";
var e=this[d]=this._createInput("rcpHexInput",c);
if(this._tabIndex){e.setAttribute("tabindex",this._tabIndex);
}e.setAttribute("title",this._localization[18]);
e.setAttribute("dir","ltr");
g.appendChild(e);
if(!f&&this.isModeEnabled(b.PaletteModes.WebPalette)){e.readOnly="readonly";
}this._initializeHexHandler(e,f);
},_createMillionColors:function(n,h){if(this[h?"get_millionCustomColorsSlider":"get_millionColorsSlider"]()){return;
}var c=this.get_id();
var i=this[h?"_millionCustomColorsPalette":"_millionColorsPalette"]=this._createDiv("rcpMillionColorsPalette",(c+(h?"_millionCustomColorsPalette":"_millionColorsPalette")));
n.appendChild(i);
this._initializeMillionColorsPaletteHandler(h);
var e=this[h?"_millionCustomColorsHandle":"_millionColorsHandle"]=this._createElement("div","<!-- / -->",{className:"rcpMillionColorsHandle"},{top:"0px",left:"0px"});
i.appendChild(e);
this._createHandleResizeExtender(h);
var l=this._createDiv("rcpMillionColorsSlider",(c+(h?"_millionCustomColorsSlider":"_millionColorsSlider")));
n.appendChild(l);
var d=(h||this._isModeSelected(b.PaletteModes.HSB))?this._localization[11]:this._localization[12];
var j=0;
var k={itemData:[],_height:this._millionColorsSliderHeight,_width:this._millionColorsSliderWidth,_skin:this._skin,maximumValue:100,value:j,orientation:1,showIncreaseHandle:false,showDecreaseHandle:false,_tabIndex:-1,_dragText:d};
this[h?"set_millionCustomColorsSlider":"set_millionColorsSlider"]($create(b.RadSlider,k,null,null,l));
this._initializeMillionColorsSliderHandler(h);
var g=this._createDiv("rcpInputsWrapper");
n.appendChild(g);
var m=this._createElement("ul");
g.appendChild(m);
var f=h?"InputCustom":"Input";
this._createListItemWithInput((c+"_r"+f),"rcpInput rcpRedInput","r","R:","_initializeMillionColorsRgbInputHandler",m,null,h);
this._createListItemWithInput((c+"_g"+f),"rcpInput rcpGreenInput","g","G:","_initializeMillionColorsRgbInputHandler",m,null,h);
this._createListItemWithInput((c+"_b"+f),"rcpInput rcpBlueInput","b","B:","_initializeMillionColorsRgbInputHandler",m,null,h);
m=this._createElement("ul",null,{className:"rcpMillionColorsInputs"});
g.appendChild(m);
this._createListItemWithInput((c+"_h"+f),"rcpInput rcpHInput","h","H:","_initializeMillionColorsInputHandler",m,null,h);
this._createListItemWithInput((c+"_s"+f),"rcpInput rcpSInput","s","S:","_initializeMillionColorsInputHandler",m,null,h);
if(h||this.isModeEnabled(b.PaletteModes.HSB)){this._createListItemWithInput((c+"_l"+f),"rcpInput rcpLInput","l","B:","_initializeMillionColorsInputHandler",m,"rcpLInputWrapper",h);
}if(!h&&this.isModeEnabled(b.PaletteModes.HSV)){this._createListItemWithInput((c+"_v"+f),"rcpInput rcpVInput","v","V:","_initializeMillionColorsInputHandler",m,"rcpVInputWrapper");
}},_createListItemWithInput:function(f,e,g,j,c,m,k,h){var l=this._createElement("li",null,{className:k});
m.appendChild(l);
var i=this._createElement("label",j,{htmlFor:f});
l.appendChild(i);
var d=this._createInput(e,0,f);
if(this._tabIndex){d.setAttribute("tabindex",this._tabIndex);
}l.appendChild(d);
this[c](d,h);
this[h?"_millionCustomColorsInputs":"_millionColorsInputs"][g]=d;
},_createHandleResizeExtender:function(e){var c=this[e?"_millionCustomColorsHandle":"_millionColorsHandle"];
var g=this[e?"_millionCustomColorsPalette":"_millionColorsPalette"];
if(!c||!g){return;
}var f=$telerik.getCurrentStyle(g,"cursor","crosshair");
var d={};
d[f]=g;
this[e?"_millionCustomColorsResizeExtender":"_millionColorsResizeExtender"]=new b.ResizeExtender(this,c,d,null,null,f,false,true);
},_createCustomColorPalette:function(){var e=this._customColorPalette=this._createDiv(this.get_element().className+" rcpCustomColorWrapper");
var c=this.get_element();
var g=$telerik.getCurrentStyle(c,"zIndex",4000);
g=isNaN(g)?parseInt(c.style.zIndex,10):g;
g=isNaN(g)?4000:g;
e.style.zIndex=g+2;
e.style.position="absolute";
document.body.appendChild(e);
var d=this._createDiv("rcpPalette");
e.appendChild(d);
this._createRoundedCornersAndShadow(d,true);
this._createHeader(d,true);
var f=this._createDiv("rcpPageView rcpMillionColorsPageView rcpHsbPageView");
d.appendChild(f);
this._createMillionColors(f,true);
this._setRightRoundedCornerAndShadowHeight(d);
return e;
},_calculateRenderSettings:function(){this._defaultRGBWidth=this._isTouchSkin?300:270;
this._defaultHSBWidth=this._isTouchSkin?380:345;
this._defaultHSVWidth=this._isTouchSkin?380:(this.isSkin("Silk")||this.isSkin("Glow"))?345:249;
},_rgbSliderValueChanged:function(g,c){if(this._sliderAvoidRecursion){return;
}var f=this.get_redSlider().get_value();
var e=this.get_greenSlider().get_value();
var d=this.get_blueSlider().get_value();
this._sliderAvoidRecursion=true;
this._updateHexPreview(f,e,d);
this._updateRgbInputUI(g);
this._sliderAvoidRecursion=false;
},_millionColorsSliderValueChanged:function(f,c){if(this._sliderAvoidRecursion||this._millionColorsSliderAvoidRecursion){return;
}var e=(f===this.get_millionCustomColorsSlider());
var d=this._getMillionColorsCoordinates(e);
this._sliderAvoidRecursion=true;
this._updateMillionColorsInputsUI(d.x,d.y,e);
this._sliderAvoidRecursion=false;
},_hexColorChange:function(c,f){if(!c){return;
}if(!f&&this._isModeSelected(b.PaletteModes.WebPalette)){return;
}var h=c.target||c.srcElement;
if(!h){return;
}var d=h.value;
if(!this._validateHexValue(d)){this._previewCurrentColor((f?"#FFFFFF":this._selectedColor),null,null,f);
return;
}if(this._inputAvoidRecursion){return;
}if(f||this._selectedContainer){var g=this._getRgbFromHex(d);
var i=(f||this._isModeSelected(b.PaletteModes.HSB))?"_updateHslPaletteElementsUI":(this._isModeSelected(b.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":"_updateHsvPaletteElementsUI");
this._inputAvoidRecursion=true;
this[i](g,null,f);
this._inputAvoidRecursion=false;
}},_hexCustomColorChange:function(c){this._hexColorChange(c,true);
},_rgbInputValueChange:function(d){if(!d){return;
}var h=d.target||d.srcElement;
if(!this._validateDecInput(h,0,255)){h.value=this._getSliderFromInput(h).get_value();
return;
}if(this._inputAvoidRecursion){return;
}var g=parseInt(this._redInput.value,10);
var f=parseInt(this._greenInput.value,10);
var c=parseInt(this._blueInput.value,10);
this._inputAvoidRecursion=true;
this._updateHexPreview(g,f,c);
this._updateRgbSliderUI(null,null,h);
this._inputAvoidRecursion=false;
},_millionColorsInputValueChange:function(c,h){if(!c){return;
}var l=c.target||c.srcElement;
var f=h||this._isMillionColorsTabSelected().HSB;
var i=this[h?"_millionCustomColorsInputs":"_millionColorsInputs"];
var d=(l.id==i.h.id)?360:100;
if(!this._validateDecInput(l,0,d)){var k=f?"_resetHslInputValue":"_resetHsvInputValue";
this[k](l,h);
return;
}if(this._inputAvoidRecursion){return;
}var m=f?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
var g=parseInt(i.h.value,10);
var j={h:((g==360)?0:g),s:parseInt(i.s.value,10)/100,l:(i.l?parseInt(i.l.value,10)/100:null),v:(i.v?parseInt(i.v.value,10)/100:null),hueValue:g};
this._inputAvoidRecursion=true;
this[m](null,j,h);
this._inputAvoidRecursion=false;
},_millionCustomColorsInputValueChange:function(c){return this._millionColorsInputValueChange(c,true);
},_millionColorsRgbInputValueChange:function(c,d){if(!c){return;
}var h=c.target||c.srcElement;
if(!this._validateDecInput(h,0,255)){this._resetRgbInputValue(h,d);
return;
}if(this._inputAvoidRecursion){return;
}if(d||this._selectedContainer){var f=this[d?"_millionCustomColorsInputs":"_millionColorsInputs"];
var g={r:parseInt(f.r.value,10),g:parseInt(f.g.value,10),b:parseInt(f.b.value,10)};
var i=(d||this._isMillionColorsTabSelected().HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
this._inputAvoidRecursion=true;
this[i](g,null,d);
this._inputAvoidRecursion=false;
}},_millionCustomColorsRgbInputValueChange:function(c){return this._millionColorsRgbInputValueChange(c,true);
},_onMillionColorsPaletteMouseDown:function(d,f){if(!this._enabled){return;
}if(this._millionColorsAvoidRecursion){return;
}var h=this[f?"_millionCustomColorsPalette":"_millionColorsPalette"];
var i=$telerik.getLocation(h);
var k=$telerik.getContentSize(h);
var j={x:k.width-1,y:k.height-1};
var c=$telerik.getBorderBox(h);
var n=$telerik.getTouchEventLocation(d);
var g=$telerik.isTouchDevice?{left:n.x,top:n.y}:$telerik.getDocumentRelativeCursorPosition(d);
var l=Math.round(g.left-i.x-c.left);
var m=Math.round(g.top-i.y-c.top);
l=(l<0)?0:(l>j.x?j.x:l);
m=(m<0)?0:(m>j.y?j.y:m);
this._updateMillionColorsHandleUI(l,m,f);
this._millionColorsAvoidRecursion=true;
this._updateMillionColorsInputsUI(l,m,f);
this._millionColorsAvoidRecursion=false;
},_onMillionCustomColorsPaletteMouseDown:function(c){this._onMillionColorsPaletteMouseDown(c,true);
},onDragStart:function(c){if(!this._enabled){return false;
}var f=c.element;
var g=this._cachedMillionColorsHandleSize=$telerik.getSize(f);
var e=Math.floor(g.width/2);
var d=Math.floor(g.height/2);
var h=this._cachedIsCustomColor=(f===this._millionCustomColorsHandle);
var i=h?this._millionCustomColorsPalette:this._millionColorsPalette;
var j=$telerik.getContentSize(i);
this._cachedMillionColorsPaletteBounds=new Telerik.Web.UI.Bounds(-e,-d,(j.width+e*2)-1,(j.height+d*2)-1);
this._eventStartedInControl=true;
return true;
},onDragEnd:function(c){var d=c.element;
this._calculateMillionColorsByHandle({x:parseInt(d.style.left,10),y:parseInt(d.style.top,10)});
this._cachedMillionColorsHandleSize=null;
this._cachedMillionColorsPaletteBounds=null;
this._cachedIsCustomColor=null;
},onDrag:function(c){var d=this._cachedMillionColorsHandleSize;
var e=this._cachedMillionColorsPaletteBounds;
if(e.width<1||e.height<1){return false;
}c.width=d.width;
c.height=d.height;
var f=b.ResizeExtender.containsBounds(e,c);
if(!f){if(c.x<=e.x){c.x=e.x;
}else{if(e.x+e.width<=c.x+d.width){c.x=e.x+e.width-d.width;
}}if(c.y<=e.y){c.y=e.y;
}else{if(e.y+e.height<=c.y+d.height){c.y=e.y+e.height-d.height;
}}f=true;
}if(f){this._calculateMillionColorsByHandle(c);
}return f;
},_calculateMillionColorsByHandle:function(c){var d=this._cachedMillionColorsHandleSize;
this._updateMillionColorsInputsUI(c.x+(Math.floor(d.width/2)),c.y+(Math.floor(d.height/2)),this._cachedIsCustomColor);
},_updateRgbSlidersUI:function(c){if(!c){return;
}this._updateRgbSliderUI(this.get_redSlider(),c.r);
this._updateRgbSliderUI(this.get_greenSlider(),c.g);
this._updateRgbSliderUI(this.get_blueSlider(),c.b);
},_updateRgbSliderUI:function(f,g,c){var d=f;
var e=g;
if(!d){if(!c){return;
}d=this._getSliderFromInput(c);
e=parseInt(c.value,10);
}d.set_value(e);
},_updateRgbInputUI:function(c){if(!c){return;
}this._getInputFromSlider(c).value=c.get_value();
},_updateMillionColorsHandleUI:function(f,g,e){var c=this[e?"_millionCustomColorsHandle":"_millionColorsHandle"];
var d=$telerik.getSize(c);
$telerik.setLocation(c,{x:f-Math.floor(d.width/2),y:g-Math.floor(d.height/2)});
},_updateMillionColorsInputsUI:function(g,h,e){if(this._inputAvoidRecursion){return;
}var f=this._isMillionColorsTabSelected();
var d=e||f.HSB;
if(!d&&!f.HSV){return;
}var c=this[d?"_getHslFromCoordinates":"_getHsvFromCoordinates"](g,h,e);
var i=this[d?"_hslToRgb":"_hsvToRgb"](c.h,c.s,c[d?"l":"v"]);
this[d?"_updateHslSliderBackground":"_updateHsvPaletteBackground"](c,e);
this._updateMillionColorsInputsValues(i,c,e);
this._updateHexPreview(i.r,i.g,i.b,e);
},_updateMillionColorsInputsValues:function(f,e,d){var c=this[d?"_millionCustomColorsInputs":"_millionColorsInputs"];
if(f){c.r.value=f.r;
c.g.value=f.g;
c.b.value=f.b;
}c.h.value=Math.round(e.hueValue);
c.s.value=Math.round(e.s*100);
if(e.l!=null){c.l.value=Math.round(e.l*100);
}if(e.v!=null){c.v.value=Math.round(e.v*100);
}},_updateHslPaletteElementsUI:function(g,d,f){if(!g&&!d){return;
}var h=(g)?g:this._hslToRgb(d.h,d.s,d.l);
var e=(d)?d:this._rgbToHsl(g);
this._updateHexPreview(h.r,h.g,h.b,f);
this._updateMillionColorsInputsValues(h,e,f);
this._updateHslSliderBackground(e,f);
var c=f?this._customPaletteRange:this._hsbPaletteRange;
this._updateMillionColorsHandleUI(Math.round(e.h*c.x/360),c.y-Math.round(e.s*c.y),f);
var i=f?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
i.set_value(100-Math.round(e.l*100));
},_updateHslSliderBackground:function(d,e){var c=this._hslToRgb(d.h,d.s,0.5);
var f=e?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
if(f._trackElement){f._trackElement.style.backgroundColor=this._rgbValuesToHex(c.r,c.g,c.b);
}},_updateHsvPaletteElementsUI:function(f,c){if(!f&&!c){return;
}var g=(f)?f:this._hsvToRgb(c.h,c.s,c.v);
var d=(c)?c:this._rgbToHsv(f);
this._updateHexPreview(g.r,g.g,g.b);
this._updateMillionColorsInputsValues(g,d);
this._updateHsvPaletteBackground(d);
var e=this._hsvPalettePoints;
this._updateMillionColorsHandleUI(Math.round(d.s*e.x),e.y-Math.round(d.v*e.y));
this.get_millionColorsSlider().set_value(100-Math.round(d.h*100/360));
},_updateHsvPaletteBackground:function(d){var c=this._hsvToRgb(d.h,1,1);
this._millionColorsPalette.style.backgroundColor=this._rgbValuesToHex(c.r,c.g,c.b);
},_updateHexPreview:function(g,d,c,e){var f=this._rgbValuesToHex(g,d,c);
this._previewCurrentColor(f,true,null,e);
},_getRgbFromHex:function(c){var d=c;
if(!d){var e=this._selectedColor;
d=(e)?e:"#FFFFFF";
}return this._hexToRgb(d);
},_resetRgbInputValue:function(g,h){var j;
var d=this[h?"_hexCustomColorInput":"_hexColorInput"];
if(d){j=this._getRgbFromHex(d.value);
}else{var c=this._getMillionColorsCoordinates(h);
if(h||this._isModeSelected(b.PaletteModes.HSB)){var e=this._getHslFromCoordinates(c.x,c.y,h);
j=this._hslToRgb(e.h,e.s,e.l);
}else{if(this._isModeSelected(b.PaletteModes.HSV)){var f=this._getHsvFromCoordinates(c.x,c.y);
j=this._hsvToRgb(f.h,f.s,f.v);
}}}var i=this[h?"_millionCustomColorsInputs":"_millionColorsInputs"];
g.value=(g===i.r)?j.r:(g===i.g?j.g:j.b);
},_resetHslInputValue:function(e,f){var c=this._getMillionColorsCoordinates(f);
var d=this._getHslFromCoordinates(c.x,c.y,f);
this._updateMillionColorsInputsValues(null,d,f);
},_resetHsvInputValue:function(e){var c=this._getMillionColorsCoordinates();
var d=this._getHsvFromCoordinates(c.x,c.y);
this._updateMillionColorsInputsValues(null,d);
},_validateDecInput:function(d,g,f){var c=parseInt(d.value,10);
var e=(!isNaN(c));
if(e){e=(c>=g&&c<=f);
}return e;
},_validateHexValue:function(c){var d=/^#?(([0-9a-f]{3})|([0-9a-f]{6}))$/i;
return d.test(c);
},_getSliderFromInput:function(c){var d=this._getColorElementPrefix(c.id.toLowerCase());
return this[d+"Slider"];
},_getInputFromSlider:function(d){var c=this._getColorElementPrefix(d.get_id().toLowerCase());
return this[c+"Input"];
},_getColorElementPrefix:function(c){var d="";
if(!c){return d;
}if(c.indexOf("red")>-1){d="_red";
}else{if(c.indexOf("green")>-1){d="_green";
}else{if(c.indexOf("blue")>-1){d="_blue";
}}}return d;
},_getMillionColorsCoordinates:function(e){var c=this[e?"_millionCustomColorsHandle":"_millionColorsHandle"];
if(!c){return{x:0,y:0};
}var d=$telerik.getSize(c);
var f=parseInt(c.style.left,10)+Math.floor(d.width/2);
var g=parseInt(c.style.top,10)+Math.floor(d.height/2);
return{x:f,y:g};
},_getHslFromCoordinates:function(h,i,f){var c=f?this._customPaletteRange:this._hsbPaletteRange;
var e=(h/c.x*360);
var d=(h==c.x)?0:e;
var j=1-i/c.y;
var k=f?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
var g=1-(k.get_value()/100);
return{h:d,s:j,l:g,hueValue:e};
},_getHsvFromCoordinates:function(f,g){var i=this.get_millionColorsSlider().get_value();
var e=360*(1-i/100);
var d=(i==0)?0:e;
var c=this._hsvPalettePoints;
var h=f/c.x;
var j=1-g/c.y;
return{h:d,s:h,v:j,hueValue:e};
},_hexToRgb:function(c){if(!c){return null;
}var e={r:0,g:0,b:0};
if(c.indexOf("#")!=-1){c=c.substring(1,c.length);
}if(c.length==3){var d=function(f){return(f+f);
};
c=c.replace(/([0-9a-f])/gi,d);
}e.r=parseInt(c.substring(0,2),16);
e.g=parseInt(c.substring(2,4),16);
e.b=parseInt(c.substring(4,6),16);
return e;
},_hslToRgb:function(d,h,e){var c=this._hueToRgb(d);
c=this._addRgbVectors(this._multiplyRgbVectorByNum(h,c),this._multiplyRgbVectorByNum((1-h),{r:128,g:128,b:128}));
if(e!=0.5){var f=(e<0.5)?{r:0,g:0,b:0}:{r:255,g:255,b:255};
var g=2*Math.abs(0.5-e);
c=this._addRgbVectors(this._multiplyRgbVectorByNum(g,f),this._multiplyRgbVectorByNum((1-g),c));
}return c;
},_hsvToRgb:function(c,e,h){var d={r:0,g:0,b:0};
if(e==0){d={r:h,g:h,b:h};
}else{var f=(1-e)*h;
var g=h*e*(c%60)/60;
if(c<60){d={r:h,g:(f+g),b:f};
}else{if(c<120){d={r:h-g,g:h,b:f};
}else{if(c<180){d={r:f,g:h,b:f+g};
}else{if(c<240){d={r:f,g:h-g,b:h};
}else{if(c<300){d={r:f+g,g:f,b:h};
}else{if(c<360){d={r:h,g:f,b:h-g};
}}}}}}}return this._multiplyRgbVectorByNum(255,d);
},_hueToRgb:function(c){var f={};
var e=c/60;
var d=e-Math.floor(e);
if(e<1){f={r:1,g:d,b:0};
}else{if(e<2){f={r:(1-d),g:1,b:0};
}else{if(e<3){f={r:0,g:1,b:d};
}else{if(e<4){f={r:0,g:(1-d),b:1};
}else{if(e<5){f={r:d,g:0,b:1};
}else{f={r:1,g:0,b:(1-d)};
}}}}}return this._multiplyRgbVectorByNum(255,f);
},_rgbToHsl:function(g){var d={};
var f=Math.min(Math.min(g.r,g.g),g.b);
var e=Math.max(Math.max(g.r,g.g),g.b);
var h=(e+f);
var c=e-f;
d.l=h/(2*255);
if(c==0){d.h=0;
d.s=0;
}else{d.s=c/((d.l<=0.5)?h:(2*255-h));
d.h=this._rgbToHue(g,c);
}d.hueValue=d.h;
return d;
},_rgbToHsv:function(g){var d={};
var e=Math.max(Math.max(g.r,g.g),g.b);
var f=Math.min(Math.min(g.r,g.g),g.b);
var c=e-f;
d.v=(e/255);
if(c==0){d.h=0;
d.s=0;
}else{d.s=(c/e);
d.h=this._rgbToHue(g,c);
}d.hueValue=d.h;
return d;
},_rgbToHue:function(e,c){var d=0;
if(e.r>=e.g&&e.g>=e.b){d=60*(e.g-e.b)/c;
}else{if(e.g>=e.r&&e.r>=e.b){d=60+60*(e.g-e.r)/c;
}else{if(e.g>=e.b&&e.b>=e.r){d=120+60*(e.b-e.r)/c;
}else{if(e.b>=e.g&&e.g>=e.r){d=180+60*(e.b-e.g)/c;
}else{if(e.b>=e.r&&e.r>=e.g){d=240+60*(e.r-e.g)/c;
}else{if(e.r>=e.b&&e.b>=e.g){d=300+60*(e.r-e.b)/c;
}}}}}}return Math.round(d);
},_isModeSelected:function(f,c,i){var e=false;
var g=c?c:this._selectedContainer;
if(g){if(f==b.PaletteModes.WebPalette){e=(this._webPalettePageView===g);
}else{if(f==b.PaletteModes.RGBSliders){e=(this._rgbPageView===g);
}else{var h=i?i:this._selectedTab;
var d=this._isMillionColorsTabSelected(h);
e=(f==b.PaletteModes.HSB)?d.HSB:d.HSV;
}}}return e;
},_isMillionColorsTabSelected:function(d){var c=d;
if(!c){c=this._selectedTab;
}if(c){var e=c.getElementsByTagName("span")[0].innerHTML;
return{HSB:(e==this._localization[5]),HSV:(e==this._localization[6])};
}else{return{HSB:this.isModeEnabled(b.PaletteModes.HSB),HSV:this.isModeEnabled(b.PaletteModes.HSV)};
}},_fixInRgbRange:function(c,d){if(d){c=Math.round(c);
}if(c<0){c=0;
}else{if(c>255){c=255;
}}return c;
},_addRgbVectors:function(c,d){return{r:this._fixInRgbRange(c.r+d.r),g:this._fixInRgbRange(c.g+d.g),b:this._fixInRgbRange(c.b+d.b)};
},_multiplyRgbVectorByNum:function(c,d){return{r:this._fixInRgbRange(d.r*c,true),g:this._fixInRgbRange(d.g*c,true),b:this._fixInRgbRange(d.b*c,true)};
},isModeEnabled:function(c){return c&this._paletteModes?true:false;
},isPaletteMode:function(d,c){return d&b.PaletteModes[c];
},_createTabStrip:function(){if(this._multiPage){return;
}var d=this.get_element();
var c=this.get_id();
var n=this._showIcon;
var k=this._paletteWrapperElement=this._createDiv("rcpPalette",(c+"_palette"));
if(n){if(!$telerik.isIE6){k.style.position="absolute";
}k.style.visibility="hidden";
}d.appendChild(k);
this._createRoundedCornersAndShadow(k);
if(n){var s=$telerik.getCurrentStyle(d,"zIndex",4000);
s=isNaN(s)?parseInt(d.style.zIndex,10):s;
s=isNaN(s)?4000:s;
k.style.zIndex=s+1;
}var r=this.isModeEnabled(b.PaletteModes.WebPalette);
var m=this.isModeEnabled(b.PaletteModes.RGBSliders);
var g=this.isModeEnabled(b.PaletteModes.HSB);
var h=this.isModeEnabled(b.PaletteModes.HSV);
var l=this.get_id();
var p=null;
if((r+m+g+h)>1){var q=this._tabStrip=this._createDiv("rcpTabs");
k.appendChild(q);
p=this._createElement("ul");
q.appendChild(p);
}this._createHeader(k);
var i=this._multiPage=this._createElement("div",null,{className:"rcpViews"});
k.appendChild(i);
var f=l+"_webPalette";
var e="rcpPageView";
var o=true;
if(r){this._createTabWithContainer(o,e,i,"_webPalettePageView","_createPalette",this._localization[3],p,f);
o=false;
}if(m){f=l+"_rgbSliders";
this._createTabWithContainer(o,(e+" rcpRGBPageView"),i,"_rgbPageView","_createRgbSliders",this._localization[4],p,f);
o=false;
}var j;
if(g){f=l+"_millionColors";
j=e+" rcpMillionColorsPageView rcpHsbPageView";
this._createTabWithContainer(o,j,i,"_millionColorsPageView","_createMillionColors",this._localization[5],p,f);
o=false;
}if(h){f=l+"_millionColors";
j=e+" rcpMillionColorsPageView rcpHsvPageView";
this._createTabWithContainer(o,j,i,"_millionColorsPageView","_createMillionColors",this._localization[6],p,f);
}this._setElementsSize();
this._initializeColorElementsArray();
this._initializePalleteEventHandlers();
if(this._recentColors&&this._recentColors.length>0){this._updateRecentColors();
}if(!this._popupBehavior){this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:c+"PopupBehavior",parentElement:this._iconWrapperElement,overlay:this._overlay,keepInScreenBounds:this._keepInScreenBounds,manageVisibility:false},null,null,k);
}this._setRightRoundedCornerAndShadowHeight(k);
},_createRecentColors:function(c){if(!this._showRecentColors||!c||this._recentColorsWrapper){return;
}var d=document.createElement("div");
c.appendChild(d);
var i=this.get_id()+"_recentColors";
var g=this._localization[15];
if(g){var f=this._createElement("span",g,{className:"rcpRecentColorsLabel"});
d.appendChild(f);
}var h=this._recentColorsWrapper=this._createElement("ul",null,{className:"rcpRecentColors",id:i});
d.appendChild(h);
this._setRecentColorsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
if($telerik.isIE6){var e=this.get_element();
e.style.cssText=e.style.cssText;
}$addHandlers(h,{mouseover:this._onBoxMouseOver,mouseup:this._onRecentBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._recentColorsKeyDown},this);
},_createTabWithContainer:function(h,d,g,i,f,l,k,e){var j;
if(k){j=this._createTab(l,e);
k.appendChild(j);
}var c=this[i];
if(!c){c=this[i]=this._createDiv(d,e,null,(h?null:"none"));
g.appendChild(c);
}if(h){this._updateTabSelection(j,c);
this[f](c);
}},_createTab:function(g,f){var e=this._createElement("li");
var c=this._createA(g,null,f);
if(this._tabIndex){c.setAttribute("tabindex",this._tabIndex);
}this._initializeTabHandler(c);
e.appendChild(c);
var d=this._createElement("span",g);
c.appendChild(d);
return e;
},_createEmptyColorElement:function(e){if(!this._showEmptyColor||this._emptyColorElement){return;
}var d=this._localization[2];
var c=this._emptyColorElement=this._createA(d,"rcpImageButton rcpEmptyColor");
c.id=this.get_id()+"_emptycolor";
if(this._tabIndex){c.setAttribute("tabindex",this._tabIndex);
}e.appendChild(c);
var f=this._createElement("span",d);
c.appendChild(f);
},_createPreviewElement:function(d,c){if(!c&&!this._previewColor){return;
}var e=c?"#fff":this._selectedColor;
if(!e){e="#fff";
}var h=c?"_customColorPreviewElement":"_previewElement";
if(this[h]){return;
}var g=this.get_id()+(c?"_customColorPreview":"_preview");
var f=this[h]=this._createDiv("rcpColorPreview",g,e,null,"<!-- / -->");
d.appendChild(f);
this._createHexColorInput(d,c);
},_tabClicked:function(g){if(this._enabled){var p=(g.target||g.srcElement);
var q=this._getParentByTagName(p,"li");
var c=this._getParentByTagName(p,"a");
if(!c){return;
}var d=c.getAttribute("rel");
var f=$get(d);
if(!q||!f){return;
}var o=this._isModeSelected(b.PaletteModes.RGBSliders,f);
var i=this._isModeSelected(b.PaletteModes.HSB,f,q);
var n=i||this._isModeSelected(b.PaletteModes.HSV,f,q);
var m="webPalette";
this._updateHeader(o||n);
this._updateTabSelection(q,f);
if(this._isModeSelected(b.PaletteModes.WebPalette,f)){this._createPalette(f);
}else{if(o){this._createRgbSliders(f);
m="rgbSliders";
}else{if(n){this._createMillionColors(f);
m=i?"hsb":"hsv";
var j=this.get_millionColorsSlider();
i?j.set_dragText(this._localization[11]):j.set_dragText(this._localization[12]);
}}}this._setElementsSize();
var l=this._paletteSizes[m];
var k=this._paletteWrapperElement;
var r=this._showIcon?k:this._wrapperElement;
if(r&&(parseInt(r.style.width,10)!=l)){r.style.width=l+"px";
}this._setRightRoundedCornerAndShadowHeight(k);
this.set_selectedColor(this._selectedColor,false,true);
this._updateOverlaySize();
if($telerik.isIE){var h=this.get_element();
h.style.cssText=h.style.cssText;
}}return $telerik.cancelRawEvent(g);
},_updateTabSelection:function(g,c){if(g&&c){var d=this._isMillionColorsTabSelected(g);
if(d.HSB){Sys.UI.DomElement.removeCssClass(c,"rcpHsvPageView");
Sys.UI.DomElement.addCssClass(c,"rcpHsbPageView");
}else{if(d.HSV){Sys.UI.DomElement.removeCssClass(c,"rcpHsbPageView");
Sys.UI.DomElement.addCssClass(c,"rcpHsvPageView");
}}var f=this._selectedTab;
var e=this._selectedContainer;
if(f&&e){Sys.UI.DomElement.removeCssClass(f,"rcpSelectedTab");
e.style.display="none";
}Sys.UI.DomElement.addCssClass(g,"rcpSelectedTab");
c.style.display="";
}this._selectedTab=g;
this._selectedContainer=c;
},_updateHeader:function(e){if(e&&!this._applyButton){this._createApplyButton(e);
}var c=this._applyButton;
if(c){c.style.display=e?"":"none";
}var d=this._customColorButton;
if(d){d.style.display=e?"none":"";
}var g=this._hexColorInput;
if(g){g.readOnly=e?"":"readonly";
}var f=this._header;
if(f){Sys.UI.DomElement.removeCssClass(f,"rcpEmptyHeader");
if(!e&&!d&&!g&&!this._emptyColorElement){Sys.UI.DomElement.addCssClass(f,"rcpEmptyHeader");
}}},_updateOverlaySize:function(){var d=this._paletteWrapperElement;
var c=d._hideWindowedElementsIFrame;
if(!c){return;
}$telerik.setSize(c,$telerik.getOuterSize(d));
},_initializeTabHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._tabClicked));
},_initializeApplyHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._applyClick));
},_initializeCustomColorHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._customColorClick));
},_initializeHexHandler:function(d,e){if(!e){if(!this.isModeEnabled(b.PaletteModes.RGBSliders)&&!this.isModeEnabled(b.PaletteModes.HSB)&&!this.isModeEnabled(b.PaletteModes.HSV)){return;
}}var c=e?"_hexCustomColorChange":"_hexColorChange";
var f=e?"_hexCustomKeyDown":"_hexKeyDown";
$addHandlers(d,{blur:this[c],keydown:this[f]},this);
},_initializeRgbInputHandler:function(c){$addHandlers(c,{blur:this._rgbInputValueChange,keydown:this._rgbInputKeyDown},this);
},_initializeRgbSliderHandler:function(d){var c=this;
var f=function(h,g){c._rgbSliderValueChanged(h,g);
};
var e=function(){c._eventStartedInControl=true;
};
d.add_valueChanged(f);
if(this._showIcon){d.add_slideStart(e);
}},_initializeMillionColorsRgbInputHandler:function(d,e){if(!d){return;
}var c=e?"_millionCustomColorsRgbInputValueChange":"_millionColorsRgbInputValueChange";
var f=e?"_millionCustomColorsRgbInputKeyDown":"_millionColorsRgbInputKeyDown";
$addHandlers(d,{blur:this[c],keydown:this[f]},this);
},_initializeMillionColorsInputHandler:function(d,e){if(!d){return;
}var c=e?"_millionCustomColorsInputValueChange":"_millionColorsInputValueChange";
var f=e?"_millionCustomColorsInputKeyDown":"_millionColorsInputKeyDown";
$addHandlers(d,{blur:this[c],keydown:this[f]},this);
},_initializeMillionColorsSliderHandler:function(c){var e=c?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
if(!e){return;
}var d=this;
var g=function(i,h){d._millionColorsSliderValueChanged(i,h);
};
var f=function(){d._eventStartedInControl=true;
};
e.add_valueChanged(g);
if(this._showIcon){e.add_slideStart(f);
}},_initializeMillionColorsPaletteHandler:function(c){var d=this[c?"_millionCustomColorsPalette":"_millionColorsPalette"];
if(d){$telerik.addMobileHandler(this,d,"mousedown",this[c?"_onMillionCustomColorsPaletteMouseDown":"_onMillionColorsPaletteMouseDown"]);
}},_createElement:function(k,g,d,i){var f=document.createElement(k);
for(var c in d){var e=d[c];
if(e!=null&&e.toString()!=""){f[c]=e;
}}for(var h in i){var j=i[h];
if(j!=null&&j.toString()!=""){f.style[h]=j;
}}if(g){f.innerHTML=g;
}return f;
},_createA:function(f,d,e,c){return this._createElement("a",null,{className:d,href:"#",title:f,rel:e},{backgroundColor:c});
},_createDiv:function(d,f,c,e,g){return this._createElement("div",g,{className:d,id:f},{background:c,display:e});
},_createInput:function(c,e,d){return this._createElement("input",null,{className:c,id:d,type:"text",value:e});
},getElementBox:function(e){var d={horizontal:0,vertical:0};
if(e){var c=$telerik.getBorderBox(e);
var f=$telerik.getPaddingBox(e);
d.horizontal=c.horizontal+f.horizontal;
d.vertical=c.vertical+f.vertical;
}return d;
},getElementContentBox:function(d){var c=this.getElementBox(d);
if(d){var e=$telerik.getMarginBox(d);
c.horizontal=c.horizontal+e.horizontal;
c.vertical=c.vertical+e.vertical;
}return c;
},showPalette:function(){if(this._paletteDisplayed){return;
}this._createTabStrip();
var i=this._popupBehavior;
var e=i._firstPopup;
var k=$telerik.isOpera?$telerik.originalGetLocation(this._iconWrapperElement).y-$telerik.getLocation(this._iconWrapperElement).y:0;
if(this.get_keepInScreenBounds()){this._paletteWrapperElement._originalHeight=this._paletteWrapperElement.style.height;
this._paletteWrapperElement.style.height=this.getPaletteHeight()+"px";
}i.set_x(0);
i.set_y($telerik.getSize(this._iconWrapperElement).height+k);
i.show();
if(this.get_keepInScreenBounds()){this._paletteWrapperElement.style.height=this._paletteWrapperElement._originalHeight;
this._paletteWrapperElement._originalHeight=null;
}var h=this._paletteWrapperElement;
h.style.visibility="";
if(e&&this._selectedContainer){var f=this._paletteSizes;
var g=this._isModeSelected(b.PaletteModes.WebPalette)?f.webPalette:(this._isModeSelected(b.PaletteModes.RGBSliders)?f.rgbSliders:(this._isModeSelected(b.PaletteModes.HSB)?f.hsb:f.hsv));
var j=this._showIcon?h:this._wrapperElement;
if(j&&(parseInt(j.style.width,10)!=g)){j.style.width=g+"px";
}}var c=this._applyButton;
var d=this._customColorButton;
if($telerik.isIE6&&(c||d)){if(c){c.style.visibility="visible";
}if(d){d.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(c){c.style.visibility="";
}if(d){d.style.visibility="";
}}),0);
}this.set_selectedColor(this._selectedColor,false,true);
this._paletteDisplayed=true;
this.raiseEvent("popUpShow",Sys.EventArgs.Empty);
},hidePalette:function(){var d=this._popupBehavior;
if(d){var c=this._paletteWrapperElement;
c.style.top="-9999px";
c.style.left="-9999px";
d.hide();
}this._paletteDisplayed=false;
},getIconContainer:function(){return this._iconWrapperElement;
},getPaletteContainer:function(){return this._paletteWrapperElement;
},getPaletteHeight:function(){var c=a(this._paletteWrapperElement);
return c.find(".rcpRoundedRight").height()+c.find(".rcpRoundedBottomRight").height()+c.find(".rcpTabs").height();
},get_selectedColor:function(){return this._selectedColor;
},set_selectedColor:function(o,m,l){if(!o||(o.toString().toLowerCase()=="null")){o=null;
}else{if(!this._validateHexValue(o)){return;
}if(o.indexOf("#")!=-1){o=o.substring(1,o.length);
}if(o.length==3){var f=function(p){return(p+p);
};
o=o.replace(/([0-9a-f])/gi,f);
}o="#"+o;
}var k=this._selectedColor;
if(!k){k=null;
}if(o!=null){o=o.toUpperCase();
}if(o!=k){var c=a.raiseCancellableControlEvent(this,"colorChanging",{oldColor:k,newColor:o});
if(c){var j=this._getBoxElementByColor(k);
if(j!=null){j.focus();
}var i=this._getBoxElementByColor(o);
if(i!=null){i.blur();
}return;
}}this._selectedColor=o;
this._previewCurrentColor(o);
if(this._showIcon){this._setIconColor(o);
}if(!m&&this._selectedContainer){if(this._isModeSelected(b.PaletteModes.WebPalette)){var g=this._emptyColorElement;
var e=this._getMarkedElement();
if(e!=null){if(e!=g){e.className="rcpColorBox";
}}e=this._getBoxElementByColor(o);
if(e!=null){this._setMarkedElement(e);
if(e!=g){e.className="rcpSelectedColor";
}}}else{var n=this._isModeSelected(b.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":(this._isModeSelected(b.PaletteModes.HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI");
var d=(o===null||o===undefined)&&this._isModeSelected(b.PaletteModes.HSB)?{r:128,g:128,b:128}:this._getRgbFromHex(o);
this._millionColorsSliderAvoidRecursion=true;
this[n](d);
this._millionColorsSliderAvoidRecursion=false;
}}if(!l){this._updateRecentColors(o);
}this.updateClientState();
if(this._selectedColor!=k){var h=new b.ColorPickerColorChangeEventArgs(k);
this.raiseEvent("colorChange",h);
if(this._autoPostBack){this._raiseColorChangedServerEvent();
}}},get_selectedColorTitle:function(){var c=this._getBoxElementByColor(this._selectedColor);
if(c!=null){return c.getAttribute("title");
}return this._selectedColor;
},get_enabled:function(){return this._enabled;
},set_enabled:function(l){if(this._enabled==l){return;
}this._enabled=l;
if(!this._wrapperElement){return;
}var d=[this.get_redSlider(),this.get_greenSlider(),this.get_blueSlider(),this.get_millionColorsSlider()];
var f,h;
for(f=0,h=d.length;
f<h;
f++){var k=d[f];
if(k&&k.set_enabled){k.set_enabled(l);
}}var c=[this._hexColorInput,this._redInput,this._greenInput,this._blueInput,this._accessKeyTextbox];
var j=this._millionColorsInputs;
if(j){c=c.concat([j.r,j.g,j.b,j.h,j.s,j.l,j.v]);
}var e=this.get_element(),g;
if(l){Sys.UI.DomElement.removeCssClass(e,"rcpDisabled");
e.removeAttribute("disabled");
for(f=0,h=c.length;
f<h;
f++){g=c[f];
if(g){g.removeAttribute("disabled");
}}}else{Sys.UI.DomElement.addCssClass(e,"rcpDisabled");
e.setAttribute("disabled","disabled");
for(f=0,h=c.length;
f<h;
f++){g=c[f];
if(g){g.setAttribute("disabled","disabled");
}}}},get_overlay:function(){return this._overlay;
},set_overlay:function(e){this._overlay=e;
var c=this._customColorPopupBehavior;
if(c){c.set_overlay(e);
}var d=this._popupBehavior;
if(d){d.set_overlay(e);
if(this._showIcon&&this._paletteDisplayed){d.show();
}}},get_keepInScreenBounds:function(){return this._keepInScreenBounds;
},set_keepInScreenBounds:function(e){this._keepInScreenBounds=e;
var c=this._customColorPopupBehavior;
if(c){c.set_keepInScreenBounds(e);
}var d=this._popupBehavior;
if(d){d.set_keepInScreenBounds(e);
if(this._showIcon&&this._paletteDisplayed){d.show();
}}},_initializeEventHandlers:function(){this._initializePalleteEventHandlers();
if(this._showIcon){$addHandlers(this._iconLink,{click:this._onIconMouseUp,keydown:this._iconKeyDown},this);
$addHandlers(this.get_element(),{mousedown:this._onWrapperMouseDown},this);
this._mouseUpHandler=Function.createDelegate(this,this._onMouseUp);
$telerik.addExternalHandler(document,"mouseup",this._mouseUpHandler);
}},_applyAccessKey:function(){if(!this._accessKey){return;
}if($telerik.isChrome||$telerik.isSafari){var d=document.createElement("div");
d.style.width="0px";
d.style.height="0px";
d.style.overflow="hidden";
this.get_element().appendChild(d);
var c=this._accessKeyTextbox=document.createElement("input");
c.setAttribute("type","text");
var e=this.get_id()+"ColorPickerAccessKey";
c.setAttribute("name",e);
c.setAttribute("id",e);
c.setAttribute("accessKey",this._accessKey);
d.appendChild(c);
$addHandlers(c,{focus:this._accessKeyPressed},this);
}},_accessKeyPressed:function(c){var d=this._iconLink;
if(!d){d=this._getFirstChildByTagName(this._tabStrip,"a");
if(!d){d=this._getFirstChildByTagName(this._webPaletteWrapper,"a");
if(!d){d=this._redInput;
if(!d&&this._millionColorsInputs){d=this._millionColorsInputs.r;
}}}}if(d){d.focus();
}},_getFirstChildByTagName:function(d,e){if(d){var c=d.getElementsByTagName(e);
if(c&&c.length>0){return c[0];
}}return null;
},_iconKeyDown:function(c){c=c.rawEvent||c;
var d=c.keyCode||c.which;
var f=(d==Sys.UI.Key.esc)||(c.altKey&&d==Sys.UI.Key.up);
var g=c.altKey&&(d==Sys.UI.Key.down);
if(!g&&!f){return;
}$telerik.cancelRawEvent(c);
if(f){this.hidePalette();
}else{this.showPalette();
}return false;
},_hexCustomKeyDown:function(c){this._hexKeyDown(c,true);
},_hexKeyDown:function(c,d){c=c.rawEvent||c;
var f=c.keyCode||c.which;
if(f!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(c);
this._hexColorChange(c,d);
if(d){this._okClick();
}else{this._applyClick(c);
}return false;
},_rgbInputKeyDown:function(c){c=c.rawEvent||c;
var d=c.keyCode||c.which;
if(d!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(c);
this._rgbInputValueChange(c);
this._applyClick(c);
return false;
},_millionCustomColorsRgbInputKeyDown:function(c){this._millionColorsRgbInputKeyDown(c,true);
},_millionColorsRgbInputKeyDown:function(c,d){c=c.rawEvent||c;
var f=c.keyCode||c.which;
if(f!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(c);
this._millionColorsRgbInputValueChange(c,d);
if(d){this._okClick();
}else{this._applyClick(c);
}return false;
},_millionCustomColorsInputKeyDown:function(c){this._millionColorsInputKeyDown(c,true);
},_millionColorsInputKeyDown:function(c,d){c=c.rawEvent||c;
var f=c.keyCode||c.which;
if(f!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(c);
this._millionColorsInputValueChange(c,d);
if(d){this._okClick();
}else{this._applyClick(c);
}return false;
},_webPaletteKeyDown:function(g){g=g.rawEvent||g;
var i=g.keyCode||g.which;
if(i==Sys.UI.Key.enter){$telerik.cancelRawEvent(g);
this._onBoxClick(g);
}else{var f=this._getColorBoxElement(g.target||g.srcElement);
if(!f){return;
}var d=this._indexByColor[this._getElementColor(f)];
var c=this._columns;
var h=this._webPaletteWrapper.getElementsByTagName("a");
var j=d;
switch(i){case Sys.UI.Key.up:j-=c;
break;
case Sys.UI.Key.down:j+=c;
break;
case Sys.UI.Key.left:j-=1;
break;
case Sys.UI.Key.right:j+=1;
break;
case Sys.UI.Key.home:j=0;
break;
case Sys.UI.Key.end:j=h.length-1;
break;
default:return;
}j=Math.max(0,Math.min(h.length-1,j));
var k=h[j];
k.focus();
this._previewCurrentColor(this._getElementColor(k),true,k.title);
}$telerik.cancelRawEvent(g);
return false;
},_recentColorsKeyDown:function(f){f=f.rawEvent||f;
var h=f.keyCode||f.which;
if(h==Sys.UI.Key.enter){this._onRecentBoxClick(f);
}else{var k=this._recentColors;
if(!k){return;
}var d=this._getColorBoxElement(f.target||f.srcElement);
if(!d){return;
}var c=Array.indexOf(k,this._getElementColor(d));
var g=this._recentColorsWrapper.getElementsByTagName("a");
var i=c;
switch(h){case Sys.UI.Key.up:i-=1;
break;
case Sys.UI.Key.down:i+=1;
break;
case Sys.UI.Key.left:i-=1;
break;
case Sys.UI.Key.right:i+=1;
break;
case Sys.UI.Key.home:i=0;
break;
case Sys.UI.Key.end:i=g.length-1;
break;
default:return;
}i=Math.max(0,Math.min(g.length-1,i));
var j=g[i];
j.focus();
this._previewCurrentColor(this._getElementColor(j),true,j.title);
}$telerik.cancelRawEvent(f);
return false;
},_initializePalleteEventHandlers:function(){var d=this._webPaletteWrapper;
if(d){$addHandlers(d,{mouseover:this._onBoxMouseOver,mouseup:this._onBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._webPaletteKeyDown},this);
}var c=this._emptyColorElement;
if(c&&this._showEmptyColor){$addHandlers(c,{click:this._onEmptyColorClick},this);
}},_disposeHandlers:function(){var d=this._webPaletteWrapper;
if(d){$clearHandlers(d);
}var c=this._emptyColorElement;
if(c&&this._showEmptyColor){$clearHandlers(c);
}if(this._showIcon){$clearHandlers(this._iconLink);
$clearHandlers(this.get_element());
$telerik.removeExternalHandler(document,"mouseup",this._mouseUpHandler);
this._iconWrapperElement=null;
this._iconLink=null;
}this._mouseUpHandler=null;
},_raiseColorChangedServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},_onMouseUp:function(c){if(!this._enabled){return;
}if(this._eventStartedInControl){this._eventStartedInControl=false;
return;
}var d=c.target||c.srcElement;
if($telerik.isDescendantOrSelf(this._paletteWrapperElement,d)){return;
}this.hidePalette();
},_onBoxMouseOver:function(d){if(!this._enabled){return;
}var f=this._getColorBoxElement(d.target||d.srcElement);
if(f==null){return;
}var c=this._getElementColor(f);
this._previewCurrentColor(c,true,f.title);
},_onBoxMouseOut:function(d){if($telerik.isMouseOverElementEx(this._webPaletteWrapper,d)){return;
}var f=this._recentColorsWrapper;
var c=this.get_selectedColor();
if(f){if($telerik.isMouseOverElementEx(f,d)){return;
}if(this._selectedContainer&&!this._isModeSelected(b.PaletteModes.WebPalette)){c=this._getColorFromRGBControls();
}}this._previewCurrentColor(c);
},_applyClick:function(c){if(this._enabled){var f=this._hexColorInput;
var d=f?f.value:this._getColorFromRGBControls();
this._applyColorAndClose(d,true);
}return $telerik.cancelRawEvent(c);
},_cancelClick:function(c){return this._closeCustomColorPalette(c);
},_okClick:function(c){if(this._enabled){var f=this._hexCustomColorInput;
var d=f?f.value:this._getColorFromRGBControls(true);
this.set_selectedColor(d);
return this._closeCustomColorPalette(c);
}return $telerik.cancelRawEvent(c);
},_customColorClick:function(g){var h=this._customColorModalExtender;
var j=this._customColorPopupBehavior;
if(!j){var f=this._customColorPalette;
if(!f){f=this._createCustomColorPalette();
}h=this._customColorModalExtender=new b.ModalExtender(f);
j=this._customColorPopupBehavior=$create(Telerik.Web.PopupBehavior,{id:this.get_id()+"CustomColorPopupBehavior",overlay:this._overlay,parentElement:document.documentElement,keepInScreenBounds:this._keepInScreenBounds},null,null,f);
}var c=this._getCentralBounds();
j.set_x(c.x);
j.set_y(c.y);
j.show();
h.show();
this._millionColorsSliderAvoidRecursion=true;
this._updateHslPaletteElementsUI(this._getRgbFromHex("#808080"),null,true);
this._millionColorsSliderAvoidRecursion=false;
var i=this._customColorOkButton;
var d=this._customColorCancelButton;
if($telerik.isIE6&&(i||d)){if(i){i.style.visibility="visible";
}if(d){d.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(i){i.style.visibility="";
}if(d){d.style.visibility="";
}}),0);
}this._millionCustomColorsInputs.r.focus();
if(this._showIcon){this.hidePalette();
}return $telerik.cancelRawEvent(g);
},_getCentralBounds:function(){var d=this._customColorPalette;
var c={width:parseInt($telerik.getCurrentStyle(d,"width","350px"),10),height:parseInt($telerik.getCurrentStyle(d,"height","325px"),10)||325};
var e=this._getViewportBounds();
var f=parseInt((e.width-c.width)/2,10);
var g=parseInt((e.height-c.height)/2,10);
c.x=f+e.scrollLeft;
c.y=g+e.scrollTop;
return c;
},_getViewportBounds:function(){var c=$telerik.getClientBounds();
var d=$telerik.getCorrectScrollLeft(document.documentElement)||$telerik.getCorrectScrollLeft(document.body);
var e=document.documentElement.scrollTop||document.body.scrollTop;
c.scrollLeft=d;
c.scrollTop=e;
if(this.isIE){if(c.width==0){c.width=document.body.clientWidth;
}if(c.height==0){c.height=document.body.clientHeight;
}}return c;
},_getColorFromRGBControls:function(d){var e;
if(!d&&this._isModeSelected(b.PaletteModes.RGBSliders)){e={r:this.get_redSlider().get_value(),g:this.get_greenSlider().get_value(),b:this.get_blueSlider().get_value()};
}else{var c=this[d?"_millionCustomColorsInputs":"_millionColorsInputs"];
e={r:parseInt(c.r.value,10),g:parseInt(c.g.value,10),b:parseInt(c.b.value,10)};
}return this._rgbValuesToHex(e.r,e.g,e.b);
},_onEmptyColorClick:function(c){if(this._enabled){this._applyColorAndClose(null);
}return $telerik.cancelRawEvent(c);
},_applyColorAndClose:function(c,f,e){var d=this._showIcon;
this.set_selectedColor(c,(d||f),e);
if(d){this.hidePalette();
}},_closeCustomColorPalette:function(c){var d=this._customColorModalExtender;
if(d){d.hide();
}var f=this._customColorPopupBehavior;
if(f){f.hide();
}return $telerik.cancelRawEvent(c);
},_onWrapperMouseDown:function(c){if(!this._enabled){return;
}this._eventStartedInControl=true;
},_onIconMouseUp:function(c){if(this._enabled){if(this._paletteDisplayed){this.hidePalette();
}else{this.showPalette();
}}return $telerik.cancelRawEvent(c);
},_getElementColor:function(c){if(c==this._emptyColorElement){return null;
}return c.firstChild.innerHTML;
},_setIconColor:function(c){var e=(c)?c:this._localization[13];
var d=a.trim(this._localization[0]+" "+this._localization[1].toString().replace("{0}",e));
if(d!=""){this._iconWrapperElement.title=d;
}this._iconElement.style.backgroundColor=(c)?c:"#FFFFFF";
},_onBoxClick:function(c,d){if(this._enabled){this._eventStartedInControl=false;
if(c.button){return;
}var f=this._getColorBoxElement(c.target||c.srcElement);
if(!f){return;
}this._applyColorAndClose(this._getElementColor(f),false,d);
}return $telerik.preventDefault(c);
},_onRecentBoxClick:function(c){return this._onBoxClick(c,true);
},_getMarkedElement:function(){var g=this._markedElement;
if(g){return g;
}var h=this._webPaletteWrapper;
if(!h){return null;
}var c=h.getElementsByTagName("A");
for(var e=0,f=c.length;
e<f;
e++){var d=c[e];
if(d.className=="rcpSelectedColor"){return d;
}}return null;
},_setMarkedElement:function(c){this._markedElement=c;
},_getColorBoxElement:function(c){var e=3;
var d=0;
while(d<e){if(c.className=="rcpColorBox"||c.className=="rcpSelectedColor"||c.className.indexOf("rcpEmptyColor")>-1){return c;
}d++;
c=c.parentNode;
}return null;
},_getParentByTagName:function(c,f){var e=3;
var d=0;
while(d<e){if(c.tagName.toLowerCase()==f){return c;
}d++;
c=c.parentNode;
}return null;
},_getBoxElementByColor:function(c){if(!c){return this._emptyColorElement;
}c=c.toUpperCase();
return this._elementsByColor[c];
},_previewCurrentColor:function(c,i,h,f){if(!this.get_isInitialized()){return;
}if(i&&(c!=this._lastPreviewColor)){var d=new b.ColorPickerColorPreviewEventArgs(c);
this.raiseEvent("colorPreview",d);
}this._lastPreviewColor=c;
if(!this._previewColor&&!f){return;
}if(c==null){c="#FFFFFF";
h=this._localization[2];
}c=c.toUpperCase();
if(!h){h=c;
}var g=this[f?"_customColorPreviewElement":"_previewElement"];
if(g){g.style.backgroundColor=c;
}var e=this[f?"_hexCustomColorInput":"_hexColorInput"];
if(e){e.value=c;
}},_updateRecentColors:function(h){var m=this._recentColors;
if(h){var f=Array.indexOf(m,h);
if(f>-1){m.splice(f,1);
}if(m.unshift(h)>this._columns){m.pop();
}}if(this._showRecentColors&&m.length>0){if(!this._recentColorsWrapper){this._createRecentColors(this._multiPage);
}var n=this._recentColorsWrapper;
if(n){var o=this._recentElementsByColor;
for(var e=0,g=m.length;
e<g;
e++){var l=m[e];
var k=this._getBoxElementByColor(l);
var d={value:l,title:(k?k.title:l)};
var c=o[e];
if(!c){var j=this._createColorElement(d,true);
n.appendChild(j);
o[o.length]=c=$telerik.getFirstChildByTagName(j,"a");
}else{c.title=d.title;
c.style.backgroundColor=d.value;
var p=$telerik.getFirstChildByTagName(c,"span");
if(p){p.innerHTML=d.value;
}}c.removeAttribute("tabIndex");
if(e>0){c.setAttribute("tabIndex","-1");
}else{if(this._tabIndex){c.setAttribute("tabIndex",this._tabIndex);
}}}if(o.length>0){n.style.height="";
}}}},saveClientState:function(){var d=["selectedColor"];
var e={};
for(var c=0;
c<d.length;
c++){e[d[c]]=this["get_"+d[c]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(e);
}};
a.registerControlProperties(b.RadColorPicker,{paletteModes:b.PaletteModes.WebPalette,hiddenSlider:null,redSlider:null,greenSlider:null,blueSlider:null,millionColorsSlider:null,millionCustomColorsSlider:null});
a.registerControlEvents(b.RadColorPicker,["load","colorPreview","colorChanging","colorChange","popUpShow"]);
b.RadColorPicker.registerClass("Telerik.Web.UI.RadColorPicker",b.RadWebControl);
})();
