Type.registerNamespace("Telerik.Web.UI.Dock");
(function(a,b){var e=["Transform","webkitTransform","OTransform","MozTransform","msTransform"];
var c=["BackfaceVisibility","webkitBackfaceVisibility","OBackfaceVisibility","MozBackfaceVisibility","msBackfaceVisibility"];
var d=Telerik.Web.Browser;
a.registerEnum(b,"DockMode",{Floating:1,Docked:2,Default:3});
$telerik.toDock=function(f){return f;
};
$telerik.findDock=$find;
Telerik.Web.UI.RadDock=function(f){Telerik.Web.UI.RadDock.initializeBase(this,[f]);
this._initialized=false;
this._enableDrag=true;
this._top=0;
this._left=0;
this._dockZoneID=null;
this._title=null;
this._commands=null;
this._closed=false;
this._collapsed=false;
this._pinned=false;
this._handle=null;
this._resizable=false;
this._width="300px";
this._height=null;
this._expandedHeight=0;
this._handle=null;
this._form=null;
this._isDragged=false;
this._accessKey="";
this._tabIndex=0;
this._draggedCssClass="rdDragHelper";
this._dropDownTouchScroll=null;
this.set_handle=this.set_handle;
this._isCustomHandle=false;
this._draggableWidget=null;
this._resizableWidget=null;
};
Telerik.Web.UI.RadDock.DragDataType="RadDock";
Telerik.Web.UI.RadDock.prototype={_isDockRightToLeft:function(){var f=this._isRightToLeft;
if(f==null){var g=this.get_element();
if(g){f=this._isRightToLeft=$telerik.isRightToLeft(g);
}}return f;
},_setResizeLimit:function(){var l=this.get_dockZoneID(),h=null,g=null,j=this._renderingView.get_minWidth(),i=this._renderingView.get_minHeight();
if(l){var k=$find(l);
var f=this._getBounds();
if(k.get_isHorizontal()){h=f.width+this._caluclateZoneFreeSpace(k).width;
}else{g=f.height+this._caluclateZoneFreeSpace(k).height;
}}this._resizableWidget.set_constraints({minWidth:this._renderingView.get_minWidth(),minHeight:this._renderingView.get_minHeight(),maxWidth:h?Math.max(j,h):null,maxHeight:g?Math.max(this.get_height()?this._element.offsetHeight:i,g):null});
},_updateSizeValues:function(){var f=this._getBounds();
this._width=f.width;
this._height=f.height;
},_moveElements:function(g,h){while(g.childNodes&&g.childNodes.length>0){var f=g.childNodes[0];
g.removeChild(f);
h.appendChild(f);
}},_initResizableWidget:function(){if(this._resizableWidget&&this._resizableWidget.dispose){this._resizableWidget.dispose();
}if(!this._resizable){return;
}if(d.webkit){this._kickStartCssTransform();
}this._resizableWidget=new Telerik.Web.UI.Widgets.Resizable(this._element,{appendHandleToElement:!$telerik.isIE,handles:this._getAvailableHandles()});
if(this._renderingView){this._setResizeLimit();
}if(this._collapsed){this._resizableWidget.hideHandles();
}this._resizableWidget.add_resizeStart(a.proxy(this._resizeStartHandler,this));
this._resizableWidget.add_resizing(a.proxy(this._resizingHandler,this));
this._resizableWidget.add_resizeEnd(a.proxy(this._resizeEndHandler,this));
},_getAvailableHandles:function(){var f;
var h=this.get_dockZoneID();
if(h){var g=$find(h);
f=g.get_isHorizontal()?[{direction:this._isDockRightToLeft()?"W":"E",element:null}]:[{direction:"S",element:null}];
}return f;
},_resizeStartHandler:function(g,f){if(this._collapsed){f.set_cancel(true);
}this.resizeHelper={width:this.get_width(),height:this.get_height()||this._element.clientHeight,offset:{top:this.get_top(),left:this.get_left()}};
this.raise_resizeStart(new Sys.EventArgs());
},_resizingHandler:function(i,f){var g=f.get_direction(),h=1,j=1;
if(g.indexOf("W")>-1){j=-1;
this.set_left(parseInt(this.resizeHelper.offset.left,10)+f.get_delta().x);
}if(g.indexOf("N")>-1){h=-1;
this.set_top(parseInt(this.resizeHelper.offset.top,10)+f.get_delta().y);
}if(g.indexOf("W")>-1||g.indexOf("E")>-1){this.set_width(parseInt(this.resizeHelper.width,10)+j*f.get_delta().x);
}if(g.indexOf("N")>-1||g.indexOf("S")>-1){this.set_height(parseInt(this.resizeHelper.height,10)+h*f.get_delta().y);
}},_resizeEndHandler:function(g,f){this.raise_resizeEnd(new Sys.EventArgs());
var i=this.get_dockZoneID();
if(i){var h=$find(i);
h._resetDocksResizeHandles();
}},_makeResizable:function(){this._enableMoveResize();
},_caluclateZoneFreeSpace:function(h){var k=$telerik.getContentSize(h.get_element());
var g=h.get_isHorizontal()?this._getDocksFromCurrentRow(h):h.get_docks();
for(var j=0;
j<g.length;
j++){var f=g[j]._getBounds();
k.height-=f.height;
k.width-=f.width;
}return k;
},_getDocksFromCurrentRow:function(h){var k=[],g=h.get_docks(),f=this._getLocation().y;
for(var j=0;
j<g.length;
j++){if(g[j]._getLocation().y==f){k.push(g[j]);
}}return k;
},_initializeDrag:function(){if(this._handle){this._disposeDrag();
if(this.get_enableDrag()&&!this.get_pinned()){if(this._draggableWidget&&this._draggableWidget.dispose){this._draggableWidget.dispose();
}this._draggableWidget=new Telerik.Web.UI.Widgets.Draggable(this._element,{handle:this._handle,shouldPreventDefault:false,validateNestedElementsAsTriggers:true});
this._draggableWidget.add_dragStarting(a.proxy(this._dragStartHandler,this));
this._draggableWidget.add_dragging(a.proxy(this._draggingHandler,this));
this._draggableWidget.add_dragEnd(a.proxy(this._dragEndHandler,this));
}}},_draggingHandler:function(g,f){this._hitZone=this.dockingZoneHitTest(f._domEvent);
this.raise_drag(new Sys.EventArgs());
$telerik.cancelRawEvent(f.get_domEvent());
},_dragStartHandler:function(h,f){if(!this.get_enableDrag()||this.get_pinned()){return false;
}this.set_isDragged(true);
var g=new Sys.CancelEventArgs();
g.ownerEvent=f.get_domEvent();
this.raiseEvent("dragStart",g);
f.set_cancel(g.get_cancel());
if(g.get_cancel()){return false;
}this._renderingView.get_contentContainer().style.overflow="hidden";
this.addCssClass(this._draggedCssClass);
this._startDragDrop();
},_dragEndHandler:function(g,f){var h=this._hitZone;
if(!h){h=this._hitZone=this.dockingZoneHitTest(f._domEvent);
}if(h){if(h.canDrop(this)){h.drop(this);
}else{this._restorePosition();
}}else{if(this.canDrop()){this.drop();
}else{this._restorePosition();
}}this._renderingView.get_contentContainer().style.overflow="auto";
this.removeCssClass(this._draggedCssClass);
if(this._resizableWidget){this._resizableWidget.repaint();
}this.raise_dragEnd(new Sys.EventArgs());
},_disposeDrag:function(){if(this._handle&&this._draggableWidget){this._draggableWidget.dispose();
this._draggableWidget=null;
}},_startDragDrop:function(){var h=this.get_element();
this.originalZIndex=h.style.zIndex;
var f=this._getBounds(h);
var g=this._getBorderBox(h);
f.width-=g.horizontal;
f.height-=g.vertical;
h.style.width=f.width+"px";
h.style.zIndex="9999999";
var i=this._getLocation(h);
if(h.parentNode!=this._form){this._form.appendChild(h);
}var j=$find(this.get_dockZoneID());
if(j){j._showPlaceholder(this,i);
}this._setLocation(i);
},get_isDragged:function(){return this._isDragged;
},set_isDragged:function(f){this._isDragged=f;
},get_dockZones:function(){if(typeof(Telerik.Web.UI.RadDockZonesGlobalArray)=="undefined"){return[];
}return Telerik.Web.UI.RadDockZonesGlobalArray;
},dockingZoneHitTest:function(j){var m=null,o;
var h=this.get_dockZones();
var g=this.get_element();
var l=[];
var k=[];
for(o=0;
o<h.length;
o++){if(h[o].hitTest(this,j,false)){l[l.length]=h[o].get_element();
k[k.length]=h[o];
}}if(l.length>0){if(l.length==1){m=$find(l[0].id);
}else{if(l.length>1){g.style.display="none";
var n=document.elementFromPoint(j.clientX,j.clientY);
g.style.display="";
if(n){var f=document.body;
while(n!=f){for(o=0;
o<l.length;
o++){if(n==l[o]){if(n.id){m=$find(n.id);
}break;
}}if(m!=null){break;
}n=n.parentNode;
}}}}for(o=0;
o<k.length;
o++){if(k[o]!=m){k[o].dragLeaveTarget(this);
}else{m.hitTest(this,j,true);
}}}return m;
},canDrop:function(){return this.get_dockMode()!=Telerik.Web.UI.DockMode.Docked;
},drop:function(){var f=new Sys.CancelEventArgs();
this.raise_dockPositionChanging(f);
this.get_element().style.zIndex=this.originalZIndex;
if(f.get_cancel()){this._restorePosition();
}else{if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this.undock();
if(this._resizable){this._initResizableWidget();
this._setResizeLimit();
}this.raise_dockPositionChanged(new Sys.EventArgs());
}},clone:function(p){if(!p){p="RadDockClone_"+(new Date()-100);
}var n=this.get_handle();
this._setHandle(null);
var u=this._grip==n?"_G":"_H";
var v=false;
if(n&&!n.id){n.id=this.get_id()+u;
v=true;
}var k=this.get_commands();
for(var q in k){$clearHandlers(k[q].get_element());
}var r=this._renderingView.clone(p);
this._removeClonedHandles(r);
var t=$telerik.cloneControl(this,Telerik.Web.UI.RadDock,r);
this._setHandle(n);
if(n&&(n.className.indexOf("rdTitleBar")==-1)){var s=$get(n.id,r);
s.id=p+u;
t.set_handle(s);
if(v){n.removeAttribute("id");
}}var l=t.get_commandsContainer();
if(l){var j=t.get_commandsContainer().getElementsByTagName("a");
for(var o=0;
o<j.length;
o++){var h=j[o];
h.removeAttribute("control");
}}if(this._originalCommandsObject){t.set_commands(Array.clone(this._originalCommandsObject));
}t._initializeCommands();
for(var g in k){var m=k[g];
var f=k[g].get_element();
$addHandlers(f,{click:m.onCommand,mousedown:m.onMouseDown},m);
}t.set_uniqueID(p);
if(t.get_dockZone()){t.get_dockZone()._resetDockIndices();
}return t;
},_removeClonedHandles:function(f){var g=a(".rrHandle",f);
for(var h=0;
h<g.length;
h++){f.removeChild(g[h]);
}},getCommand:function(f){return this._commands?this._commands[f]:null;
},get_handle:function(){return this._handle;
},set_handle:function(f){this._isCustomHandle=true;
this._setHandle(f);
},_setHandle:function(f){this._disposeDrag();
this._handle=f;
this._initializeDrag();
},subtractPoints:function(f,g){return{x:f.x-g.x,y:f.y-g.y};
},addPoints:function(f,g){return{x:f.x+g.x,y:f.y+g.y};
},_getRenderingView:function(){if(this._renderMode==Telerik.Web.UI.RenderMode.Classic){return new Telerik.Web.UI.Dock.ClassicView(this);
}else{if(this._renderMode==Telerik.Web.UI.RenderMode.Lite){return new Telerik.Web.UI.Dock.LightweightView(this);
}else{throw Error("RadDock with ID: "+this.get_id()+" has not defined RenderMode");
}}},initialize:function(){Telerik.Web.UI.RadDock.callBaseMethod(this,"initialize");
this._renderingView=this._getRenderingView();
if(this._isDockRightToLeft()){var f=this.get_element();
Sys.UI.DomElement.addCssClass(f,"rdRtl");
Sys.UI.DomElement.addCssClass(f,"RadDock_"+this.get_skin()+"_rtl");
}if(!$telerik.isTouchDevice){this._resetCSS3Rules();
}this._renderingView.initialize();
this._initializeCommands();
this._updateToggleCommandsState();
this._setPinUnpinVisibility();
var j=this.get_element();
var h=j.parentNode;
var i=$telerik.getInvisibleParent(this.get_element().parentNode);
var g=(i!=null);
if(g){var k={position:j.style.position,top:j.style.top,left:j.style.left};
j.parentNode.removeChild(j);
j.style.position="absolute";
j.style.top="-5000px";
j.style.left="-5000px";
document.body.appendChild(j);
j.style.position=k.position;
j.style.top=k.top;
j.style.left=k.left;
j.parentNode.removeChild(j);
var m=this.get_dockZone();
if(m&&Telerik.Web.UI.RadDockZone.isInstanceOfType(m)){h.insertBefore(j,m._placeholder);
}else{h.appendChild(j);
}}if(Telerik.Web.UI.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}if(!g&&this.get_dockZoneID()==""){var l=window.theForm;
h.removeChild(j);
l.appendChild(j);
}j.style.visibility="";
this._registerShortcuts();
this._initResizableWidget();
this.updateClientState();
this.raise_initialize();
this.raise_load();
this.add_dockPositionChanged(Function.createDelegate(this,function(){this.conditionalPostback("dockPositionChanged");
}));
},dispose:function(){this._createTouchScrollExtender(false);
this._renderingView.dispose();
Telerik.Web.UI.RadDock.callBaseMethod(this,"dispose");
},_resetCSS3Rules:function(){this._setCss3Rules("none","visible");
},_kickStartCssTransform:function(){this._setCss3Rules("","visible");
},_setCss3Rules:function(h,f){var g=this._element.style;
Array.forEach(e,function(i){g[i]=h;
});
Array.forEach(c,function(i){g[i]=f;
});
},_createTouchScrollExtender:function(h){var f=$get(this.get_id()+"_C");
if(f){var g=this._dropDownTouchScroll;
if(g){if(!h){g.dispose();
this._dropDownTouchScroll=null;
}}else{if(h){this._dropDownTouchScroll=new Telerik.Web.UI.TouchScrollExtender(f);
this._dropDownTouchScroll.initialize();
}}}},undock:function(){var f=this.get_element();
if(f.parentNode!=this._form){this._form.appendChild(f);
f.style.position="absolute";
}var g=this._getLocation(f);
this.set_left(g.x);
this.set_top(g.y);
var h=$find(this.get_dockZoneID());
if(h){this.set_dockZoneID("");
h._resetDockIndices();
this._unfitWidth();
}this._setPinUnpinVisibility();
this.updateClientState();
},_fitWidth:function(){this._renderingView.fitWidth();
},_unfitWidth:function(){this._renderingView.unfitWidth();
},_initializeCommands:function(){if(!this.get_commandsContainer()){this._commands={};
return;
}var j=this._renderingView.getCommandsElements();
var l=this._commands;
if(l){this._commands={};
for(var m=0;
m<l.length;
m++){var h=l[m];
var f=eval(h.clientTypeName);
if(f==Telerik.Web.UI.DockCommand||f.inheritsFrom(Telerik.Web.UI.DockCommand)){h.radDock=this;
var k=null;
if(h.command){k={command:eval(h.command)};
delete h.command;
}var g=$create(f,h,k,null,j[m]);
this._commands[g.get_name()]=g;
}else{throw Error.invalidOperation(h.clientTypeName+" does not inherit from Telerik.Web.UI.DockCommand.");
}}}},_updateToggleCommandsState:function(){var f=this.getCommand("ExpandCollapse");
if(f){f.set_state(this.get_collapsed()?2:1);
}var g=this.getCommand("PinUnpin");
if(g){g.set_state(this.get_pinned()?2:1);
}},_setPinUnpinVisibility:function(){var f=this.getCommand("PinUnpin");
if(f){f.get_element().style.display=this.get_dockZoneID()?"none":"";
}},_getBounds:function(f){if(!f){f=this.get_element();
}return $telerik.getBounds(f);
},_getMarginBox:function(f){if(!f){f=this.get_element();
}return $telerik.getMarginBox(f);
},_getBorderBox:function(f){if(!f){f=this.get_element();
}return $telerik.getBorderBox(f);
},_resetPosition:function(){var f=this.get_element();
f.style.top="";
f.style.left="";
f.style.position="";
if(typeof(this.originalZIndex)=="undefined"){this.originalZIndex="";
}f.style.zIndex=this.originalZIndex;
},_restorePosition:function(){var f=$find(this.get_dockZoneID());
if(f){f.dock(this,this.get_index());
}else{this.undock();
}},_getLocation:function(f){if(!f){f=this.get_element();
}return $telerik.getLocation(f);
},_setLocation:function(f){$telerik.setLocation(this.get_element(),f);
},_setSize:function(h,g){var f=this._getBounds();
this._setHeight(g);
if(!h){h=f.width;
}this._setWidthHtmlEl(h);
},get_contentContainer:function(){this._ensureRenderingView();
return this._renderingView.get_contentContainer();
},get_titleBar:function(){this._ensureRenderingView();
return this._renderingView.get_titleBar();
},get_commandsContainer:function(){this._ensureRenderingView();
return this._renderingView.get_commandsContainer();
},get_titleElement:function(){this._ensureRenderingView();
return this._renderingView.get_titleElement();
},_ensureRenderingView:function(){if(!this._renderingView){this._renderingView=this._getRenderingView();
this._renderingView.initialize();
}},executeCommand:function(g){var f=this.getCommand(g);
if(!f){return;
}if(b.DockToggleCommand.isInstanceOfType(f)){f.set_state(f.get_state()==1?2:1);
}f.onCommand();
},addShortCut:function(f,g){if(this._shortCutManager){this._shortCutManager.addShortCut(f,g);
}},removeShortCut:function(f){if(this._shortCutManager){this._shortCutManager.removeShortCut(f);
}},setShortCut:function(f,g){if(this._shortCutManager){this._shortCutManager.setShortCut(f,g);
}},_getDefaultShortCuts:function(){var f=[["Close","ESC"],["PinUnpin","Ctrl+F12"],["ExpandCollapse","Ctrl+F11"]];
return f;
},_registerShortcuts:function(g){this._attachShortcutHandlers(g!==false);
if(!this._shortCutManager){this._shortCutManager=new b.ShortCutManager(this._getDefaultShortCuts());
this._shortCutManager.addShortCuts(this.get_shortcuts());
}var f=this.get_element();
f.setAttribute("tabIndex",this._tabIndex.toString());
if(this._accessKey){f.setAttribute("accessKey",this._accessKey);
}},_attachShortcutHandlers:function(f){if(f){this._keyDownDelegate=Function.createDelegate(this,this._keyDown);
$addHandler(this.get_element(),"keydown",this._keyDownDelegate);
}else{$removeHandler(this.get_element(),"keydown",this._keyDownDelegate);
this._keyDownDelegate=null;
}},_keyDown:function(f){var h=this._shortCutManager.isShortCutHit(f.rawEvent);
if(!h){return;
}var g=new b.Dock.ShortCutCancelEventArgs(f.rawEvent,h);
this.raiseEvent("shortCutHit",g);
if(!g.get_cancel()){this.executeCommand(h.get_name());
}$telerik.cancelRawEvent(f.rawEvent);
return false;
},saveClientState:function(){var f={Top:this.get_top(),Left:this.get_left(),DockZoneID:this.get_dockZoneID(),Collapsed:this.get_collapsed(),Pinned:this.get_pinned(),Resizable:this.get_resizable(),Closed:this.get_closed(),Width:this.get_width(),Height:this.get_height(),ExpandedHeight:this._expandedHeight,Index:this.get_index(),IsDragged:this.get_isDragged()};
return Sys.Serialization.JavaScriptSerializer.serialize(f);
},conditionalPostback:function(f){if(this.get_autoPostBack()){this.doPostBack(f);
}},doPostBack:function(f){__doPostBack(this.get_uniqueID(),f);
},get_top:function(){return this._top;
},set_top:function(f){if(f!=""){f=parseInt(f,10);
if(this._initialized){this.get_element().style.top=f+"px";
}}this._top=f;
this.updateClientState();
},get_left:function(){return this._left;
},set_left:function(f){if(f!=""){f=parseInt(f,10);
if(this._initialized){this.get_element().style.left=f+"px";
}}this._left=f;
this.updateClientState();
},_onCloseAnimationEnd:function(){var g=this.get_element();
var f=this.getCommand("Close");
var h=this.get_titleElement();
if(h!=null){h.style.display="block";
}if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}if(this._closed){this._resizableWidget.hideHandles();
}else{this._resizableWidget.showHandles();
}}if(this._closed){g.style.display="none";
if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this._resizableWidget.hideHandles();
}this.updateClientState();
if(f){Telerik.Web.UI.DockCloseCommand.callBaseMethod(f,"onCommand");
}}else{g.style.display="block";
this._renderingView.repaint();
if(!this._collapsed){this.set_height(this.get_height());
}$telerik.repaintChildren(this);
if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this._resizableWidget.hideHandles();
}this.updateClientState();
if(f){Telerik.Web.UI.DockCloseCommand.callBaseMethod(f,"onCommand");
}}},get_visible:function(){return !this.get_closed();
},set_visible:function(f){this.set_closed(!f);
},get_closed:function(){return this._closed;
},set_closed:function(k,j){if(!this._initialized){return;
}this._closed=k;
j=j?j:false;
var g=this.get_enableAnimation()?this.get_animationDuration():0;
if(!j||g==0){this._onCloseAnimationEnd();
return;
}var h=this.get_element();
var f=Function.createDelegate(this,this._onCloseAnimationEnd);
var i=this.get_titleElement();
if(i!=null){i.style.display="none";
}if(k){$telerik.stopTransition(h,false,true);
$telerik.transition(h,{opacity:0},g,"easeIn",f);
}else{$telerik.stopTransition(h,false,true);
$telerik.transition(h,{opacity:1},g,"easeIn",f);
}},get_collapsed:function(){return this._collapsed;
},set_collapsed:function(g,f){f=f?f:false;
if(this._resizable&&this._resizableWidget){if(g){this._resizableWidget.hideHandles();
}else{this._resizableWidget.showHandles();
}}this._collapsed=g;
this.updateClientState();
if(this._initialized&&this._renderingView){this._renderingView.collapse(g,f);
}},get_commands:function(){return this._commands;
},set_commands:function(f){this._commands=f;
this._originalCommandsObject=f;
},get_dockZoneID:function(){return this._dockZoneID;
},set_dockZoneID:function(f){this._dockZoneID=f;
},get_height:function(){return this._height;
},set_height:function(f){this._height=f;
this.updateClientState();
if(this._initialized){this._renderingView.set_height(f);
}},get_enableDrag:function(){return this._enableDrag;
},set_enableDrag:function(f){this._enableDrag=f;
this._initializeDrag();
},get_pinned:function(){return this._pinned;
},set_pinned:function(g){if(this.get_dockZoneID()){return;
}this._pinned=g;
var f=this.getCommand("PinUnpin");
if(f){f.set_state(g?2:1);
}if(this._renderingView&&this._initialized){this._renderingView.pin(g);
}},get_title:function(){return this._title;
},set_title:function(f){this._title=f;
if(this._renderingView){this._renderingView.set_title(f);
}},set_visibleTitlebar:function(g){if(g==null){g=true;
}var f=this._topBar;
if(g){this.get_titleBar().style.display="";
Sys.UI.DomElement.removeCssClass(f,"rdNone");
}else{Sys.UI.DomElement.addCssClass(f,"rdNone");
this.get_titleBar().style.display="none";
}},get_width:function(){return this._width;
},set_width:function(f){this._width=f;
this.updateClientState();
if(this._initialized&&this._renderingView){this._renderingView.set_width(f);
}},get_resizable:function(){return this._resizable;
},set_resizable:function(f){this._resizable=f;
this._initResizableWidget();
},get_renderMode:function(){return this._renderMode;
},set_renderMode:function(f){this._renderMode=f;
}};
$telerik.$.registerControlProperties(Telerik.Web.UI.RadDock,{allowedZones:[],animationDuration:300,autoPostBack:false,dockMode:Telerik.Web.UI.DockMode.Default,dockZone:null,enableAnimation:false,forbiddenZones:[],index:0,layoutID:null,skin:"Default",tag:"",uniqueID:null,uniqueName:null,shortcuts:[]});
$telerik.$.extend({registerControlEventsDock:function(f,g){$telerik.$.registerControlEvents(f,g);
$telerik.$.each(g,function(j,h){f.prototype["raise_"+h]=function(i){this.raiseEvent(h,i);
};
});
}});
$telerik.$.registerControlEventsDock(Telerik.Web.UI.RadDock,["command","dockPositionChanged","dockPositionChanging","drag","dragEnd","dragStart","enterZone","initialize","leaveZone","resizeEnd","resizeStart","load"]);
Telerik.Web.UI.RadDock.registerClass("Telerik.Web.UI.RadDock",Telerik.Web.UI.RadWebControl);
Telerik.Web.UI.RadDock.prototype.repaint=function(){this._renderingView.repaint();
if(this._resizableWidget){this._resizableWidget.repaint();
}};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs=function(f,g){b.Dock.ShortCutCancelEventArgs.initializeBase(this);
this._domEvent=f;
this._shortCut=g;
};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs.prototype={get_shortCut:function(){return this._shortCut;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs.registerClass("Telerik.Web.UI.Dock.ShortCutCancelEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.DockCommand=function(f){Telerik.Web.UI.DockCommand.initializeBase(this,[f]);
};
Telerik.Web.UI.DockCommand.prototype={add_command:function(f){this.get_events().addHandler("command",f);
},remove_command:function(f){this.get_events().removeHandler("command",f);
},raise_command:function(f){var g=this.get_events().getHandler("command");
if(g){g(this.get_radDock(),f);
}},onCommand:function(g){var f=new Sys.CancelEventArgs();
f.command=this;
f.event=g;
f.Command=this;
this.raise_command(f);
if(f.get_cancel()){return;
}this.get_radDock().raise_command(f);
if(f.get_cancel()){return;
}this.get_radDock().updateClientState();
this.conditionalPostback();
},onMouseDown:function(f){$telerik.cancelRawEvent(f);
},_preventDefault:function(f){if(f.preventDefault){f.preventDefault();
}f.returnValue=false;
},conditionalPostback:function(){if(this.get_autoPostBack()){this.get_radDock().doPostBack(this.get_name());
}},initialize:function(){Telerik.Web.UI.DockCommand.callBaseMethod(this,"initialize");
$addHandlers(this.get_element(),{click:this.onCommand,mousedown:this.onMouseDown},this);
},dispose:function(){$clearHandlers(this.get_element());
Telerik.Web.UI.DockCommand.callBaseMethod(this,"dispose");
}};
$telerik.$.registerControlProperties(Telerik.Web.UI.DockCommand,{autoPostBack:false,clientTypeName:null,cssClass:"rdCustom",name:"Custom",radDock:null,shortCut:"",text:"Custom"});
Telerik.Web.UI.DockCommand.registerClass("Telerik.Web.UI.DockCommand",Sys.UI.Control);
Telerik.Web.UI.DockToggleCommand=function(f){Telerik.Web.UI.DockToggleCommand.initializeBase(this,[f]);
this._state=1;
this._alternateCssClass="rdCustom";
this._alternateText="Custom";
this._initialSetState=false;
};
Telerik.Web.UI.DockToggleCommand.prototype={updateState:function(){var f=this.get_element();
var g=this.get_radDock()._renderMode==Telerik.Web.UI.RenderMode.Classic?f.getElementsByTagName("span")[0]:f;
if(this.get_state()==1){f.title=this.get_text();
Sys.UI.DomElement.addCssClass(g,this.get_cssClass());
Sys.UI.DomElement.removeCssClass(g,this.get_alternateCssClass());
}else{f.title=this.get_alternateText();
Sys.UI.DomElement.addCssClass(g,this.get_alternateCssClass());
Sys.UI.DomElement.removeCssClass(g,this.get_cssClass());
}},get_state:function(){return this._state;
},set_state:function(f){this._state=f;
if(this._initialSetState){this.updateState();
}},get_alternateCssClass:function(){return this._alternateCssClass;
},set_alternateCssClass:function(f){this._alternateCssClass=f;
},get_alternateText:function(){return this._alternateText;
},set_alternateText:function(f){this._alternateText=f;
},initialize:function(){Telerik.Web.UI.DockToggleCommand.callBaseMethod(this,"initialize");
this._initialSetState=true;
this.updateState();
},dispose:function(){b.DockToggleCommand.callBaseMethod(this,"dispose");
}};
b.DockToggleCommand.registerClass("Telerik.Web.UI.DockToggleCommand",Telerik.Web.UI.DockCommand);
b.DockCloseCommand=function(f){Telerik.Web.UI.DockCloseCommand.initializeBase(this,[f]);
this._cssClass="rdClose";
this._name="Close";
this._text="Close";
};
b.DockCloseCommand.prototype={onCommand:function(f){this.get_radDock().set_closed(true,true);
}};
b.DockCloseCommand.registerClass("Telerik.Web.UI.DockCloseCommand",Telerik.Web.UI.DockCommand);
b.DockExpandCollapseCommand=function(f){b.DockExpandCollapseCommand.initializeBase(this,[f]);
this._cssClass="rdCollapse";
this._alternateCssClass="rdExpand";
this._name="ExpandCollapse";
this._text="Collapse";
this._alternateText="Expand";
};
b.DockExpandCollapseCommand.prototype={onCommand:function(f){this.get_radDock().set_collapsed(!this.get_radDock().get_collapsed(),true);
}};
b.DockExpandCollapseCommand.registerClass("Telerik.Web.UI.DockExpandCollapseCommand",Telerik.Web.UI.DockToggleCommand);
b.DockPinUnpinCommand=function(f){Telerik.Web.UI.DockPinUnpinCommand.initializeBase(this,[f]);
this._cssClass="rdUnpin";
this._alternateCssClass="rdPin";
this._name="PinUnpin";
this._text="Pin";
this._alternateText="Unpin";
};
b.DockPinUnpinCommand.prototype={onCommand:function(f){if(this.get_radDock().get_dockZoneID()){return;
}this.get_radDock().set_pinned(!this.get_radDock().get_pinned());
Telerik.Web.UI.DockPinUnpinCommand.callBaseMethod(this,"onCommand");
}};
b.DockPinUnpinCommand.registerClass("Telerik.Web.UI.DockPinUnpinCommand",Telerik.Web.UI.DockToggleCommand);
})($telerik.$,Telerik.Web.UI);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.IView=function(c){};
b.Dock.IView.prototype={initialize:function(){},dispose:function(){},repaint:function(){},clone:function(){},get_width:function(){},set_width:function(c){},get_height:function(){},set_height:function(c){},get_title:function(){},set_title:function(c){},isPinned:function(){},pin:function(c){},isCollapsed:function(){},collapse:function(d,c){},isClosed:function(){},get_minWidth:function(){},get_minHeight:function(){},get_titleElement:function(){},get_titleBar:function(){},get_commandsContainer:function(){},get_contentContainer:function(){},getCommandsElements:function(){},fitWidth:function(){},unfitWidth:function(){}};
b.Dock.IView.registerInterface("Telerik.Web.UI.Dock.IView");
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.BaseView=function(c){this.control=c;
this.initialize();
};
b.Dock.BaseView.prototype={initialize:function(){this.initializeFormElement();
},isPinned:function(){return this.control._pinned;
},isCollapsed:function(){return this.control._collapsed;
},isClosed:function(){return this.control._closed;
},get_width:function(){return this.control.get_width();
},get_height:function(){return this.control.get_height();
},get_title:function(){return this.control._title;
},set_title:function(d){var c=this.get_titleElement();
if(c){c.innerHTML=d;
}},get_contentContainer:function(){if(!this._contentContainer){this._contentContainer=$get(this.control.get_id()+"_C");
}return this._contentContainer;
},get_titleBar:function(){if(!this._titleBar){this._titleBar=$get(this.control.get_id()+"_T");
}return this._titleBar;
},get_commandsContainer:function(){if(!this._commandsContainer){var c=this.get_titleBar();
if(c){this._commandsContainer=$telerik.getElementByClassName(c,"rdCommands","UL");
}else{this._commandsContainer=null;
}}return this._commandsContainer;
},initializeFormElement:function(){var c=this.control.get_element().parentNode;
while(c){if(c.tagName.toLowerCase()==="form"){this._form=this.control._form=c;
break;
}c=c.parentNode;
}}};
b.Dock.BaseView.registerClass("Telerik.Web.UI.Dock.BaseView");
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.ClassicView=function(c){b.Dock.ClassicView.initializeBase(this,[c]);
this.control=c;
};
b.Dock.ClassicView.prototype={initialize:function(){Telerik.Web.UI.Dock.ClassicView.callBaseMethod(this,"initialize");
this._initializeHtmlElementVariables();
this._setUnselectableOn();
this.control._setHandle(this._titleBar||this._grip);
if(this.get_height()){this._setContentContainerHeight(this._height);
}this._middleMiddleCell.style.height="auto";
if(this.get_height()!=null){this._setHeightHtmlEl(this.get_height());
}this._fixEmWidth();
},repaint:function(){if(this.isClosed()||$telerik.getInvisibleParent(this.control.get_element())!=null){return;
}this._fixEmWidth();
this._setContentContainerHeight();
},clone:function(f){var e=this.control.get_element();
var g=e.cloneNode(true);
g.removeAttribute("control");
var h=$telerik.getElementByClassName(g,"rdTable","TABLE").rows;
var i=$telerik.getElementByClassName(h[0].cells[1],"rdTitleBar","DIV");
var d=$telerik.getElementByClassName(h[1].cells[1],"rdContent","DIV");
var c=g.getElementsByTagName("input")[0];
if(i){i.setAttribute("id",f+"_T");
}d.setAttribute("id",f+"_C");
g.setAttribute("id",f);
c.setAttribute("id",f+"_ClientState");
c.setAttribute("name",f+"_ClientState");
e.parentNode.insertBefore(g,e.nextSibling);
return g;
},get_minWidth:function(){var d=0;
for(var c=0;
c<this.getCommandsElements().length;
c++){d+=this.getCommandsElements()[c].clientWidth;
}if(this._topLeftBar){d+=this._topLeftBar.clientWidth;
}if(this._topRightBar){d+=this._topLeftBar.clientWidth;
}return d;
},get_minHeight:function(){var c=0;
if(this._topBar){c+=this._topBar.clientHeight||this._topBar.offsetHeight;
}if(this._bottomBar){c+=this._bottomBar.clientHeight||this._bottomBar.offsetHeight;
}return c;
},getCommandsElements:function(){return this.get_commandsContainer()?this.get_commandsContainer().getElementsByTagName("a"):[];
},get_titleElement:function(){var c=this.get_titleBar();
return c?c.getElementsByTagName("em")[0]:null;
},set_width:function(c){this._setWidthHtmlEl(c);
this._fixEmWidth();
},set_height:function(c){if(this._tableElement){this._tableElement.style.height="auto";
}this._setHeight(c);
},pin:function(f){if($telerik.isIE6){if(f){this.control.set_enableDrag(false);
}else{this.control.set_enableDrag(true);
}return;
}var c=this.control.get_element();
c.style.position="absolute";
var e=$telerik.getScrollOffset(c,true);
var d=this.control._getLocation(c);
if(f){d=this.control.subtractPoints(d,e);
this.control._setLocation(d);
c.style.position="fixed";
this.control.set_enableDrag(false);
}else{d=this.control.addPoints(d,e);
this.control._setLocation(d);
this.control.set_enableDrag(true);
}},collapse:function(p,m){var n=this,g=this.control,i=g.get_element(),j=this._tableElement,h=this.get_contentContainer(),f=h.style.overflow;
$telerik.stopTransition(h,false,true);
var d=g.get_enableAnimation()?g.get_animationDuration():0;
if(!m){d=0;
}var c={};
var k=g.getCommand("ExpandCollapse");
i.style.height="auto";
if(g._resizable){j.style.height="auto";
}h.style.overflow="hidden";
if(p){g._expandedHeight=g._height?parseInt(g._height,10):parseInt(g._getBounds().height,10);
if(!h.style.height){n._forceContentContainerHeight(g._expandedHeight);
}c.height="0px";
$telerik.transition(h,c,d,"easeIn",function(){n._setContentContainerHeight();
g.addCssClass("rdCollapsed");
if(k){k.set_state(2);
Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(k,"onCommand");
}if(g._resizable){if(g.get_dockZoneID()){$find(g.get_dockZoneID())._resetDocksResizeHandles();
}else{g._resizableWidget.repaint();
}}h.style.overflow=f;
});
}else{if(g._collapsed&&!p&&!g._expandedHeight){if(g._height){g._expandedHeight=parseInt(g._height,10);
}else{h.style.height="auto";
g.removeCssClass("rdCollapsed");
g._expandedHeight=parseInt(g._getBounds().height,10);
g.addCssClass("rdCollapsed");
}}g.removeCssClass("rdCollapsed");
var o=this._getBounds(this._topBar).height,e=this._getBounds(this._bottomMiddleBar).height,l=parseInt(g._expandedHeight,10)-o-e;
c.height=l+"px";
h.style.height="0px";
$telerik.transition(h,c,d,"easeIn",function(){h.style.display="";
j.style.height="";
if(g.get_height()!=null){n._setHeightHtmlEl(g._expandedHeight);
}if(g._resizable){if(g.get_dockZoneID()){$find(g.get_dockZoneID())._resetDocksResizeHandles();
}else{g._resizableWidget.repaint();
}}if(g.get_height()==null){i.style.height="";
}g._renderingView._setContentContainerHeight();
if(k){k.set_state(1);
}$telerik.repaintChildren(g);
if(g._resizable){g.set_height($telerik.getBounds(i).height+"px");
}if(k){Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(k,"onCommand");
}h.style.overflow=f;
});
}if(!m&&g._resizable){g._resizableWidget.repaint();
}},fitWidth:function(){this.control.get_element().style.width="100%";
this.get_contentContainer().style.width="100%";
this._fixEmWidth();
},unfitWidth:function(){this.set_width(this.get_width());
},dispose:function(){this._disposeHtmlVariables();
},_initializeHtmlElementVariables:function(){this._grip=$get(this.control.get_id()+"_G");
this._titleBar=$get(this.control.get_id()+"_T");
this.get_commandsContainer();
var c=this.control.get_element();
this._tableElement=c.getElementsByTagName("table")[0];
var d=this._tableElement.rows;
this._topBar=d[0];
this._topLeftBar=d[0].cells[0];
this._topRightBar=d[0].cells[2];
this._middleLeftBar=d[1].cells[0];
this._middleMiddleCell=d[1].cells[1];
this._middleRightBar=d[1].cells[2];
this._bottomBar=d[2];
this._bottomLeftBar=d[2].cells[0];
this._bottomMiddleBar=d[2].cells[1];
this._bottomRightBar=d[2].cells[2];
},_disposeHtmlVariables:function(){this._grip=this._titleBar=this._commandsContainer=this._tableElement=this._topBar=this._topLeftBar=this._topRightBar=this._middleLeftBar=this._middleMiddleCell=this._middleRightBar=this._bottomBar=this._bottomLeftBar=this._bottomMiddleBar=this._bottomRightBar=this._form=null;
},_setUnselectableOn:function(){this._topLeftBar.setAttribute("unselectable","on");
this._topRightBar.setAttribute("unselectable","on");
this._middleLeftBar.setAttribute("unselectable","on");
this._middleRightBar.setAttribute("unselectable","on");
this._bottomLeftBar.setAttribute("unselectable","on");
this._bottomMiddleBar.setAttribute("unselectable","on");
this._bottomRightBar.setAttribute("unselectable","on");
},_setHeight:function(c){this._setContentContainerHeight(c);
this._setHeightHtmlEl(c);
},_setContentContainerHeight:function(d){var e=this,c=this.get_contentContainer();
if(!c){return;
}if(e.get_height()!=null||e._resizable){e._forceContentContainerHeight(d);
}else{c.style.height="";
}},_forceContentContainerHeight:function(g){var j=this,f=j.get_contentContainer(),c=j._getBounds();
var h=g!=null?parseInt(g,10):c.height,e=j._getBounds(j._topBar),d=j._getBounds(j._bottomBar),i=h-e.height-d.height;
f.style.height=(i<0?0:i)+"px";
},_setHeightHtmlEl:function(d,c){if(!c){c=this.control.get_element();
}if(!d){c.style.height="";
return;
}if(d.toString().indexOf("%")>-1){c.style.height=parseInt(d,10)+"%";
}else{c.style.height=parseInt(d,10)+"px";
}},_setWidthHtmlEl:function(d,c){if(!d){return;
}if(!c){c=this.control.get_element();
}if(d.toString().indexOf("%")>-1){c.style.width=parseInt(d,10)+"%";
}else{c.style.width=parseInt(d,10)+"px";
}},_fixEmWidth:function(){var f=this.get_titleBar();
if(f==null){return;
}var e=this.control.get_element();
var h=this.get_titleElement();
if(!h){return;
}var c=this.get_commandsContainer();
var d=c?$telerik.getOuterBounds(c).width:0;
h.style.display="block";
h.style.width="";
if(h.offsetWidth+30+d<e.offsetWidth){return;
}var g=$telerik.getBounds(f).width;
if(g>0){if($telerik.isIE6){h.style.display="none";
g=$telerik.getBounds(f).width;
h.style.display="block";
}var j=g-d-30;
var i=j>0?j:0;
h.style.width=i+"px";
}},_getBounds:function(c){if(!c){c=this.control.get_element();
}return $telerik.getBounds(c);
}};
b.Dock.ClassicView.registerClass("Telerik.Web.UI.Dock.ClassicView",Telerik.Web.UI.Dock.BaseView,Telerik.Web.UI.Dock.IView);
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.LightweightView=function(c){b.Dock.LightweightView.initializeBase(this,[c]);
this.control=c;
};
b.Dock.LightweightView.prototype={initialize:function(){var d=this;
var c=d.control;
b.Dock.LightweightView.callBaseMethod(d,"initialize");
c._setHandle(d._getHandle());
if(c.get_collapsed()){d._setCollapsedDockHeight();
}else{if(c.get_height()){d.set_height(c.get_height());
}}},dispose:function(){},repaint:function(){},clone:function(d){var e=this.control._element;
var c=e.cloneNode(true);
this._fixCloneIds(c,d);
e.parentNode.insertBefore(c,e.nextSibling);
return c;
},get_minWidth:function(){var c=0;
if(this.get_commandsContainer()){c+=this.get_commandsContainer().clientWidth;
}if(this._getTitleWrapper()){c+=parseInt($telerik.getComputedStyle(this._getTitleWrapper(),"padding-left",0),10);
c+=parseInt($telerik.getComputedStyle(this._getTitleWrapper(),"padding-right",0),10);
}return c;
},get_minHeight:function(){return this._getTitleWrapperHeight();
},set_width:function(d){var c=d.indexOf&&d.indexOf("%")>-1?"%":"px";
this.control.get_element().style.width=parseInt(d,10)+c;
if(this.get_titleElement()){this._sizeTitleElement();
}},set_height:function(c){if(c){this.control.get_element().style.height=parseInt(c,10)+"px";
this._setContentWrapperHeight(c);
}},pin:function(d){var c=d?"fixed":"absolute";
this.control.set_enableDrag(!d);
this.control.get_element().style.position=c;
},collapse:function(i,g){var c=this.control.getCommand("ExpandCollapse");
var h=this,f={},d=this.control,e=this.control.get_enableAnimation()?this.control.get_animationDuration():0;
if(i){this.control._element.style.overflow="hidden";
f.height=this._getTitleWrapperHeight();
d._expandedHeight=this._calcExpandedHeight();
if(!h.get_height()){h.set_height(d._expandedHeight);
}}else{this.control._element.style.overflow="";
d.removeCssClass("rdCollapsed");
this.set_height(this._getTitleWrapperHeight());
if(!d._expandedHeight){d._expandedHeight=this._calcExpandedHeight();
}f.height=parseInt(d._expandedHeight,10);
}$telerik.stopTransition(this.control._element,false,true);
$telerik.transition(this.control._element,f,e,"easeIn",function(){if(i){h.set_height(h._getTitleWrapperHeight());
d.addCssClass("rdCollapsed");
}else{h.set_height(d._expandedHeight);
}if(d._resizable&&d._resizableWidget){if(d.get_dockZoneID()){$find(d.get_dockZoneID())._resetDocksResizeHandles();
}else{d._resizableWidget.repaint();
}}if(c){c.set_state(i?2:1);
Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(c,"onCommand");
}});
},close:function(d,c){},get_titleElement:function(){return this.get_titleBar()?this.get_titleBar().getElementsByTagName("h6")[0]:null;
},getCommandsElements:function(){return a(".rdCommandButton",this.get_commandsContainer()).toArray();
},fitWidth:function(){this.originalWidth=this.get_width();
this.control.get_element().style.width="100%";
if(this.get_titleElement()){this._sizeTitleElement();
}},unfitWidth:function(){var c=this.originalWidth||this.get_width();
this.set_width(c);
this.originalWidth=null;
},_getHandle:function(){return $get(this.control.get_id()+"_T")||$get(this.control.get_id()+"_G");
},_sizeTitleElement:function(){var f=this.get_titleElement(),e=this.get_titleBar(),c=this.get_commandsContainer(),d=c?parseInt(c.clientWidth,10):0;
f.style.width=Math.max(0,parseInt(e.clientWidth,10)-d)+"px";
f.style.display="";
},_setContentWrapperHeight:function(d){var e=this;
var c=this.get_contentContainer().parentNode;
if(e.control.get_height()){c.style.overflow="auto";
}c.style.height=parseInt(d,10)-this._getTitleWrapperHeight()+"px";
},_getBounds:function(c){if(!c){c=this.control.get_element();
}return $telerik.getBounds(c);
},_getTitleWrapperHeight:function(){var c=a(this.control._element).find(".rdTitleWrapper");
var d=$telerik.isIE6||$telerik.isIE7?c.get(0).clientHeight:c.get(0).offsetHeight;
return parseInt(d,10);
},_fixCloneIds:function(c,d){a(c).attr("id",d);
a(".rdTitleBar",c).attr("id",d+"_T");
a(".rdContent",c).attr("id",d+"_C");
a("input[id$='ClientState']").attr("id",d+"_ClientState");
},_getTitleWrapper:function(){return a(".rdTitleWrapper",this.control._element).get(0);
},_calcExpandedHeight:function(){var c=this.control;
return c._expandedHeight&&!isNaN(parseInt(c._expandedHeight,10))?parseInt(c._expandedHeight,10):c._height?parseInt(c._height,10):parseInt(c._element.clientHeight,10);
},_setCollapsedDockHeight:function(){var d=this;
var c=d.control;
c._expandedHeight=d._calcExpandedHeight();
d.set_height(d._getTitleWrapperHeight());
a(c.get_element()).css("overflow","");
}};
b.Dock.LightweightView.registerClass("Telerik.Web.UI.Dock.LightweightView",Telerik.Web.UI.Dock.BaseView,Telerik.Web.UI.Dock.IView);
})(Telerik.Web.UI,$telerik.$);
