Type.registerNamespace("Telerik.Web.UI");
(function(a,g){var b=Telerik.Web.UI,e="",f="itemDataBound",d="dataBound";
$telerik.toTagCloud=function(h){return h;
};
$telerik.findTagCloud=$find;
a.registerEnum(b,"TagCloudDistribution",{Linear:0,Logarithmic:1});
a.registerEnum(b,"TagCloudSorting",{NotSorted:0,AlphabeticAsc:1,AlphabeticDsc:2,WeightedAsc:3,WeightedDsc:4});
b.RadTagCloud=function(h){var i=this;
b.RadTagCloud.initializeBase(i,[h]);
i._clickDelegate=null;
i._postBackReference=null;
i._webServiceSettings=new b.WebServiceSettings({});
i._items=[];
i._enabled=true;
i._target="";
i._accessKey="";
i._tabIndex=0;
i._focusedItemIndex=null;
i._itemsElement=null;
i._clientDataSourceID=e;
i._clientDataSource=null;
i._dataSource=null;
i._dataNavigateUrlField=e;
i._dataTextField=e;
i._dataToolTipField=e;
i._dataValueField=e;
i._dataWeightField=e;
i._clientDataSourceChangeDelegate=Function.createDelegate(i,i._clientDataSourceChangeHandler);
};
b.RadTagCloud.prototype={initialize:function(){var h=this;
b.RadTagCloud.callBaseMethod(h,"initialize");
if(this._isRightToLeft()){Sys.UI.DomElement.addCssClass(h.get_element(),"rtcRtl");
}h._itemsElement=$telerik.getElementByClassName(h.get_element(),"rtcTagList");
h._createChildItems();
h._createClientDataBoundItems();
h._attachEvents(true);
h._enableKeyboardNavigation();
h._setItemsRowIndex();
h.raiseEvent("load",Sys.EventArgs.Empty);
},dispose:function(){this._attachEvents(false);
this._detachKeyboardNavHandlers(this.get_element());
b.RadTagCloud.callBaseMethod(this,"dispose");
},_createChildItems:function(){var k=this.get_containerElement();
if(k!=null){var j=$telerik.getChildrenByTagName(k,"li"),n=j.length;
for(var l=0;
l<n;
l++){var o=j[l];
var h=$telerik.getChildrenByTagName(o,"a")[0];
var m=o.getAttribute("id");
o.removeAttribute("id");
var p=$create(b.RadTagCloudItem,{navigateUrl:h.getAttribute("href")},null,null,o);
if(m!=null){p.set_weight(parseFloat(m.substring(m.lastIndexOf("_")+1))||0);
}if(!this.get_enabled()){h.removeAttribute("href");
}p._setTarget(this.get_target());
j[l]._item=p;
this.get_items()[l]=p;
}this.requestItems();
}},_createClientDataBoundItems:function(){var j=this,i=j.get_clientDataSourceID(),h=$find(i);
if(i&&(h===null)){Sys.Application.add_load(function(){j.dataBind();
});
}else{j.dataBind();
}},dataBind:function(){var i=this,h=i.get_clientDataSource();
if(h){i._dataBindToClientDataSource(h);
}else{i._dataBind();
}},_dataBindToClientDataSource:function(h){var i=this;
if(h&&(h instanceof b.RadClientDataSource)){i._clientDataSource=h;
h.remove_change(i._clientDataSourceChangeDelegate);
h.add_change(i._clientDataSourceChangeDelegate);
h.fetch();
}},_clientDataSourceChangeHandler:function(){var j=this,h=j.get_clientDataSource();
if(h){var i=h.view();
j.set_dataSource(i);
j._dataBind();
}},_dataBind:function(){var j=this,h=j.get_dataSource(),i=!j.get_appendClientDataBoundItems();
if(h&&a.isArray(h)){if(i){j._clearItems();
}j._createDataBoundItems(h);
j._raiseDataBound();
}},_createDataBoundItems:function(h){var p=this,k=h.length,n=p._dataNavigateUrlField,q=p._dataTextField,r=p._dataToolTipField,s=p._dataValueField,t=p._dataWeightField,j=null,m=null,o=null;
for(var l=0;
l<k;
l++){j=h[l];
m={NavigateUrl:j[n],Text:j[q],ToolTip:j[r],Value:j[s],Weight:j[t]};
o=p.addTagCloudItem(m);
p._raiseItemDataBound(o,j);
}},_raiseItemDataBound:function(k,h){var j=this,i=new b.TagCloudItemDataBoundEventArgs(k,h);
j.raiseEvent(f,i);
},_raiseDataBound:function(){var h=this;
h.raiseEvent(d,Sys.EventArgs);
},_dataBindToCustomDataSource:function(){},get_clientDataSourceID:function(){return this._clientDataSourceID;
},set_clientDataSourceID:function(h){this._clientDataSourceID=h;
},get_clientDataSource:function(){var j=this,i=j.get_clientDataSourceID(),h=$find(i);
if(h&&(h instanceof b.RadClientDataSource)){return h;
}else{return j._clientDataSource;
}},set_dataSource:function(h){var i=this;
i._dataSource=h;
},get_dataSource:function(){var h=this;
return h._dataSource;
},_enableItems:function(o){var j=this.get_containerElement();
if(j!=null){var h=$telerik.getChildrenByTagName(j,"li");
var l=h.length;
for(var k=0;
k<l;
k++){var m=h[k];
var n=m._item;
if(o){n.set_navigateUrl(n.get_navigateUrl());
Sys.UI.DomElement.removeCssClass(this.get_element(),"rtcDisabled");
}else{Sys.UI.DomElement.addCssClass(this.get_element(),"rtcDisabled");
n.get_anchorElement().removeAttribute("href");
}}}},_setTargetToItems:function(){var k=this.get_items();
var h=k.length;
var m=this.get_target();
for(var j=0;
j<h;
j++){var l=k[j];
l._setTarget(m);
}},_attachEvents:function(i){var h=this.get_containerElement();
if(null==h){return;
}if(i!=false){this._clickDelegate=Function.createDelegate(this,this._mouseClickHandler);
$addHandler(h,"click",this._clickDelegate);
}else{$removeHandler(h,"click",this._clickDelegate);
this._clickDelegate=null;
}},_mouseClickHandler:function(h){if(!this.get_enabled()){$telerik.cancelRawEvent(h.rawEvent);
return false;
}var k=h.target;
if($telerik.isIE6){$telerik.cancelRawEvent(h.rawEvent);
}var j=this._getItemFromEvent(k);
if(null!=j){var i=new b.TagCloudCancelEventArgs(j);
this.raiseEvent("itemClicking",i);
if(i.get_cancel&&i.get_cancel()){$telerik.cancelRawEvent(h.rawEvent);
return false;
}this.raiseEvent("itemClicked",new b.TagCloudEventArgs(j));
this._postback(j.get_index());
}},_postback:function(h){if(!this._postBackReference){return;
}var i=this._postBackReference.replace("arguments",h);
eval(i);
},_getItemFromEvent:function(i){var k=i.tagName.toLowerCase();
if(k!="a"&&i.parentNode.className.indexOf("rtcTagItem")!=-1||i.className.indexOf("rtcTagItem")!=-1||k=="ul"){return null;
}var h=this.get_containerElement();
var j=null;
while(null!=i&&i!=h&&i!=document){if(i.tagName.toLowerCase()=="li"&&null!=i._item&&Object.getTypeName(i._item)=="Telerik.Web.UI.RadTagCloudItem"){j=i._item;
}i=i.parentNode;
}return j;
},_isRightToLeft:function(){var h=null;
if(h==null){var i=this.get_element();
if(i){h=$telerik.isRightToLeft(i);
}}return h;
},_enableKeyboardNavigation:function(){var h=this.get_element();
$telerik.$(h).attr({tabIndex:this._tabIndex,accessKey:this._accessKey});
this._attachKeyboardNavHandlers(h);
},_attachKeyboardNavHandlers:function(h){$telerik.$(h).on("click",$telerik.$.proxy(this._clickHandler,this)).on("keydown",$telerik.$.proxy(this._keyDownHandler,this)).on("focus",$telerik.$.proxy(this._focusHandler,this));
a(".rtcTagItem > a").on("focus",$telerik.$.proxy(this._focusItemHandler,this));
},_detachKeyboardNavHandlers:function(h){$telerik.$(h).off("click",this._clickHandler).off("keydown",this._keyDownHandler).off("focus",this._focusHandler);
$telerik.$(".rtcTagItem > a").off("focus",this._focusItemHandler);
},_keyDownHandler:function(h){switch(h.keyCode){case 37:this._focusNewItem(this._getPrevItem());
break;
case 38:this._focusNewItem(this._getAboveItem());
break;
case 39:this._focusNewItem(this._getNextItem());
break;
case 40:this._focusNewItem(this._getBelowItem());
break;
}if(h.keyCode>36&&h.keyCode<41){$telerik.cancelRawEvent(h.originalEvent);
}},_clickHandler:function(h){if($telerik.isChrome){var i=$telerik.$(h.target).parents(".rtcTagItem").get(0);
if(i){this._focusedItemIndex=this._getItemByDomEl(i).get_index();
}}this._focusHandler(h);
},_focusHandler:function(h){this._focusedItemIndex=this._focusedItemIndex||0;
this.get_items()[this._focusedItemIndex].get_anchorElement().focus();
},_focusItemHandler:function(h){var i=this._getItemFromEvent(h.target);
this._focusedItemIndex=i.get_index();
},_focusNewItem:function(h){if(h&&this._focusedItemIndex!=null){h.get_anchorElement().focus();
}},_getNextItem:function(){return this._focusedItemIndex==this._items.length-1?this._items[0]:this._items[this._focusedItemIndex+1];
},_getPrevItem:function(){return this._focusedItemIndex==0?this._items[this._items.length-1]:this._items[this._focusedItemIndex-1];
},_getBelowItem:function(){return this._getAllegedItem("below");
},_getAboveItem:function(){return this._getAllegedItem("above");
},_getItemsMinimalHeight:function(){var j=this._items;
var k=1;
for(var h=0;
h<j.length;
h++){if(j[h].get_weight()==this.get_minimalWeight()){k=$telerik.getOuterBounds(j[h].get_element()).height;
break;
}}return k;
},_getLastItemFromRow:function(i){var h=this.get_itemsByRow(i);
return h[h.length-1];
},_getAllegedItem:function(n){var j=null;
var l=this._items[this._focusedItemIndex];
var p=$telerik.getOuterBounds(l.get_element());
var m=l.get_rowIndex();
var t=p.y;
var s=this._getItemsMinimalHeight()/2;
var q=t;
var r=p.x+p.width/2;
var o=-1;
if(n=="below"){o=1;
q+=p.height;
}var i=this._getRowHeight(m+o);
var h=t+(o*i);
var k=q+i;
while(j==null){q=q+o*s;
if(q>=k||q<=h){j=this._getLastItemFromRow(m+o);
break;
}j=this._getItemByLoc({x:r,y:q});
}if(j==null&&((m==this._getNumberOfRows()-1)||m==1)){j=this._getLastItemFromRow(m+o);
}return j;
},_getItemByDomEl:function(h){if(h&&h.control&&Telerik.Web.UI.RadTagCloudItem.isInstanceOfType(h.control)){return h.control;
}return null;
},_getItemByLoc:function(m){var k=null;
var l=this._items;
for(var j=0;
j<l.length;
j++){var h=l[j].get_element();
if($telerik.containsPoint($telerik.getOuterBounds(h),m.x,m.y)){k=h;
break;
}}return k?this._getItemByDomEl(k):null;
},_setItemsRowIndex:function(){var l=parseInt(this.get_width(),10);
var h=1;
var j=0;
for(var k=0;
k<this._items.length;
k++){j+=$telerik.getOuterBounds(this._items[k].get_element()).width;
if(j>l){j=$telerik.getOuterBounds(this._items[k].get_element()).width;
h++;
}this._items[k]._rowIndex=h;
}},_getNumberOfRows:function(){return this._items[this._items.length-1].get_rowIndex();
},_getRowHeight:function(k){var j=0;
var l=this.get_itemsByRow(k);
for(var h=0;
h<l.length;
h++){j=Math.max(j,$telerik.getOuterBounds(l[h].get_element()).height);
}return j;
},get_itemsByRow:function(k){var j=[];
for(var h=0;
h<this._items.length;
h++){if(this._items[h].get_rowIndex()==k){j.push(this._items[h]);
}}return j;
},get_containerElement:function(){if(!this._itemsElement){var h=this.get_element();
a(h).append('<ul class="rtcTagList"></ul>');
this._itemsElement=a("ul",h)[0];
}return this._itemsElement;
},get_items:function(){return this._items;
},get_enabled:function(){return this._enabled;
},set_enabled:function(h){if(this.get_isInitialized()&&this._enabled!=h){this._enableItems(h);
}this._enabled=h;
},get_target:function(){return this._target;
},set_target:function(i){var h=this._target!=i;
this._target=i;
if(this.get_isInitialized()&&h){this._setTargetToItems();
}this.updateClientState();
},get_height:function(){return this.get_element().style.height;
},set_height:function(h){if(typeof(h)=="number"){this.get_element().style.height=h+"px";
}else{this.get_element().style.height=h;
}},get_width:function(){return this.get_element().style.width;
},set_width:function(h){if(typeof(h)=="number"){this.get_element().style.width=h+"px";
}else{this.get_element().style.width=h;
}this._setItemsRowIndex();
},addTagCloudItem:function(o,k){if(k<0){return;
}var i=this.get_containerElement();
var m=i.ownerDocument.createElement("li");
Sys.UI.DomElement.addCssClass(m,"rtcTagItem");
var h={accessKey:o.AccessKey,navigateUrl:o.NavigateUrl,tabIndex:o.TabIndex,text:o.Text,toolTip:o.ToolTip,value:o.Value,weight:o.Weight};
var p=$create(b.RadTagCloudItem,h,null,null,m);
if(this.get_renderItemWeight()){this._renderItemWeightElement(p);
}this._calculateMinMaxWeight(p);
if(k>=i.children.length||k==null){var l=i.lastChild;
if(l&&l.nodeType==3){i.insertBefore(m,l);
}else{i.appendChild(m);
}Array.add(this.get_items(),p);
}else{var j=i.firstChild;
var n=(j&&j.nodeType==3)?i.childNodes[k+1]:i.childNodes[k];
i.insertBefore(m,n);
Array.insert(this.get_items(),k,p);
}var q=o&&parseFloat(o.weight)||0;
if(this.get_items().length>1&&(q>this.get_maximalWeight()||q<this.get_minimalWeight())){this.repaint();
}else{this._setItemWidth(p);
this._setItemColor(p);
}m._item=p;
return p;
},_calculateMinMaxWeight:function(i){if(i){var h=i.get_weight();
if(this.get_items().length==0){this.set_minimalWeight(h);
this.set_maximalWeight(h);
}else{if(h>this.get_maximalWeight()){this.set_maximalWeight(h);
}if(h<this.get_minimalWeight()){this.set_minimalWeight(h);
}}}},_setItemWidth:function(j){if(j&&j.get_element){var k=this,h=a(j.get_element()).find("a,span"),i=k.get_minFontSize();
if(k._isUnitEm(i)){h.css({"font-size":this._calculateFontSize(j)+"em"});
}else{h.css({"font-size":this._calculateFontSize(j)+"px"});
}}},_isUnitEm:function(h){if(h.match(/em$/)!==null){return true;
}else{return false;
}},_setItemColor:function(h){if(h&&h.get_element){a("a",h.get_element()).css({color:this._calculateColor(h)});
}},_calculateFontSize:function(l){var m=this,h=this.get_coefficient(l),j=parseFloat(this.get_maxFontSize()),k=parseFloat(this.get_minFontSize()),i=k+((j-k)*h);
if(m._isUnitEm(m.get_minFontSize())){return i;
}else{return Math.round(i)||1;
}},get_coefficient:function(h){return(this.get_distribution()==b.TagCloudDistribution.Linear)?this.get_linearCoefficient(h):this.get_logarithmicCoefficient(h);
},get_linearCoefficient:function(n){var h=0,k=parseFloat(n.get_weight())||0,m=parseFloat(this.get_minimalWeight())||0,l=parseFloat(this.get_maximalWeight())||0,i=k-m,j=l-m;
if(j!=0){h=i/j;
}return h;
},get_logarithmicCoefficient:function(q){var p=parseFloat(this.get_minimalWeight())||0,o=parseFloat(this.get_maximalWeight())||0,k=parseFloat(q.get_weight())||0,n=(p<=0||Math.log(p)<0)?0:Math.log(p),m=(o<=0||Math.log(o)<0)?0:Math.log(o),l=(k<=0||Math.log(k)<0)?0:Math.log(k),h=0,i=l-n,j=m-n;
if(j!=0){h=i/j;
}return h;
},_calculateColor:function(q){var p="",m=this.get_minColor(),k=this.get_maxColor();
if(m&&k){var n=this._hexToRgb(m),l=this._hexToRgb(k),i=parseFloat(this.get_coefficient(q))||0;
if(i>1){i=1;
}if(i<0){i=0;
}var o=Math.round(n.r+(l.r-n.r)*i);
var j=Math.round(n.g+(l.g-n.g)*i);
var h=Math.round(n.b+(l.b-n.b)*i);
p=this._rgbValuesToHex(o,j,h);
}else{p=this.get_foreColor();
}return p;
},_rgbValuesToHex:function(l,j,h){var k="#";
var i=function(n){var m=parseInt(n,10).toString(16);
k=k+(m.length==1?"0"+m:m);
};
i(l);
i(j);
i(h);
i=null;
return k;
},_hexToRgb:function(h){if(!h){return null;
}var j={r:0,g:0,b:0};
if(h.indexOf("#")!=-1){h=h.substring(1,h.length);
}if(h.length==3){var i=function(k){return(k+k);
};
h=h.replace(/([0-9a-f])/gi,i);
}j.r=parseInt(h.substring(0,2),16);
j.g=parseInt(h.substring(2,4),16);
j.b=parseInt(h.substring(4,6),16);
return j;
},_resetMinimalMaximalWeight:function(){var j=this.get_items(),n=j[0]&&parseFloat(j[0].get_weight())||0,m=n;
for(var h=1,k=j.length;
h<k;
h++){var o=j[h].get_weight();
if(o<n){n=o;
}if(o>m){m=o;
}}if(this.get_minimalWeight()<n){this.set_minimalWeight(n);
}if(this.get_maximalWeight()>m){this.set_maximalWeight(m);
}},removeTagCloudItem:function(m,k){if(m&&m.get_element){var l=this,j=l.get_items(),h=m.get_element(),i=m.get_index();
m.dispose();
h._item=null;
h.parentNode.removeChild(h);
j.splice(i,1);
l._resetMinimalMaximalWeight();
if(k!==false){l.repaint();
}}},_clearItems:function(){var m=this,k=m.get_items(),l=k.length,n=null,j=null;
for(var h=l-1;
h>=0;
h--){n=k.pop();
j=n.get_element();
j._item=null;
j.parentNode.removeChild(j);
n.dispose();
}},_renderItemWeightElement:function(i){if(i&&i.get_element){var h=i.get_element();
if(a("span",h).length==0){a(h).append("<span>("+(i.get_weight()||this.get_minimalWeightAllowed()||"0")+")</span>");
}}},repaint:function(){b.RadTagCloud.callBaseMethod(this,"repaint");
var k=this.get_items(),l=k.length;
for(var h=0;
h<l;
h++){var j=k[h];
this._setItemWidth(j);
this._setItemColor(j);
}this._setItemsRowIndex();
},requestItems:function(h){var i=this.get_webServiceSettings();
if(i.get_path()){this._loadChildrenFromWebService(h);
}else{return false;
}},_loadChildrenFromWebService:function(i){if(!this._webServiceLoader){this._initializeWebServiceLoader();
}var h=new Sys.CancelEventArgs();
h._context=i||null;
h.get_context=function(){return this._context;
};
h.set_context=function(k){this._context=k;
};
this.raiseEvent("itemsRequesting",h);
if(h.get_cancel()){return;
}var j={context:h.get_context()};
if(this.get_webServiceSettings().get_isWcf()){j.context=this._webServiceLoader._serializeDictionaryAsKeyValuePairs(j.context);
}this._webServiceLoader.loadData(j);
},_initializeWebServiceLoader:function(){this._webServiceLoader=new b.WebServiceLoader(this.get_webServiceSettings());
this._webServiceLoader.add_loadingStarted(Function.createDelegate(this,this._onItemLoadingStarted));
this._webServiceLoader.add_loadingSuccess(Function.createDelegate(this,this._onItemLoadingSuccess));
this._webServiceLoader.add_loadingError(Function.createDelegate(this,this._onItemLoadingError));
},get_webServiceSettings:function(){return this._webServiceSettings;
},set_webServiceSettings:function(i){var h=Sys.Serialization.JavaScriptSerializer.deserialize(i);
this._webServiceSettings=new b.WebServiceSettings(h);
},_onItemLoadingStarted:function(i,h){this._showLoadingSign(true);
},_showLoadingSign:function(i){var h=this.get_element();
if(i===true){a(this._itemsElement).css({height:this.get_containerElement().clientHeight||"",visibility:"hidden"});
Sys.UI.DomElement.addCssClass(h,"rtcLoading");
}else{a(this._itemsElement).css({height:"",visibility:""});
Sys.UI.DomElement.removeCssClass(h,"rtcLoading");
}},_onItemLoadingSuccess:function(n,h){var m=h.get_data(),k=this.get_items(),l=k.length,j;
if(l>0){for(j=l-1;
j>=0;
j--){this.removeTagCloudItem(k[j],false);
}this.repaint();
}if(m&&m.length>0){for(j=0;
j<m.length;
j++){this.addTagCloudItem(m[j]);
}this.raiseEvent("itemsRequested",Sys.EventArgs.Empty);
}this._showLoadingSign(false);
},_onItemLoadingError:function(k,j){var i=j.get_message();
if(!i){i="No error data available";
}var h=new Telerik.Web.UI.TagCloudErrorEventArgs(i);
this.raiseEvent("itemsRequestFailed",h);
if(!h.get_cancelErrorAlert()){alert("RadTagCloud items request failed :\n Exception="+i);
}this._showLoadingSign(false);
},saveClientState:function(){var l=["target"];
var m={};
var j=l.length;
for(var h=0;
h<j;
h++){var k=l[h];
m[k]=this["get_"+k]();
}return Sys.Serialization.JavaScriptSerializer.serialize(m);
}};
a.registerControlProperties(b.RadTagCloud,{minFontSize:"0.8em",maxFontSize:"1.7em",maxNumberOfItems:0,minimalWeightAllowed:0,renderItemWeight:false,minColor:"",maxColor:"",foreColor:"",minimalWeight:0,maximalWeight:0,distribution:b.TagCloudDistribution.Linear,sorting:b.TagCloudSorting.NotSorted,appendClientDataBoundItems:false});
a.registerControlEvents(b.RadTagCloud,["load","itemClicking","itemClicked","itemsRequested","itemsRequesting","itemsRequestFailed",f,d]);
b.RadTagCloud.registerClass("Telerik.Web.UI.RadTagCloud",b.RadWebControl);
var c=function(i,h){b[i]=function(){var j=Array.prototype.slice.call(arguments);
b[i].initializeBase(this,j);
};
b[i].registerClass("Telerik.Web.UI."+i,h);
};
b.TagCloudEventArgs=function(h){b.TagCloudEventArgs.initializeBase(this);
this._item=h;
};
b.TagCloudEventArgs.prototype={get_item:function(){return this._item;
}};
b.TagCloudEventArgs.registerClass("Telerik.Web.UI.TagCloudEventArgs",Sys.EventArgs);
c("RadTagCloudEventArgs",Telerik.Web.UI.TagCloudEventArgs);
b.TagCloudErrorEventArgs=function(h){b.TagCloudErrorEventArgs.initializeBase(this);
this._cancelErrorAlert=false;
this._errorMessage=h;
};
b.TagCloudErrorEventArgs.prototype={get_errorMessage:function(){return this._errorMessage;
},get_cancelErrorAlert:function(){return this._cancelErrorAlert;
},set_cancelErrorAlert:function(h){this._cancelErrorAlert=h;
}};
b.TagCloudErrorEventArgs.registerClass("Telerik.Web.UI.TagCloudErrorEventArgs",Sys.EventArgs);
c("RadTagCloudErrorEventArgs",Telerik.Web.UI.TagCloudErrorEventArgs);
b.TagCloudCancelEventArgs=function(h){b.TagCloudCancelEventArgs.initializeBase(this);
this._item=h;
};
b.TagCloudCancelEventArgs.prototype={get_item:function(){return this._item;
}};
b.TagCloudCancelEventArgs.registerClass("Telerik.Web.UI.TagCloudCancelEventArgs",Sys.CancelEventArgs);
c("RadTagCloudCancelEventArgs",Telerik.Web.UI.TagCloudCancelEventArgs);
b.TagCloudItemDataBoundEventArgs=function(i,h){var j=this;
b.TagCloudItemDataBoundEventArgs.initializeBase(j);
j._item=i;
j._dataItem=h;
};
b.TagCloudItemDataBoundEventArgs.prototype={get_item:function(){return this._item;
},get_dataItem:function(){return this._dataItem;
}};
b.TagCloudItemDataBoundEventArgs.registerClass("Telerik.Web.UI.TagCloudItemDataBoundEventArgs",Sys.EventArgs);
c("RadTagCloudItemDataBoundEventArgs",Telerik.Web.UI.TagCloudItemDataBoundEventArgs);
b.RadTagCloudItem=function(h){b.RadTagCloudItem.initializeBase(this,[h]);
this._accessKey=null;
this._index=-1;
this._navigateUrl=null;
this._tabIndex=null;
this._text=null;
this._value=null;
this._toolTip=null;
this._weight=null;
this._anchorElement=null;
this._rowIndex=1;
};
b.RadTagCloudItem.prototype={initialize:function(){b.RadTagCloudItem.callBaseMethod(this,"initialize");
},dispose:function(){b.RadTagCloudItem.callBaseMethod(this,"dispose");
},_setTarget:function(h){if(h==""){this.get_anchorElement().removeAttribute("target");
return;
}this.get_anchorElement().setAttribute("target",h);
},get_accessKey:function(){if(!this._accessKey){var h=this.get_anchorElement();
this._accessKey=h.getAttribute("accessKey");
}return this._accessKey;
},set_accessKey:function(i){this._accessKey=i;
var h=this.get_anchorElement();
if(i){h.setAttribute("accessKey",this._accessKey);
}else{h.removeAttribute("accessKey");
}},get_index:function(){if(this._index==-1){var i=0;
var h=this.get_element();
var j=h.parentNode;
if(null!=j){var k=$telerik.getChildrenByTagName(j,"li");
if(null!=k){i=0;
while(i<k.length&&k[i]!=h){i++;
}if(i==k.length){i=0;
}}}this._index=i;
}return this._index;
},get_navigateUrl:function(){if(this._navigateUrl==null){var h=this.get_anchorElement();
this._navigateUrl=h.getAttribute("href");
}return this._navigateUrl;
},set_navigateUrl:function(i){this._navigateUrl=i;
var h=this.get_anchorElement();
h.setAttribute("href",this._navigateUrl||"javascript:void(0);",2);
},get_tabIndex:function(){if(!this._tabIndex){var h=this.get_anchorElement();
this._tabIndex=h.getAttribute("tabIndex");
}return this._tabIndex;
},set_tabIndex:function(i){this._tabIndex=i;
var h=this.get_anchorElement();
if(this._tabIndex){h.setAttribute("tabIndex",this._tabIndex);
}else{h.removeAttribute("tabIndex");
}},get_text:function(){if(this._text==null){var h=this.get_anchorElement();
if(h.textContent){this._text=h.textContent;
}else{if(h.innerText){this._text=h.innerText;
}}}return this._text;
},set_text:function(i){this._text=i||"";
var h=this.get_anchorElement();
if(!this._toolTip){h.setAttribute("title",this._text);
}if(h.textContent){h.textContent=this._text;
}else{if(h.innerText){h.innerText=this._text;
}}},get_value:function(){return this._value;
},set_value:function(h){this._value=h;
},get_toolTip:function(){if(this._toolTip==null){var h=this.get_anchorElement();
this._toolTip=h.getAttribute("title");
}return this._toolTip;
},set_toolTip:function(i){this._toolTip=i;
var h=this.get_anchorElement();
h.setAttribute("title",this._toolTip||this._text||"");
},get_weight:function(){return this._weight||0;
},set_weight:function(h){this._weight=h||0;
},get_anchorElement:function(){if(this._anchorElement==null){this._anchorElement=$telerik.getChildrenByTagName(this.get_element(),"a")[0]||this.createAnchor();
}return this._anchorElement;
},get_rowIndex:function(){return this._rowIndex;
},createAnchor:function(){var h=this.get_element();
a(h).append('<a rel="tag">&nbsp;</a>');
return h.lastChild;
}};
b.RadTagCloudItem.registerClass("Telerik.Web.UI.RadTagCloudItem",Sys.UI.Control);
})($telerik.$);
