using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Concretec.Pedidos.BE
{
    public class CB2
    {
        public string IdCB2 { set; get; }
        public string Folio { set; get; }
        public string Fecha_Hora_Final { set; get; }
        public string Pta { set; get; }
        public string ID_Carga_Rem { set; get; }
        public string Fecha_Hora_Final_2 { set; get; }
        public string Producto { set; get; }
        public string Codigo { set; get; }
        public string M3 { set; get; }
        public string ID_Dosif_Pedido { set; get; }
        public string Vol_M3 { set; get; }
        public string Manual { set; get; }
        public string CR { set; get; }
        public string Operador { set; get; }
        public string Fecha_Hora_Inicial { set; get; }
        public string Fecha_Hora_Final_3 { set; get; }
        public string Ingr_1 { set; get; }
        public string HuFac_1 { set; get; }
        public string AbsFac_1 { set; get; }
        public string Sec_1 { set; get; }
        public string Abs_1 { set; get; }
        public string SSS_1 { set; get; }
        public string U_Med_1 { set; get; }
        public string Acor_1 { set; get; }
        public string M3_1 { set; get; }
        public string Obj_1 { set; get; }
        public string Real_1 { set; get; }
        public string U_Med_1A { set; get; }
        public string Err_1 { set; get; }
        public string Porcentaje_1 { set; get; }
        public string Ingr_2 { set; get; }
        public string HuFac_2 { set; get; }
        public string AbsFac_2 { set; get; }
        public string Sec_2 { set; get; }
        public string Abs_2 { set; get; }
        public string SSS_2 { set; get; }
        public string U_Med_2 { set; get; }
        public string Acor_2 { set; get; }
        public string M3_2 { set; get; }
        public string Obj_2 { set; get; }
        public string Real_2 { set; get; }
        public string U_Med_2A { set; get; }
        public string Err_2 { set; get; }
        public string Porcentaje_2 { set; get; }
        public string Ingr_3 { set; get; }
        public string HuFac_3 { set; get; }
        public string AbsFac_3 { set; get; }
        public string Sec_3 { set; get; }
        public string Abs_3 { set; get; }
        public string SSS_3 { set; get; }
        public string U_Mes_3 { set; get; }
        public string Acor_3 { set; get; }
        public string M3_3 { set; get; }
        public string Obj_3 { set; get; }
        public string Real_3 { set; get; }
        public string U_Med_3 { set; get; }
        public string Err_3 { set; get; }
        public string Porcentaje_3 { set; get; }
        public string Ingr_4 { set; get; }
        public string HuFac_4 { set; get; }
        public string AbsFac_4 { set; get; }
        public string Sec_4 { set; get; }
        public string Abs_4 { set; get; }
        public string SSS_4 { set; get; }
        public string U_Med_4 { set; get; }
        public string Acor_4 { set; get; }
        public string M3_4 { set; get; }
        public string Obj_4 { set; get; }
        public string Real_4 { set; get; }
        public string U_Med_4A { set; get; }
        public string Err_4 { set; get; }
        public string Porcentaje_4 { set; get; }
        public string Ingr_5 { set; get; }
        public string HuFac_5 { set; get; }
        public string AbsFac_5 { set; get; }
        public string Sec_5 { set; get; }
        public string Abs_5 { set; get; }
        public string SSS_5 { set; get; }
        public string U_Med_5 { set; get; }
        public string Acor_5 { set; get; }
        public string M3_5 { set; get; }
        public string Obj_5 { set; get; }
        public string Real_5 { set; get; }
        public string U_Med_5A { set; get; }
        public string Err_5 { set; get; }
        public string Porcentaje_5 { set; get; }
        public string Ingr_6 { set; get; }
        public string HuFac_6 { set; get; }
        public string AbsFac_6 { set; get; }
        public string Sec_6 { set; get; }
        public string Abs_6 { set; get; }
        public string SSS_6 { set; get; }
        public string U_Med_6 { set; get; }
        public string Acor_6 { set; get; }
        public string M3_6 { set; get; }
        public string Obj_6 { set; get; }
        public string Real_6 { set; get; }
        public string U_Med_6A { set; get; }
        public string Err_6 { set; get; }
        public string Porcentaje_6 { set; get; }
        public string Ingr_7 { set; get; }
        public string HuFac_7 { set; get; }
        public string AbsFac_7 { set; get; }
        public string Sec_7 { set; get; }
        public string Abs_7 { set; get; }
        public string SSS_7 { set; get; }
        public string U_Med_7 { set; get; }
        public string Acor_7 { set; get; }
        public string M3_7 { set; get; }
        public string Obj_7 { set; get; }
        public string Real_7 { set; get; }
        public string U_Med_7A { set; get; }
        public string Err_7 { set; get; }
        public string Porcentaje_7 { set; get; }
        public string Ingr_8 { set; get; }
        public string HuFac_8 { set; get; }
        public string AbsFac_8 { set; get; }
        public string Sec_8 { set; get; }
        public string Abs_8 { set; get; }
        public string SSS_8 { set; get; }
        public string U_Med_8 { set; get; }
        public string Acor_8 { set; get; }
        public string M3_8 { set; get; }
        public string Obj_8 { set; get; }
        public string Real_8 { set; get; }
        public string U_Med_8A { set; get; }
        public string Err_8 { set; get; }
        public string Porcentaje_8 { set; get; }
        public string Ingr_9 { set; get; }
        public string HuFac_9 { set; get; }
        public string AbsFac_9 { set; get; }
        public string Sec_9 { set; get; }
        public string Abs_9 { set; get; }
        public string SSS_9 { set; get; }
        public string U_Med_9 { set; get; }
        public string Acor_9 { set; get; }
        public string M3_9 { set; get; }
        public string Obj_9 { set; get; }
        public string Real_9 { set; get; }
        public string U_Med_9A { set; get; }
        public string Err_9 { set; get; }
        public string Porcentaje_9 { set; get; }
        public string Ingr_10 { set; get; }
        public string HuFac_10 { set; get; }
        public string AbsFac_10 { set; get; }
        public string Sec_10 { set; get; }
        public string Abs_10 { set; get; }
        public string SSS_10 { set; get; }
        public string U_Med_10 { set; get; }
        public string Acor_10 { set; get; }
        public string M3_10 { set; get; }
        public string Obj_10 { set; get; }
        public string Real_10 { set; get; }
        public string U_Med_10A { set; get; }
        public string Err_10 { set; get; }
        public string Porcentaje_10 { set; get; }
        public string Ingr_11 { set; get; }
        public string HuFac_11 { set; get; }
        public string AbsFac_11 { set; get; }
        public string Sec_11 { set; get; }
        public string Abs_11 { set; get; }
        public string SSS_11 { set; get; }
        public string U_Med_11 { set; get; }
        public string Acor_11 { set; get; }
        public string M3_11 { set; get; }
        public string Obj_11 { set; get; }
        public string Real_11 { set; get; }
        public string U_Med_11A { set; get; }
        public string Err_11 { set; get; }
        public string Porcentaje_11 { set; get; }
        public string Ingr_12 { set; get; }
        public string HuFac_12 { set; get; }
        public string AbsFac_12 { set; get; }
        public string Sec_12 { set; get; }
        public string Abs_12 { set; get; }
        public string SSS_12 { set; get; }
        public string U_Med_12 { set; get; }
        public string Acor_12 { set; get; }
        public string M3_12 { set; get; }
        public string Obj_12 { set; get; }
        public string Real_12 { set; get; }
        public string U_Med_12B { set; get; }
        public string Err_12 { set; get; }
        public string Porcentaje_12 { set; get; }
        public string Ingr_13 { set; get; }
        public string HuFac_13 { set; get; }
        public string AbsFac_13 { set; get; }
        public string Sec_13 { set; get; }
        public string Abs_13 { set; get; }
        public string SSS_13 { set; get; }
        public string U_Med_13 { set; get; }
        public string Acor_13 { set; get; }
        public string M3_13 { set; get; }
        public string Obj_13 { set; get; }
        public string Real_13 { set; get; }
        public string U_Med_13A { set; get; }
        public string Err_13 { set; get; }
        public string Porcentaje_13 { set; get; }
        public string Ingr_14 { set; get; }
        public string HuFac_14 { set; get; }
        public string AbsFac_14 { set; get; }
        public string Sec_14 { set; get; }
        public string Abs_14 { set; get; }
        public string SSS_14 { set; get; }
        public string U_Med_14 { set; get; }
        public string Acor_14 { set; get; }
        public string M3_14 { set; get; }
        public string Obj_14 { set; get; }
        public string Real_14 { set; get; }
        public string U_Med_14A { set; get; }
        public string Err_14 { set; get; }
        public string Porcentaje_14 { set; get; }
        public string Ingr_15 { set; get; }
        public string HuFac_15 { set; get; }
        public string AbsFac_15 { set; get; }
        public string Sec_15 { set; get; }
        public string Abs_15 { set; get; }
        public string SSS_15 { set; get; }
        public string U_Med_15 { set; get; }
        public string Acor_15 { set; get; }
        public string M3_15 { set; get; }
        public string Obj_15 { set; get; }
        public string Real_15 { set; get; }
        public string U_Med_15A { set; get; }
        public string Err_15 { set; get; }
        public string Porcentaje_15 { set; get; }
        public string Ingr_16 { set; get; }
        public string HuFac_16 { set; get; }
        public string AbsFac_16 { set; get; }
        public string Sec_16 { set; get; }
        public string Abs_16 { set; get; }
        public string SSS_16 { set; get; }
        public string U_Med_16 { set; get; }
        public string Acor_16 { set; get; }
        public string M3_16 { set; get; }
        public string Obj_16 { set; get; }
        public string Real_16 { set; get; }
        public string U_Med_16A { set; get; }
        public string Err_16 { set; get; }
        public string Porcentaje_16 { set; get; }
        public string Ingr_17 { set; get; }
        public string HuFac_17 { set; get; }
        public string AbsFac_17 { set; get; }
        public string Sec_17 { set; get; }
        public string Abs_17 { set; get; }
        public string SSS_17 { set; get; }
        public string U_Med_17 { set; get; }
        public string Acor_17 { set; get; }
        public string M3_17 { set; get; }
        public string Obj_17 { set; get; }
        public string Real_17 { set; get; }
        public string U_Med_17A { set; get; }
        public string Err_17 { set; get; }
        public string Porcentaje_17 { set; get; }
        public string Ingr_18 { set; get; }
        public string HuFac_18 { set; get; }
        public string AbsFac_18 { set; get; }
        public string Sec_18 { set; get; }
        public string Abs_18 { set; get; }
        public string SSS_18 { set; get; }
        public string U_Med_18 { set; get; }
        public string Acor_18 { set; get; }
        public string M3_18 { set; get; }
        public string Obj_18 { set; get; }
        public string Real_18 { set; get; }
        public string U_Med_18A { set; get; }
        public string Err_18 { set; get; }
        public string Porcentaje_18 { set; get; }
        public string Ingr_19 { set; get; }
        public string HuFac_19 { set; get; }
        public string AbsFac_19 { set; get; }
        public string Sec_19 { set; get; }
        public string Abs_19 { set; get; }
        public string SSS_19 { set; get; }
        public string U_Med_19 { set; get; }
        public string Acor_19 { set; get; }
        public string M3_19 { set; get; }
        public string Obj_19 { set; get; }
        public string Real_19 { set; get; }
        public string U_Med_19A { set; get; }
        public string Err_19 { set; get; }
        public string Porcentaje_19 { set; get; }
        public string Rev { set; get; }
        public string Agua_Ajuste { set; get; }
        public string Rel_Agua_Cem { set; get; }
    }
}
