(function(a,l){Type.registerNamespace("Telerik.Web.UI");
var g="rgFocusable",h="rgActiveCell",k="selected-th",j="tr:visible",e=":visible",b=j+">td"+e,f=b+":first",d="click",c="change",i={BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F12:123};
Telerik.Web.UI.GridCellSelection=function(){Telerik.Web.UI.GridCellSelection.initializeBase(this);
this._owner={};
this._currentTableView;
this._lastActiveHeader=null;
this.options=null;
this._multiple=false;
this._columnSelect=false;
this._multiColumnSelect=false;
this._masterTable=null;
this._current=null;
this.selectable=null;
this.wrapper=null;
this._cellSelectedDelegate=null;
this._cellSelectingDelegate=null;
this._cellDeselectingDelegate=null;
this._cellDeselectedDelegate=null;
this._upDelegate=null;
};
Telerik.Web.UI.GridCellSelection.prototype={initialize:function(){Telerik.Web.UI.GridCellSelection.callBaseMethod(this,"initialize");
this._cellSelectingDelegate=Function.createDelegate(this,this._cellSelecting);
this._cellSelectedDelegate=Function.createDelegate(this,this._cellSelected);
this._cellDeselectingDelegate=Function.createDelegate(this,this._cellDeselecting);
this._cellDeselectedDelegate=Function.createDelegate(this,this._cellDeselected);
this.wrapper=a(this._owner.get_element());
this._masterTable=$get(this._owner._masterClientID).tBodies[0];
$addHandlers(this._masterTable,{mousedown:function(m){var n=Telerik.Web.UI.Grid.GetCurrentElement(m);
if(!Telerik.Web.UI.Grid.IsEditableControl(n)){Telerik.Web.UI.Grid.ClearDocumentEvents();
}},mouseup:function(){Telerik.Web.UI.Grid.RestoreDocumentEvents();
}});
if(this._owner.ClientSettings.AllowKeyboardNavigation){this._navigatable();
}this._selectable();
},_navigatable:function(){var r=this,s=r.wrapper,q=a(r._masterTable).addClass(g),o=a.proxy(r.current,r),p="."+g+" "+b,m=a.browser,n=function(t){if(!r._owner._getGridRow(t)){return;
}if(a(t.currentTarget).parent().attr("id")!=l){o(a(t.currentTarget));
if(!a(t.target).is(":button,a,:input, textarea")){s.focus();
}}};
s.bind({focus:function(u){var t=r._current;
if(t&&t.is(":visible")){t.addClass(h);
}else{if(r.get_owner().ClientSettings.Scrolling.EnableVirtualScrollPaging){var v=a(r._masterTable).find(f);
if(v!=l&&v.length){v.addClass(h);
r._current=v;
}}else{o(a(r._masterTable).find(f));
}}},focusout:function(){if(r._current){r._current.removeClass(h);
}},keydown:function(w){var A=w.keyCode,u=r.current(),F=w.shiftKey,t=!a(w.target).is(":button,a,:input,a>.t-icon"),y=false;
if(u==l||!t){return;
}if(F){if(!u.hasClass(r.options.styles.SELECTED)&&w.keyCode!=16){r.select(u);
}}if(i.UP===A){var E=u.parent().prevAll(j).first();
var x=q.find(f);
if(E.length!=0&&E.attr("id")==null){var v=E.find('table[id*="Detail"]');
E=v.find("tr[id]:visible").last();
x=E.find(f);
}else{if(E.length==0){E=u.parent();
var C=E.parents('table[id*="Detail"]').parents("tr");
var D;
for(var z=0;
z<C.length;
z++){D=a(C[z]).prev("tr[id]");
if(D!=null){E=D;
break;
}}}}o(u?E.children(":eq("+u.index()+"),:eq(0)").last():x);
y=true;
}else{if(i.DOWN===A){var E=u.parent().nextAll(j).first();
var x=q.find(f);
if(E.length!=0&&E.attr("id")==null){var v=E.find('table[id*="Detail"]');
E=v.find("tr[id]:visible").first();
x=E.find(f);
}else{if(E.length==0){E=u.parent();
var C=E.parents('table[id*="Detail"]').parents("tr");
var B;
for(var z=0;
z<C.length;
z++){B=a(C[z]).next("tr[id]");
if(B!=null){E=B;
break;
}}}}o(u?E.children(":eq("+u.index()+"),:eq(0)").last():x);
y=true;
}else{if(i.LEFT===A){o(u?u.prevAll(e+":first"):q.find(f));
y=true;
}else{if(i.RIGHT===A){o(u?u.nextAll(":visible:first"):q.find(f));
y=true;
}}}}if(y){w.preventDefault();
if(F){r.select(r.current());
}}}});
s.delegate(p,"mousedown",n);
},_selectable:function(){var o=this;
var n="rgCellSelectorArea rgCellSelectorArea_"+o._owner.Skin;
o.selectable=new Telerik.Web.UI.Extensions.Selectable(o._owner.get_element(),{filter:"tr[id] > td:visible",multiple:o.get_multiple(),multiColumnSelect:o.get_multiColumnSelect(),owner:o._owner,styles:{SELECTED:"rgSelectedCell",ACTIVE:"rgFocusedCell",UNSELECTING:"web-ui-state-unselecting",MARQUEE:n},change:function(){}});
o.options=o.selectable.options;
var m=a.proxy(o._getGridTableFromElement,o);
a.extend(o.selectable,{getParentTable:function(p){return m(p);
}});
o.selectable.bind("select",o._cellSelectingDelegate);
o.selectable.bind("selected",o._cellSelectedDelegate);
o.selectable.bind("deselect",o._cellDeselectingDelegate);
o.selectable.bind("deselected",o._cellDeselectedDelegate);
if(o.get_columnSelect()){o.wrapper.delegate("th","mousedown",a.proxy(o._thMouseDown,o));
o._upDelegate=a.proxy(o.selectable._up,o.selectable);
}if(o._owner.ClientSettings.AllowKeyboardNavigation){o.wrapper.keydown(function(r){var p=!a(r.target).is(":button,a,:input,a>.t-icon"),s=$find(r.target.id);
if(!p||(s&&Telerik.Web.UI.RadGrid.isInstanceOfType(s)&&s.get_id()!=o._owner.get_id())){return;
}var q=o.current();
if(r.keyCode===i.SPACEBAR){r.preventDefault();
if(o.get_multiple()){if(!r.ctrlKey){o.selectable.clear();
}else{if(q.hasClass(o.options.styles.SELECTED)){o.deselect(q);
q.removeClass(o.options.styles.SELECTED);
q=null;
}}}else{o.selectable.clear();
}o.select(q);
}});
}},_thMouseDown:function(o){var q=this,n=o.target;
if(q._owner._isResize){return;
}do{if(Telerik.Web.UI.RadGrid.isInstanceOfType($find(n.id))){if($find(n.id)!==q._owner){return;
}break;
}n=n.parentNode;
}while(n);
if(!a(o.target).is(":button,a,:input, textarea")&&!(a(o.target).is("span")&&a(o.target).attr("onclick")!=l&&a(o.target).attr("onclick")!="")){var m=o.ctrlKey,p=o.shiftKey;
q._shiftPressed=o.shiftKey;
q._downTarget=a(o.currentTarget);
q.wrapper.undelegate("th","mouseup",q._upDelegate);
q.wrapper.delegate("th","mouseup",q._upDelegate);
if(q.options.multiColumnSelect){q._prepareCellsForMultiColumnSelection(p,m);
}else{q._prepareCellsForSingleColumnSelection(p,m);
}q._lastActiveHeader=q._downTarget;
}},select:function(m){var o=this,n=o.selectable;
m=a(m);
if(m.length){if(!n.options.multiple){n.clear();
m=m.first();
}n.value(m);
return;
}return n.value();
},deselect:function(m){var o=this,n=o.selectable;
m=a(m);
if(m.length){n.unselect(m);
}},current:function(n){var o=this,m=o._current;
if(n!==l&&n.length){if(!m||m[0]!==n[0]){n.addClass(h);
if(m){m.removeClass(h);
}o._current=n;
if(o.get_owner().ClientSettings.Scrolling.AllowScroll){o._scrollTo(n.parent()[0],n[0]);
}}}return o._current;
},_cellSelecting:function(m){var o=this;
if(!o._owner._getGridRow({target:m.element})){m.preventDefault();
return;
}var n=new Telerik.Web.UI.GridCellSelectCancelEventArgs(m.element,a);
o._owner.raise_cellSelecting(n);
if(n.get_cancel()||!n.get_column().get_selectable()){m.preventDefault();
}},_cellSelected:function(m){var n=new Telerik.Web.UI.GridCellSelectEventArgs(m.element,a);
if(!Array.contains(this._owner._selectedCellsIndexes,n.get_cellIndexHierarchical())){Array.add(this._owner._selectedCellsIndexes,n.get_cellIndexHierarchical());
}this._owner.raise_cellSelected(n);
this._owner.updateClientState();
n.get_column()._selectedCellsCount++;
},_cellDeselecting:function(m){var n=new Telerik.Web.UI.GridCellSelectCancelEventArgs(m.element,a);
this._owner.raise_cellDeselecting(n);
if(n.get_cancel()||!n.get_column().get_selectable()){m.preventDefault();
}},_cellDeselected:function(m){var n=new Telerik.Web.UI.GridCellSelectEventArgs(m.element,a);
if(Array.contains(this._owner._selectedCellsIndexes,n.get_cellIndexHierarchical())){Array.remove(this._owner._selectedCellsIndexes,n.get_cellIndexHierarchical());
}this._owner.raise_cellDeselected(n);
this._owner.updateClientState();
n.get_column()._selectedCellsCount--;
},_prepareCellsForSingleColumnSelection:function(v,p){var y=this;
var u=y._getGridTableFromElement(y._downTarget);
var x=y._downTarget;
if(u!=null){var m;
var s=y._getHeaderSettings(u);
var r=s.getHeaderIndex(x);
if(p){m=a(u).find(">tbody>"+y.options.filter+":nth-child("+(r+1)+")");
y._setActiveOrUnselecting(m);
y._setActiveCellUponColumnSelection(m);
var w=y.get_currentTableView(x[0]);
var o=w.get_columns();
for(var t=0;
t<o.length;
t++){var n=o[t];
if(n.get_selected()){x=n.get_element();
m=a(u).find(">tbody>"+y.options.filter+":nth-child("+(s.getHeaderIndex(x)+1)+")");
y._setUnselecting(m);
}}}else{m=a(u).find(">tbody>"+y.options.filter+":nth-child("+(r+1)+")");
y._setActive(m);
var q=y.wrapper.find(y.options.filter+"."+y.options.styles.SELECTED).not(m);
y.selectable.unselect(q);
q.last().removeClass(h);
y._setActiveCellUponColumnSelection(m);
}}},_prepareCellsForMultiColumnSelection:function(w,n){var z=this;
var v=z._getGridTableFromElement(z._downTarget);
if(v!=null){var m;
var x;
var r=z._getHeaderSettings(v);
if(w){if(z._lastActiveHeader==l||z._lastActiveHeader.length==0){x=z._downTarget;
var p=r.getHeaderIndex(x);
m=a(v).find(">tbody>"+z.options.filter+":nth-child("+(p+1)+")");
z._setActiveOrUnselecting(m);
if(this._owner.ClientSettings.AllowKeyboardNavigation){z._setActiveCellUponColumnSelection(m);
}}else{if(z._lastActiveHeader[0]==z._downTarget[0]){return;
}else{x=z._downTarget;
var q;
z.selectable._shiftPressed=false;
if(r.hasMultiHeaders){var u=r.multiHeaders;
var y=a.inArray(x[0],u);
var t=a.inArray(z._lastActiveHeader[0],u);
if(y>t){q=u.slice(t+1,y+1);
}else{q=u.slice(y,t).reverse();
}}else{if(x.index()>z._lastActiveHeader.index()){q=z._lastActiveHeader.nextAll();
}else{q=z._lastActiveHeader.prevAll();
}}var s=0;
while(s<q.length){x=a(q[s]);
var p=r.getHeaderIndex(x);
m=a(v).find(">tbody>"+z.options.filter+":nth-child("+(p+1)+")");
z._setActiveOrUnselecting(m);
if(x[0]===z._downTarget[0]){if(this._owner.ClientSettings.AllowKeyboardNavigation){z._setActiveCellUponColumnSelection(m);
}break;
}s++;
}}}}else{if(n){x=z._downTarget;
var p=r.getHeaderIndex(x);
m=a(v).find(">tbody>"+z.options.filter+":nth-child("+(p+1)+")");
z._setActiveOrUnselecting(m);
if(this._owner.ClientSettings.AllowKeyboardNavigation){z._setActiveCellUponColumnSelection(m);
}}else{x=z._downTarget;
var p=r.getHeaderIndex(x);
m=a(v).find(">tbody>"+z.options.filter+":nth-child("+(p+1)+")");
z._setActive(m);
var o=z.wrapper.find(z.options.filter+"."+z.options.styles.SELECTED).not(m);
z.selectable.unselect(o);
o.last().removeClass(h);
if(this._owner.ClientSettings.AllowKeyboardNavigation){z._setActiveCellUponColumnSelection(m);
}}}}},_setActiveCellUponColumnSelection:function(m){var n=this;
n.selectable._downTarget=n.current(m.first());
},_setActiveCellElement:function(m){var n=this;
n.selectable._downTarget=n.current(a(m));
},_setActiveOrUnselecting:function(m){var o=this;
for(var n=0;
n<m.length;
n++){if(a(m[n]).hasClass(o.options.styles.SELECTED)){a(m[n]).addClass(o.options.styles.UNSELECTING);
}else{a(m[n]).addClass(o.options.styles.ACTIVE);
}}},_setActive:function(m){var o=this;
for(var n=0;
n<m.length;
n++){if(!a(m[n]).hasClass(o.options.styles.SELECTED)){a(m[n]).addClass(o.options.styles.ACTIVE);
}}},_setUnselecting:function(m){var o=this;
for(var n=0;
n<m.length;
n++){if(a(m[n]).hasClass(o.options.styles.SELECTED)){a(m[n]).addClass(o.options.styles.UNSELECTING);
}}},_scrollTo:function(p,m){var o=p.offsetTop,n=$get(this._owner.get_id()+"_GridData");
elementOffsetLeft=m.offsetLeft,elementOffsetHeight=p.offsetHeight,elementOffsetWidth=m.offsetWidth,containerScrollTop=n.scrollTop,containerScrollLeft=n.scrollLeft,containerOffsetHeight=n.clientHeight,containerOffsetWidth=n.clientWidth,bottomDistance=o+elementOffsetHeight,horizontalDistance=elementOffsetLeft+elementOffsetWidth;
n.scrollTop=containerScrollTop>o?o:bottomDistance>(containerScrollTop+containerOffsetHeight)?bottomDistance-containerOffsetHeight:containerScrollTop;
n.scrollLeft=containerScrollLeft>elementOffsetLeft?elementOffsetLeft:horizontalDistance>(containerScrollLeft+containerOffsetWidth)?horizontalDistance-containerOffsetWidth:containerScrollLeft;
},_selectColumnByHeaderElement:function(n,m){var o=this;
if(n.get_element!=null){o._selectColumnCells(m,n.get_element());
}else{o._selectColumnCells(m,n);
}},_deselectColumnByHeaderElement:function(n,m){var o=this;
if(n.get_element!=null){o._deselectColumnCells(m,n.get_element());
}else{o._deselectColumnCells(m,n);
}},_selectColumnCells:function(p,n){var o=this;
if(n==null){n=o._getGridTableFromElement(p);
}if(n){var m=o._getHeaderSettings(n).getHeaderIndex(p);
cells=a(n).find(">tbody>"+o.options.filter+":nth-child("+(m+1)+")");
o.selectable.value(cells);
}},_deselectColumnCells:function(p,n){var o=this;
if(n==null){n=o._getGridTableFromElement(p);
}if(n){var m=o._getHeaderSettings(n).getHeaderIndex(p);
cells=a(n).find(">tbody>"+o.options.filter+":nth-child("+(m+1)+")");
o.selectable.unselect(cells);
}},_deselectTableViewCells:function(m){var n=this;
if(m){if(m.get_element!=l){m=m.get_element();
}cells=a(m).find(">tbody>"+n.options.filter+"."+n.options.styles.SELECTED);
n.selectable.unselect(cells);
}},_clear:function(){var m=this;
m.selectable.clear();
},_isMasterTable:function(n){var m=false;
if(n.id==this._owner._masterClientID){m=true;
}return m;
},_isDetailTable:function(n){var m=new RegExp(this.get_owner().get_id()+".+Detail.+");
return m.test(n.id);
},_isHeaderTable:function(n){var m=new RegExp(this.get_owner().get_id()+".+Header");
return m.test(n.id);
},_getGridTableFromElement:function(m){var q=this;
var p;
var o=a(m).parents("table");
for(var n=0;
n<o.length;
n++){if(q._isMasterTable(o[n])||q._isDetailTable(o[n])){p=o[n];
break;
}else{if(q._isHeaderTable(o[n])){p=a(o[n]).parents('div[id="'+this.get_owner().get_id()+'"]').find('div[id="'+this.get_owner().get_id()+'_GridData"]').find('table[id*="'+this.get_owner().get_id()+'"]');
if(p.length>0){p=p[0];
}}}}return p;
},_getHeaderSettings:function(r){var q={hasMultiHeaders:false,multiHeaders:[],getHeaderIndex:function(s){return a(s).index();
}};
if(!!r.id){var m=$find(r.id);
var n=this._owner;
if(m&&!m.get_parentView()){m=n.MasterTableViewHeader?n.MasterTableViewHeader:n.MasterTableView;
}var o=m._hasMultiHeaders,p=m.MultiHeaderCells;
if(o){q.hasMultiHeaders=true;
q.multiHeaders=p;
q.getHeaderIndex=function(t){var s=a(t);
return a.inArray(s[0],p);
};
}}return q;
},get_currentTableView:function(){var p=this;
var m=p.selectable._lastActive;
var o;
if(m.is("th")){o=p._getGridTableFromElement(m).id;
}else{var n=m.parents("tr[id]").first();
o=n[0].id.split("__")[0];
}if(p._currentTableView==null||p._currentTableView.get_id()!=o){p._currentTableView=$find(o);
}return p._currentTableView;
},get_currentTableView:function(o){var n=this;
var m;
m=n._getGridTableFromElement(o).id;
if(n._currentTableView==null||n._currentTableView.get_id()!=m){n._currentTableView=$find(m);
}return n._currentTableView;
},get_column:function(q){var p=this;
var n=p.get_currentTableView().get_columns();
var m;
for(var o=0;
o<n.length;
o++){if(n[o].get_uniqueName()==q){m=n[o];
break;
}}return m;
},get_owner:function(){return this._owner;
},set_owner:function(m){this._owner=m;
},get_multiple:function(){return this._multiple;
},set_multiple:function(m){this._multiple=m;
},get_columnSelect:function(){return this._columnSelect;
},set_columnSelect:function(m){this._columnSelect=m;
},get_multiColumnSelect:function(){return this._multiColumnSelect;
},set_multiColumnSelect:function(m){this._multiColumnSelect=m;
}};
Telerik.Web.UI.GridCellSelection.registerClass("Telerik.Web.UI.GridCellSelection",Sys.Component);
})($telerik.$);
