(function(b,a){a(["./kendo.data","./kendo.userevents","./kendo.dataviz.themes"],b);
})(function(){(function(a,I){var s=Math,y=a.proxy,r=window.kendo,d=r.Class,L=r.ui.Widget,G=r.template,l=r.deepExtend,p=r.data.HierarchicalDataSource,o=r.getter,j=r.dataviz;
var x=".kendoTreeMap",c="change",i="dataBound",q="itemCreated",t=Number.MAX_VALUE,u=-Number.MAX_VALUE,w="mouseover"+x,v="mouseleave"+x,J="undefined";
var H=L.extend({init:function(M,N){r.destroy(M);
a(M).empty();
L.fn.init.call(this,M,N);
this._initTheme(this.options);
this.element.addClass("k-widget k-treemap");
this._setLayout();
this._originalOptions=l({},this.options);
this._initDataSource();
this._attachEvents();
r.notify(this,j.ui);
},options:{name:"TreeMap",theme:"default",autoBind:true,textField:"text",valueField:"value",colorField:"color"},events:[i,q],_initTheme:function(M){var N=this,Q=j.ui.themes||{},O=((M||{}).theme||"").toLowerCase(),P=(Q[O]||{}).treeMap;
N.options=l({},P,M);
},_attachEvents:function(){this.element.on(w,y(this._mouseover,this)).on(v,y(this._mouseleave,this));
},_setLayout:function(){if(this.options.type==="horizontal"){this._layout=new C(false);
this._view=new D(this,this.options);
}else{if(this.options.type==="vertical"){this._layout=new C(true);
this._view=new D(this,this.options);
}else{this._layout=new E();
this._view=new F(this,this.options);
}}},_initDataSource:function(){var O=this,N=O.options,M=N.dataSource;
O._dataChangeHandler=y(O._onDataChange,O);
O.dataSource=p.create(M).bind(c,O._dataChangeHandler);
if(M){if(O.options.autoBind){O.dataSource.fetch();
}}},setDataSource:function(M){var N=this;
N.dataSource.unbind(c,N._dataChangeHandler);
N.dataSource=M.bind(c,N._dataChangeHandler);
if(M){if(N.options.autoBind){N.dataSource.fetch();
}}},_onDataChange:function(O){var T=O.node;
var S=O.items;
var U=this.options;
var R,Q,M;
if(!T){this.element.empty();
R=this._wrapItem(S[0]);
this._layout.createRoot(R,this.element.outerWidth(),this.element.outerHeight(),this.options.type==="vertical");
this._view.createRoot(R);
this._root=R;
}else{if(S.length){var V=this._getByUid(T.uid);
V.children=[];
if(!m(V.minColor)&&!m(V.maxColor)){M=U.colors||[];
}else{M=g(V.minColor,V.maxColor,S.length)||[];
}for(Q=0;
Q<S.length;
Q++){R=S[Q];
V.children.push(this._wrapItem(R));
}var P=this._view.htmlSize(V);
this._layout.compute(V.children,V.coord,P);
for(Q=0;
Q<V.children.length;
Q++){R=V.children[Q];
if(!m(R.color)){if(typeof(M[0])==="string"){R.color=M[Q%M.length];
}else{var N=M[Q%M.length];
if(N){R.color=N[0];
R.minColor=N[0];
R.maxColor=N[1];
}}}}this._view.render(V);
}}for(Q=0;
Q<S.length;
Q++){S[Q].load();
}if(T){this.trigger(i,{node:T});
}},_contentSize:function(M){this.view.renderHeight(M);
},_wrapItem:function(M){var N={};
if(m(this.options.valueField)){N.value=n(this.options.valueField,M);
}if(m(this.options.colorField)){N.color=n(this.options.colorField,M);
}if(m(this.options.textField)){N.text=n(this.options.textField,M);
}N.level=M.level();
N.dataItem=M;
return N;
},_getByUid:function(O){var N=[this._root];
var M;
while(N.length){M=N.pop();
if(M.dataItem.uid===O){return M;
}if(M.children){N=N.concat(M.children);
}}},dataItem:function(N){var O=a(N).attr(r.attr("uid")),M=this.dataSource;
return M&&M.getByUid(O);
},findByUid:function(M){return this.element.find(".k-treemap-tile["+r.attr("uid")+"='"+M+"']");
},_mouseover:function(M){var N=a(M.target);
if(N.hasClass("k-leaf")){this._removeActiveState();
N.removeClass("k-state-hover").addClass("k-state-hover");
}},_removeActiveState:function(){this.element.find(".k-state-hover").removeClass("k-state-hover");
},_mouseleave:function(){this._removeActiveState();
},destroy:function(){L.fn.destroy.call(this);
this.element.off(x);
if(this.dataSource){this.dataSource.unbind(c,this._dataChangeHandler);
}this._root=null;
r.destroy(this.element);
},items:function(){return a();
},getSize:function(){return r.dimensions(this.element);
},_resize:function(){this.dataSource.fetch();
},setOptions:function(N){var M=N.dataSource;
N.dataSource=I;
this._originalOptions=l(this._originalOptions,N);
this.options=l({},this._originalOptions);
this._setLayout();
this._initTheme(this.options);
L.fn._setEvents.call(this,N);
if(M){this.setDataSource(p.create(M));
}if(this.options.autoBind){this.dataSource.fetch();
}}});
var E=d.extend({createRoot:function(N,O,M){N.coord={width:O,height:M,top:0,left:0};
},leaf:function(M){return !M.children;
},layoutChildren:function(P,M){var S=M.width*M.height;
var U=0,Q=[],O;
for(O=0;
O<P.length;
O++){Q[O]=parseFloat(P[O].value);
U+=Q[O];
}for(O=0;
O<Q.length;
O++){P[O].area=S*Q[O]/U;
}var R=this.layoutHorizontal()?M.height:M.width;
P=new r.data.Query(P)._sortForGrouping("value","desc");
var N=[P[0]];
var T=P.slice(1);
this.squarify(T,N,R,M);
},squarify:function(O,N,P,M){this.computeDim(O,N,P,M);
},computeDim:function(R,P,S,M){if(R.length+P.length==1){var N=R.length==1?R:P;
this.layoutLast(N,S,M);
return;
}if(R.length>=2&&P.length===0){P=[R[0]];
R=R.slice(1);
}if(R.length===0){if(P.length>0){this.layoutRow(P,S,M);
}return;
}var O=R[0];
if(this.worstAspectRatio(P,S)>=this.worstAspectRatio([O].concat(P),S)){this.computeDim(R.slice(1),P.concat([O]),S,M);
}else{var Q=this.layoutRow(P,S,M);
this.computeDim(R,[],Q.dim,Q);
}},layoutLast:function(N,O,M){N[0].coord=M;
},layoutRow:function(N,O,M){if(this.layoutHorizontal()){return this.layoutV(N,O,M);
}else{return this.layoutH(N,O,M);
}},orientation:"h",layoutVertical:function(){return this.orientation==="v";
},layoutHorizontal:function(){return this.orientation==="h";
},layoutChange:function(){this.orientation=this.layoutVertical()?"h":"v";
},worstAspectRatio:function(P,S){if(!P||P.length===0){return t;
}var N=0,Q=0,R=t;
for(var O=0;
O<P.length;
O++){var M=P[O].area;
N+=M;
R=(R<M)?R:M;
Q=(Q>M)?Q:M;
}return s.max((S*S*Q)/(N*N),(N*N)/(S*S*R));
},compute:function(M,P,N){if(!(P.width>=P.height&&this.layoutHorizontal())){this.layoutChange();
}if(M&&M.length>0){var O={width:P.width,height:P.height-N.text,top:0,left:0};
this.layoutChildren(M,O);
}},layoutV:function(Q,T,N){var S=this._totalArea(Q),R=0;
T=B(S/T);
for(var P=0;
P<Q.length;
P++){var O=B(Q[P].area/T);
Q[P].coord={height:O,width:T,top:N.top+R,left:N.left};
R+=O;
}var M={height:N.height,width:N.width-T,top:N.top,left:N.left+T};
M.dim=s.min(M.width,M.height);
if(M.dim!=M.height){this.layoutChange();
}return M;
},layoutH:function(Q,U,N){var T=this._totalArea(Q);
var O=B(T/U),S=N.top,R=0;
for(var P=0;
P<Q.length;
P++){Q[P].coord={height:O,width:B(Q[P].area/O),top:S,left:N.left+R};
R+=Q[P].coord.width;
}var M={height:N.height-O,width:N.width,top:N.top+O,left:N.left};
M.dim=s.min(M.width,M.height);
if(M.dim!=M.width){this.layoutChange();
}return M;
},_totalArea:function(N){var O=0;
for(var M=0;
M<N.length;
M++){O+=N[M].area;
}return O;
}});
var F=d.extend({init:function(N,M){this.options=l({},this.options,M);
this.treeMap=N;
this.element=a(N.element);
this.offset=0;
},htmlSize:function(N){var O=this._getByUid(N.dataItem.uid);
var M={text:0};
if(N.children){this._clean(O);
var P=this._getText(N);
if(P){var Q=this._createTitle(N);
O.append(Q);
M.text=Q.height();
}O.append(this._createWrap());
this.offset=(O.outerWidth()-O.innerWidth())/2;
}return M;
},_getByUid:function(M){return this.element.find(".k-treemap-tile["+r.attr("uid")+"='"+M+"']");
},render:function(Q){var R=this._getByUid(Q.dataItem.uid);
var M=Q.children;
if(M){var S=R.find(".k-treemap-wrap");
for(var O=0;
O<M.length;
O++){var P=M[O];
var N=this._createLeaf(P);
S.append(N);
this.treeMap.trigger(q,{element:N});
}}},createRoot:function(N){var M=this._createLeaf(N);
this.element.append(M);
this.treeMap.trigger(q,{element:M});
},_clean:function(M){M.css("background-color","");
M.removeClass("k-leaf");
M.removeClass("k-inverse");
M.empty();
},_createLeaf:function(M){return this._createTile(M).css("background-color",M.color).addClass("k-leaf").toggleClass("k-inverse",this._tileColorBrightness(M)>180).append(a("<div></div>").html(this._getText(M)));
},_createTile:function(M){var N={width:M.coord.width,height:M.coord.height,left:M.coord.left,top:M.coord.top};
if(N.left&&this.offset){N.width+=this.offset*2;
}else{N.width+=this.offset;
}if(N.top){N.height+=this.offset*2;
}else{N.height+=this.offset;
}var O=a("<div class='k-treemap-tile'></div>").css({width:N.width,height:N.height,left:N.left,top:N.top});
if(m(M.dataItem)&&m(M.dataItem.uid)){O.attr(r.attr("uid"),M.dataItem.uid);
}return O;
},_getText:function(M){var N=M.text;
if(this.options.template){N=this._renderTemplate(M);
}return N;
},_renderTemplate:function(M){var N=G(this.options.template);
return N({dataItem:M.dataItem,text:M.text});
},_createTitle:function(M){return a("<div class='k-treemap-title'></div>").append(a("<div></div>").html(this._getText(M)));
},_createWrap:function(){return a("<div class='k-treemap-wrap'></div>");
},_tileColorBrightness:function(M){return e(M.color);
}});
var C=d.extend({createRoot:function(N,P,M,O){N.coord={width:P,height:M,top:0,left:0};
N.vertical=O;
},init:function(M){this.vertical=M;
this.quotient=M?1:0;
},compute:function(M,Q,O){if(M.length>0){var R=Q.width;
var N=Q.height;
if(this.vertical){N-=O.text;
}else{R-=O.text;
}var P={width:R,height:N,top:0,left:0};
this.layoutChildren(M,P);
}},layoutChildren:function(P,M){var R=M.width*M.height;
var S=0;
var Q=[];
var N;
for(N=0;
N<P.length;
N++){var O=P[N];
Q[N]=parseFloat(P[N].value);
S+=Q[N];
O.vertical=this.vertical;
}for(N=0;
N<Q.length;
N++){P[N].area=R*Q[N]/S;
}P=new r.data.Query(P)._sortForGrouping("value","desc");
this.sliceAndDice(P,M);
},sliceAndDice:function(N,M){var O=this._totalArea(N);
if(N[0].level%2===this.quotient){this.layoutHorizontal(N,M,O);
}else{this.layoutVertical(N,M,O);
}},layoutHorizontal:function(P,M,R){var Q=0;
for(var N=0;
N<P.length;
N++){var O=P[N];
var S=O.area/(R/M.width);
O.coord={height:M.height,width:S,top:M.top,left:M.left+Q};
Q+=S;
}},layoutVertical:function(Q,M,S){var R=0;
for(var O=0;
O<Q.length;
O++){var P=Q[O];
var N=P.area/(S/M.height);
P.coord={height:N,width:M.width,top:M.top+R,left:M.left};
R+=N;
}},_totalArea:function(N){var O=0;
for(var M=0;
M<N.length;
M++){O+=N[M].area;
}return O;
}});
var D=F.extend({htmlSize:function(N){var O=this._getByUid(N.dataItem.uid);
var M={text:0,offset:0};
if(N.children){this._clean(O);
var P=this._getText(N);
if(P){var Q=this._createTitle(N);
O.append(Q);
if(N.vertical){M.text=Q.height();
}else{M.text=Q.width();
}}O.append(this._createWrap());
this.offset=(O.outerWidth()-O.innerWidth())/2;
}return M;
},_createTitle:function(M){var N;
if(M.vertical){N=a("<div class='k-treemap-title'></div>");
}else{N=a("<div class='k-treemap-title-vertical'></div>");
}return N.append(a("<div></div>").html(this._getText(M)));
}});
function K(N,M){return m(N)?N:M;
}function n(M,O){if(O===null){return O;
}var N=o(M,true);
return N(O);
}function m(M){return typeof M!==J;
}function g(S,Q,P){var T=z(S);
var R=z(Q);
var O=e(S)-e(Q)<0;
var M=[];
M.push(S);
for(var N=0;
N<P;
N++){var U={r:f(T.r,R.r,N,P,O),g:f(T.g,R.g,N,P,O),b:f(T.b,R.b,N,P,O)};
M.push(b(U));
}M.push(Q);
return M;
}function f(T,R,O,Q,P){var U=s.min(s.abs(T),s.abs(R));
var S=s.max(s.abs(T),s.abs(R));
var V=(S-U)/(Q+1);
var N=V*(O+1);
var M;
if(P){M=U+N;
}else{M=S-N;
}return M;
}function b(M){return"#"+k(M.r)+k(M.g)+k(M.b);
}function z(M){M=M.replace("#","");
var N=h(M);
return{r:A(N.r),g:A(N.g),b:A(N.b)};
}function k(M){var N=s.round(M).toString(16).toUpperCase();
if(N.length===1){N="0"+N;
}return N;
}function h(M){var N=M.length;
var O={};
if(N===3){O.r=M[0];
O.g=M[1];
O.b=M[2];
}else{O.r=M.substring(0,2);
O.g=M.substring(2,4);
O.b=M.substring(4,6);
}return O;
}function A(M){return parseInt(M.toString(16),16);
}function e(N){var M=0;
if(N){N=z(N);
M=s.sqrt(0.241*N.r*N.r+0.691*N.g*N.g+0.06800000000000001*N.b*N.b);
}return M;
}function B(N){var M=s.pow(10,4);
return s.round(N*M)/M;
}j.ui.plugin(H);
})(window.kendo.jQuery);
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
