Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSlidingZone=function(b){return b;
};
$telerik.findSlidingZone=$find;
var a=Telerik.Web.UI;
a.SplitterSlideDirection=function(){};
a.SplitterSlideDirection.prototype={Right:1,Left:2,Top:3,Bottom:4};
a.SplitterSlideDirection.registerEnum("Telerik.Web.UI.SplitterSlideDirection",false);
a.RadSlidingZone=function(b){a.RadSlidingZone.initializeBase(this,[b]);
this._width=null;
this._height=null;
this._clickToOpen=false;
this._resizeStep=0;
this._slideDuration=300;
this._splitter=null;
this._slideDirection=a.SplitterSlideDirection.Right;
this._slidingPanes=null;
this._slidingPanesById=null;
this._initiallyDockedPaneId=null;
this._dockedPaneId=null;
this._initiallyExpandedPaneId=null;
this._expandedPaneId=null;
this.GetPaneById=this.getPaneById;
this.GetTabsContainer=this.getTabsContainer;
this.DockPane=this.dockPane;
this.UndockPane=this.undockPane;
this.GetPanes=this.getPanes;
this.ExpandPane=this.expandPane;
this.CollapsePane=this.collapsePane;
this.IsLeftDirection=this.isLeftDirection;
this.IsRightDirection=this.isRightDirection;
this.IsTopDirection=this.isTopDirection;
this.IsBottomDirection=this.isBottomDirection;
};
a.RadSlidingZone.prototype={endUpdate:function(){if(this._width.toString().indexOf("px")>-1){this._width=parseInt(this._width,10);
}if(this._height.toString().indexOf("px")>-1){this._height=parseInt(this._height,10);
}a.RadSlidingZone.callBaseMethod(this,"endUpdate");
},dispose:function(){var d=this.getPanes();
for(var b=0,c=d.length;
b<c;
b++){var e=d[b];
if(e){e._moveRootToParent(true);
}}if(this._paneTabMoutTimeout){window.clearTimeout(this._paneTabMoutTimeout);
this._paneTabMoutTimeout=null;
}a.RadSplitterController.getInstance()._removeSlidingZone(this.get_id());
a.RadSlidingZone.callBaseMethod(this,"dispose");
},initialize:function(){a.RadSlidingZone.callBaseMethod(this,"initialize");
var b=this._getPanesContainer();
var c=this.get_element();
if(this._isVerticalSlide()){b=b.parentNode;
if(this.isTopDirection()&&($telerik.isIE6||$telerik.isIE7)){c.style.marginTop="-1px";
}}else{if(this.isLeftDirection()&&$telerik.isSafari){c.style.marginLeft="-1px";
}}if($telerik.isIE6||$telerik.isIE7){c.setAttribute("cellSpacing","0");
c.setAttribute("cellPadding","0");
}b.style.display="";
},set_clickToOpen:function(b){this._clickToOpen=b;
this.updateClientState();
},get_clickToOpen:function(){return this._clickToOpen;
},set_resizeStep:function(b){this._resizeStep=b;
this.updateClientState();
},get_resizeStep:function(){return this._resizeStep;
},set_slideDuration:function(e){this._slideDuration=e;
this.updateClientState();
var d=this.getPanes();
for(var b=0;
b<d.length;
b++){var c=d[b];
c._slideDuration=e;
if(c._animation){c._animation._expandAnimation.set_duration(e);
}}},get_slideDuration:function(){return this._slideDuration;
},get_width:function(){return this._width;
},get_height:function(){return this._height;
},get_expandedPaneId:function(){return this._expandedPaneId;
},get_dockedPaneId:function(){return this._dockedPaneId;
},get_parent:function(){return this._getParentPane();
},_getParentPane:function(){var b=this._parent;
if(!b){b=this._parent=a.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return b;
},get_splitter:function(){var b=this._splitter;
if(!b){b=this._splitter=a.RadSplitterController.getInstance()._getSplitter(this.get_id());
}return b;
},set_splitter:function(b){this._splitter=b;
},add_loaded:function(b){this.add_load(b);
},remove_loaded:function(b){this.remove_load(b);
},add_load:function(b){this.get_events().addHandler("load",b);
},remove_load:function(b){this.get_events().removeHandler("load",b);
},getPaneById:function(b){return this._getSlidingPanesById()[b];
},getTabsContainer:function(){return $get("RAD_SLIDING_ZONE_TABS_CONTAINER_"+this.get_id());
},_getPanesContainer:function(){return $get("RAD_SLIDING_ZONE_PANES_CONTAINER_"+this.get_id());
},dockPane:function(h){var j=this.getPaneById(h);
if(!j||!j.get_enableDock()){return false;
}var d=new Sys.CancelEventArgs();
j.raiseEvent("docking",d);
if(d.get_cancel()){return false;
}var c=this._dockedPaneId;
if(c&&!this.undockPane(c)){return false;
}j._moveRootToParent(true);
var i=this._getPanesContainer();
var e=this.isLeftDirection();
var f=this.isTopDirection();
this._dockingMode=true;
var o=this._getTabsContainerSize();
var l=o+j[this._isHorizontalSlide()?"get_width":"get_height"]();
var k=this.get_parent();
var m=k.getVarSize();
var n=(e||f)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
var g=m+this.get_splitter()._getAvailIncreaseDelta(k.get_indexInPanes(),n);
l=Math.min(l,g);
var b=l-m;
if(b!=0){k.resize(b,n);
}j._dock();
j._setSlidingContainerSize();
j._setTabDockedState();
var p=this.get_element();
if(f&&($telerik.isIE6||$telerik.isIE7)){p.style.marginTop="0";
}else{if(e&&$telerik.isSafari){i.style.width="1px";
setTimeout(function(){i.style.width="";
},0);
p.style.marginLeft="0";
}}this._dockedPaneId=h;
this._dockingMode=false;
this.updateClientState();
j.raiseEvent("docked",new Sys.EventArgs());
return true;
},undockPane:function(g){var i=this.getPaneById(g);
if(!i){return false;
}var d=new Sys.CancelEventArgs();
i.raiseEvent("undocking",d);
if(d.get_cancel()){return false;
}if(!g){g=this._dockedPaneId;
}var j=this.get_parent();
if(j.get_collapsed()){return false;
}i._moveRootToParent(false);
this._dockingMode=true;
i._undock();
i._setTabDefaultState();
this._dockedPaneId=null;
var f=this.isTopDirection();
var e=this.isLeftDirection();
var h=this._getPanesContainer();
var l=this.get_element();
if(f&&($telerik.isIE6||$telerik.isIE7)){l.style.marginTop="-1px";
}else{if(e&&$telerik.isSafari){h.style.width="1px";
setTimeout(function(){h.style.width="";
},0);
l.style.marginLeft="-1px";
}}var b=j.getVarSize();
var c=b-this._getTabsContainerSize();
var k=(e||f)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
j.resize(c*(-1),k);
this.updateClientState();
this._dockingMode=false;
i.raiseEvent("undocked",new Sys.EventArgs());
this._paneTabInMover=null;
return true;
},getPanes:function(){var b=this._slidingPanes;
if(!b){var c=this.get_id();
b=this._slidingPanes=a.RadSplitterController.getInstance()._getSlidingPanes(c);
}return b;
},_getSlidingPanesById:function(){var f=this._slidingPanesById;
if(!f){f=[];
var e=this.getPanes();
for(var b=0,c=e.length;
b<c;
b++){var d=e[b];
f[d.get_id()]=d;
}this._slidingPanesById=f;
}return f;
},expandPane:function(e){if(!e){return false;
}var d=this.getPaneById(e);
if(!d){return false;
}if(d._dockOnOpen){this.dockPane(e);
this._dockedPaneId=e;
this.updateClientState();
return false;
}var c=this._expandedPaneId;
if((e==this._paneTabInMover)||(c&&e==c)){return false;
}if(c&&!this.collapsePane(c)){this._paneTabInMover=null;
return;
}if(e==this._dockedPaneId){return false;
}var b=new Sys.CancelEventArgs();
d.raiseEvent("expanding",b);
if(b.get_cancel()){return false;
}this._paneTabInMover=e;
d._setTabExpandedState();
d._expand();
this._expandedPaneId=e;
this.updateClientState();
return true;
},collapsePane:function(e,d){if(this._expandedPaneId!=e){return true;
}if(this._dockedPaneId==e){return false;
}var f=this.getPaneById(e);
if(!f){return false;
}var c=new Sys.CancelEventArgs();
f.raiseEvent("collapsing",c);
if(c.get_cancel()){return false;
}f._setTabDefaultState();
var b=f._animation;
if(b){b._stopAnimation();
}if(!d){f._tableElement.style.position="";
}f._collapse();
this._expandedPaneId=null;
this.updateClientState();
this._paneTabInMover=null;
return true;
},isLeftDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Left);
},isRightDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Right);
},isTopDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Top);
},isBottomDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Bottom);
},_paneTab_OnMouseOver:function(b){if(this._clickToOpen){return;
}window.clearTimeout(this._paneTabMoutTimeout);
var c=this._getPaneIdFromTabElement(b.target);
this.expandPane(c);
},_paneTab_OnMouseOut:function(b){if(this._clickToOpen){return;
}var c=this._getPaneIdFromTabElement(b.target);
if(!c){return;
}if($telerik.isMouseOverElementEx(this.getPaneById(c).getTabContainer(),b)){return $telerik.cancelRawEvent(b);
}this._paneTabMoutTimeout=setTimeout(Function.createDelegate(this,function(){this._paneTabInMover=null;
this.collapsePane(c);
}),100);
},_paneTab_OnMouseDown:function(b){if(!this._clickToOpen){return;
}var f=b.target;
var d=this._getPaneIdFromTabElement(f);
var c=this._expandedPaneId;
if(c==d){this.collapsePane(d);
}else{this.expandPane(d);
}},_isHorizontalSlide:function(){return(this._slideDirection==a.SplitterSlideDirection.Left||this._slideDirection==a.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},_getPaneIdFromTabElement:function(b){while(b&&b.tagName!="DIV"){b=b.parentNode;
}if(!b||b.id.indexOf("RAD_SLIDING_PANE_TAB_")==-1){return"";
}return b.id.substr("RAD_SLIDING_PANE_TAB_".length);
},_handleParentPaneResizing:function(k,b){if(this._dockingMode){return;
}var d=b.get_delta();
if(this._dockedPaneId){var e=this.getPaneById(this._dockedPaneId);
if(!e.get_enableResize()){b.set_cancel(true);
return;
}var l=this._getTabsContainerSize();
var h=l+(this._isHorizontalSlide())?e.get_minWidth():e.get_minHeight();
var g=l+(this._isHorizontalSlide())?e.get_maxWidth():e.get_maxHeight();
var f=e.get_slidingPaneBounds();
var c=(this._isHorizontalSlide())?f.width:f.height;
var i=c+d;
if(i>g||i<h){b.set_cancel(true);
return;
}var j=new a.PaneResizingEventArgs(d);
e.raiseEvent("resizing",j);
b.set_cancel(j.get_cancel());
}},_getTabsContainerSize:function(){var b=this.getTabsContainer();
return(this._isHorizontalSlide())?b.offsetWidth:b.offsetHeight;
},_handleParentPaneResized:function(q,b){var h=this._dockedPaneId;
if(this._dockingMode||!h){return;
}var g=this.getPaneById(h);
var j=g.get_enableResize();
var k=g._isVerticalSlide();
var i=g.get_slidingPaneBounds();
var d=i.width;
var f=(!j&&!k)?0:(q.get_width()-b.get_oldWidth());
var n=d+f;
var c=i.height;
var e=(!j&&k)?0:q.get_height()-b.get_oldHeight();
var m=c+e;
g._setSlidingContainerSize(n,m);
var p=g.get_width();
var o=b.get_oldHeight();
var l=q.get_height();
g.set_width(n);
g.set_height(l);
g.raiseEvent("resized",new a.PaneResizedEventArgs(p,o));
},_handleSplitterResized:function(d,b){if(this._expandedPaneId){if(d.get_width()!=b.get_oldWidth()||d.get_height()!=b.get_oldHeight()){var c=this._expandedPaneId;
this.collapsePane(c);
this.expandPane(c);
}}},_splitterLoadHandler:function(){var f=this.get_parent();
f.add_resizing(Function.createDelegate(this,this._handleParentPaneResizing));
f.add_resized(Function.createDelegate(this,this._handleParentPaneResized));
var k=this.get_splitter();
k.add_resized(Function.createDelegate(this,this._handleSplitterResized));
if($telerik.quirksMode||$telerik.isFirefox2){var j=this.getPanes();
for(var d=0,e=j.length;
d<e;
d++){var h=j[d];
var g=h.get_element();
g.className=k.getContainerElement().className+" RadSlidingPaneQuirksMode "+g.className;
h._originalParent=h.get_element().parentNode;
h._moveRootToParent(false);
}}var b=this._initiallyDockedPaneId;
if(b!=null){this.dockPane(b);
}var c=this._initiallyExpandedPaneId;
if(c!=null){this.expandPane(c);
}this.updateClientState();
this.raiseEvent("load");
},saveClientState:function(){if(this.get_isUpdating()){return null;
}var f={dockedPaneId:this._dockedPaneId||"",expandedPaneId:this._expandedPaneId||""};
var d=["clickToOpen","resizeStep","slideDuration"];
for(var b=0,c=d.length;
b<c;
b++){var e=d[b];
f[e]=this["get_"+e]();
}return Sys.Serialization.JavaScriptSerializer.serialize(f);
}};
a.RadSlidingZone._preInitialize=function(c,d,b){a.RadSplitterController.getInstance()._addSlidingZone(c,d,b);
};
a.RadSlidingZone.registerClass("Telerik.Web.UI.RadSlidingZone",a.RadWebControl);
})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSlidingPane=function(e){return e;
};
$telerik.findSlidingPane=$find;
var b=Telerik.Web.UI;
var a=$telerik.$;
var c=Telerik.Web.Browser;
var d={width:1,height:1};
b.RadSlidingPane=function(e){b.RadSlidingPane.initializeBase(this,[e]);
this._title="";
this._isTabRotated=false;
this._enableResize=true;
this._enableDock=true;
this._dockOnOpen=false;
this._parentPane=null;
this._clickToOpen=false;
this._slideDirection=b.SplitterSlideDirection.Right;
this._slideDuration=300;
this._resizeBarSize=null;
this._isExpanded=false;
this._isDocked=false;
this._width=150;
this._height=150;
this._minWidth=60;
this._minHeight=60;
this._overlay=false;
this._isInitialSizeApplied=false;
this._popupBehavior=null;
this._popupElement=null;
this._contentElement=null;
this._tableElement=null;
this._tabContainer=null;
this._resizeElement=null;
this._originalParent=null;
this.GetContentContainer=this.getContentContainer;
this.GetContent=this.getContent;
this.SetContent=this.setContent;
this.GetDockIconElement=this.getDockIconElement;
this.GetUndockIconElement=this.getUndockIconElement;
this.GetCollapseIconElement=this.getCollapseIconElement;
this.GetSlidingContainerTitle=this.getSlidingContainerTitle;
this.GetSlidingPaneResizeContainer=this.getSlidingPaneResizeContainer;
this.GetTabContainer=this.getTabContainer;
this.HideTab=this.hideTab;
this.ShowTab=this.showTab;
this.IsTabDisplayed=this.isTabDisplayed;
};
b.RadSlidingPane.prototype={initialize:function(){b.RadSlidingPane.callBaseMethod(this,"initialize");
this._popupElement=this.get_element();
this._contentElement=this.getContentContainer();
this._tableElement=this._popupElement.getElementsByTagName("TABLE")[0];
this._tabContainer=this.getTabContainer();
this._resizeElement=this.getSlidingPaneResizeContainer();
var l=this._tabContainer;
$addHandlers(l,{mousedown:this._paneTab_OnMouseDown,mouseover:this._paneTab_OnMouseOver,mouseout:this._paneTab_OnMouseOut},this);
var k=this._popupElement;
$addHandlers(k,{mouseover:this._slidingContainer_OnMouseOver,mouseout:this._slidingContainer_OnMouseOut},this);
var j=this._resizeElement;
if(j){j.setAttribute("unselectable","on");
$addHandlers(j,{mouseover:this._resizeSlidePane_OnMouseOver,mouseout:this._resizeSlidePane_OnMouseOut},this);
this._createResizeHelper();
var i=this._getCursorStyle();
var g={};
g[i]=j;
this._resizeExtender=new b.ResizeExtender(this,this._helperBar,g,null,null,i,false);
}var f=this.getDockIconElement();
$addHandlers(f,{mouseover:this._dockElement_OnMouseOver,mouseout:this._dockElement_OnMouseOut,mousedown:this._dockElement_OnMouseDown},this);
var m=this.getUndockIconElement();
$addHandlers(m,{mouseover:this._undockElement_OnMouseOver,mouseout:this._undockElement_OnMouseOut,mousedown:this._undockElement_OnMouseDown},this);
var e=this.getCollapseIconElement();
$addHandlers(e,{mouseover:this._collapseElement_OnMouseOver,mouseout:this._collapseElement_OnMouseOut,mousedown:this._collapseElement_OnMouseDown},this);
if(this._scrollingEnabled){if(b.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}else{if(this._persistScrollPosition){this._attachScrollHandler(true);
}}}var h=this._tableElement.getElementsByTagName("table")[0];
if($telerik.isIE6||$telerik.isIE7){this._tableElement.setAttribute("cellSpacing","0");
this._tableElement.setAttribute("cellPadding","0");
h.setAttribute("cellSpacing","0");
h.setAttribute("cellPadding","0");
}if(this._resizeElement){this._setResizeElSpan();
}if(this._isHorizontalSlide()&&!$telerik.getInvisibleParent(this.get_element())){if(!$telerik.isIE){this._applyTabRotation();
}}this.updateClientState();
},dispose:function(){this._moveRootToParent(true);
this._originalParent=null;
var h=this._popupBehavior;
if(h){h.dispose();
this._popupBehavior=null;
}var e=this._animation;
if(this._expandAnimationEndedDelegate){if(e){e.remove_expandAnimationEnded(this._expandAnimationEndedDelegate);
}this._expandAnimationEndedDelegate=null;
}if(e){e.dispose();
this._animation=null;
}var k=this._tabContainer;
if(k){$clearHandlers(k);
}var j=this._popupElement;
if(j){$clearHandlers(j);
}this._popupElement=null;
var i=this._resizeElement;
if(i){$clearHandlers(i);
}this._resizeElement=null;
var g=this.getDockIconElement();
if(g){$clearHandlers(g);
}var l=this.getUndockIconElement();
if(l){$clearHandlers(l);
}var f=this.getCollapseIconElement();
if(f){$clearHandlers(f);
}this._attachScrollHandler(false);
this._createTouchScrollExtender(false);
this._contentElement=null;
b.RadSplitterController.getInstance()._removeSlidingPane(this.get_id());
b.RadSlidingPane.callBaseMethod(this,"dispose");
},repaint:function(){b.RadSlidingPane.callBaseMethod(this,"repaint");
if(!this._isTabRotated&&!$telerik.isIE){this._applyTabRotation();
}},get_parent:function(){return this._getSlidingZone();
},_getSlidingZone:function(){var e=this._parent;
if(!e){e=this._parent=b.RadSplitterController.getInstance()._getSlidingZone(this.get_id());
}return e;
},get_enableResize:function(){return this._enableResize;
},set_enableResize:function(e){this._enableResize=e;
this.updateClientState();
},get_enableDock:function(){return this._enableDock;
},set_enableDock:function(e){this._enableDock=e;
this.updateClientState();
},get_dockOnOpen:function(){return this._dockOnOpen;
},set_dockOnOpen:function(e){this._dockOnOpen=e;
this.updateClientState();
},set_title:function(g){this._title=g;
var e=this._getTitleContainerElement();
if(e!=null){e.innerHTML=g;
}var f=this.getSlidingContainerTitle();
if(f){f.innerHTML=g;
}this.updateClientState();
},get_title:function(){return this._title;
},get_expanded:function(){return this._isExpanded;
},get_docked:function(){return this._isDocked;
},get_overlay:function(){return this._overlay;
},set_overlay:function(f){this._overlay=f;
var e=this._popupBehavior;
if(e){e.set_overlay(this._overlay);
}},get_parentPane:function(){var e=this._parentPane;
if(!e){e=this._parentPane=b.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return e;
},set_parentPane:function(e){this._parentPane=e;
},add_docked:function(e){this.get_events().addHandler("docked",e);
},remove_docked:function(e){this.get_events().removeHandler("docked",e);
},add_undocked:function(e){this.get_events().addHandler("undocked",e);
},remove_undocked:function(e){this.get_events().removeHandler("undocked",e);
},add_beforeDock:function(e){this.add_docking(e);
},remove_beforeDock:function(e){this.remove_docking(e);
},add_docking:function(e){this.get_events().addHandler("docking",e);
},remove_docking:function(e){this.get_events().removeHandler("docking",e);
},add_beforeUndock:function(e){this.add_undocking(e);
},remove_beforeUndock:function(e){this.remove_undocking(e);
},add_undocking:function(e){this.get_events().addHandler("undocking",e);
},remove_undocking:function(e){this.get_events().removeHandler("undocking",e);
},getContentContainer:function(){if(!this._contentElement){this._contentElement=$get("RAD_SLIDING_PANE_CONTENT_"+this.get_id());
}return this._contentElement;
},get_pane:function(){return this.get_parentPane().get_element();
},get_paneBounds:function(){var e=this.get_pane();
return $telerik.getBounds(e);
},_show:function(f,g){var e=this._popupBehavior;
e._setCoordinates(f,g);
e.show();
},get_slidingPaneBounds:function(){var e=this._popupElement;
var g=(e.style.top==""&&!this._isDocked);
if(g){this._setSlidingContainerSize();
}var f=$telerik.getBounds(e);
return f;
},_fixIeHeight:function(h,f){if($telerik.standardsMode){var e=(h.offsetHeight-parseInt(f,10));
if(e>0){var g=(parseInt(h.style.height,10)-e);
if(g>0){h.style.height=g+"px";
}}}},getContent:function(){return this._contentElement.innerHTML;
},setContent:function(e){this._contentElement.innerHTML=e;
},getDockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_DOCK_"+this.get_id());
},getDockIconWrapperElement:function(){return this.getDockIconElement().parentNode;
},getUndockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_UNDOCK_"+this.get_id());
},getUnDockIconWrapperElement:function(){return this.getUndockIconElement().parentNode;
},getCollapseIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_COLLAPSE_"+this.get_id());
},getCollapseIconWrapperElement:function(){return this.getCollapseIconElement().parentNode;
},getSlidingContainerTitle:function(){return $get("RAD_SPLITTER_SLIDING_TITLE_"+this.get_id());
},getSlidingPaneResizeContainer:function(){if(!this._resizeElement){this._resizeElement=$get("RAD_SPLITTER_SLIDING_ZONE_RESIZE_"+this.get_id());
}return this._resizeElement;
},getTabContainer:function(){if(!this._tabContainer){this._tabContainer=$get("RAD_SLIDING_PANE_TAB_"+this.get_id());
}return this._tabContainer;
},hideTab:function(){var e=this._tabContainer;
if(e==null){return;
}e.style.display="none";
},showTab:function(){var e=this._tabContainer;
if(e==null){return;
}e.style.display="";
},isTabDisplayed:function(){var e=this._tabContainer;
if(e==null){return false;
}return(e.style.display!="none");
},_setResizeElSpan:function(){if(this._isHorizontalSlide()){this._resizeElement.setAttribute("rowSpan","2");
}else{this._resizeElement.setAttribute("colSpan","2");
}},_getIsLeftDirection:function(){var e=$telerik.isRightToLeft(this.get_element());
return(this._isLeftDirection()&&!e)||(e&&this._isRightDirection());
},_getIsRightDirection:function(){var e=$telerik.isRightToLeft(this.get_element());
return(this._isRightDirection()&&!e)||(e&&this._isLeftDirection());
},_setTabDefaultState:function(){var e=this._tabContainer;
if(e==null){return false;
}Sys.UI.DomElement.removeCssClass(e,"rspPaneTabContainerDocked");
Sys.UI.DomElement.removeCssClass(e,"rspPaneTabContainerExpanded");
},_setTabDockedState:function(){var e=this._tabContainer;
if(e==null){return false;
}Sys.UI.DomElement.addCssClass(e,"rspPaneTabContainerDocked");
},_setTabExpandedState:function(){var e=this._tabContainer;
if(e==null){return false;
}Sys.UI.DomElement.addCssClass(e,"rspPaneTabContainerExpanded");
},_applyTabRotation:function(){if(this._isTabRotated){return;
}var i=a("span",this._tabContainer).get(0),e=this._getTabIconElement(),f=e?a(e).outerHeight(true):0;
if(this._isHorizontalSlide()){a(this._tabContainer).height(a(i).width()+f);
}var l=0;
var h=a(i);
if($telerik.isRightToLeft(this.get_element())){l=h.width()+parseInt(h.css("margin-left"),10)-h.height();
}var k=String.format("{0}transform",this._getBrowserCssPrefix());
a(i).css(k,"matrix(0, 1, -1, 0, "+l+", 0)");
var j=this._calculateTabTextLineHeight();
var g=Math.ceil(j/2);
var m=String.format("{0}transform-origin",this._getBrowserCssPrefix());
a(i).css(m,String.format("{0}px {0}px",g)).css("line-height",j+"px");
this._isTabRotated=true;
},_calculateTabTextLineHeight:function(){var e=(this._isHorizontalSlide())?"width":"height";
return parseInt($telerik.getComputedStyle(this._tabContainer,e),10);
},_getTabIconElement:function(){return $get("RAD_SLIDING_PANE_ICON_"+this.get_id());
},_resizeSlidePane_OnMouseOver:function(f){var g=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.addCssClass(this._resizeElement,g);
},_resizeSlidePane_OnMouseOut:function(f){var g=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.removeCssClass(this._resizeElement,g);
},_resizeByDelta:function(e){var f=new b.PaneResizingEventArgs(e);
this.raiseEvent("resizing",f);
if(f.get_cancel()){return;
}var i=this._isTopDirection();
var h=this._getIsLeftDirection();
if(i||h){e*=-1;
}var g=this._isHorizontalSlide();
var o=this.get_slidingPaneBounds();
var k=g?(o.width+e):null;
var j=!g?(o.height+e):null;
this._setSlidingContainerSize(k,j);
var n=this._popupBehavior;
var p=n.get_x()-(h?e:0);
var q=n.get_y()-(i?e:0);
this._show(p,q);
var m=this.get_width();
var l=this.get_height();
if(g){this.set_width(k);
this._resizeTitleElemWidth(k);
}else{this.set_height(j);
}$telerik.repaintChildren(this);
this.raiseEvent("resized",new b.PaneResizedEventArgs(m,l));
},_resizeTitleElemWidth:function(h){var g=this.getSlidingContainerTitle(),e=$telerik.getMarginBox(g),f=$telerik.getComputedStyle(g,"overflow");
g.style.overflow="hidden";
g.style.width="1px";
h=h-e.horizontal-this._resizeElement.offsetWidth-this._getCommandsWidth();
g.style.width=h>18?h+"px":18+"px";
g.style.overflow=f;
},_getIconWrapperElements:function(){return $telerik.getElementsByClassName(this.get_element(),"rspSlideHeaderIconWrapper");
},_getCommandsWidth:function(){var g=0;
var f=this._getIconWrapperElements();
for(var e=0;
e<f.length;
e++){g+=f[e].offsetWidth;
}return g;
},_getCursorStyle:function(){return(this._isHorizontalSlide()?"w-resize":"n-resize");
},_createResizeHelper:function(){var i=this._popupElement.style.zIndex+2;
var g=this._isHorizontalSlide();
var e=this._getCursorStyle();
var h=document.createElement("div");
h.unselectable="on";
a(h).css({display:"none",position:"absolute",cursor:e,zIndex:i});
document.body.insertBefore(h,document.body.firstChild);
Sys.UI.DomElement.addCssClass(h,"RadSplitter");
var f=document.createElement("div");
f.unselectable="on";
a(f).css({cursor:e,fontSize:"1px",margin:(g?"0 150px":"150px 0")});
f.innerHTML="<!-- / -->";
h.appendChild(f);
Sys.UI.DomElement.addCssClass(f,"rspHelperBarSlideDrag");
this._helperBar=h;
this._helperBarDecoration=f;
},_getHelperSize:function(){var f={width:4,height:4};
var e=this.get_parentPane();
if(this._isHorizontalSlide()){f.height=e.get_height();
}else{f.width=e.get_width();
}return f;
},onDragStart:function(e){var z=this._getSlidingZone();
var h=z.get_dockedPaneId();
if(h==this.get_id()){return false;
}var l=this._isHorizontalSlide();
var y=this.get_width();
var j=this.get_height();
var n=l?(y-this.get_minWidth()):(j-this.get_minHeight());
var o=l?(this.get_maxWidth()-y):(this.get_maxHeight()-j);
var q=this.get_parentPane();
var s=this.get_splitter()._getAvailDecreaseDelta(q.get_indexInPanes(),b.SplitterDirection.Forward);
var r=Math.min(q._getAvailIncreaseDelta(),s);
if(h!=null){var g=z.getPaneById(h);
r+=(l)?g.get_width():g.get_height();
}r-=(l)?y:j;
o=Math.min(o,r);
if(this._getIsLeftDirection()||this._isTopDirection()){var x=o;
o=n;
n=x;
}var w=this.get_splitter();
var p=w._getDragOverlay();
a(p).css({zIndex:(this._popupElement.style.zIndex+1),cursor:this._getCursorStyle(),display:"block"});
$telerik.setBounds(p,$telerik.getBounds(w.get_element()));
var v=this._getHelperSize();
$telerik.setSize(this._helperBarDecoration,v);
var u=this._resizeElement;
var m=$telerik.getLocation(u);
if($telerik.isSafari&&l){m.y=$telerik.getLocation(u.parentNode).y;
}var f=this._cachedResizeHelperBounds=a.extend({},v,m);
this._liveResizePosition=a.extend({},f);
this._cachedSplitterBounds={x:f.x-(l?n:0),y:f.y-(!l?n:0),width:f.width+(l?(n+o):0),height:f.height+(!l?(n+o):0)};
m[l?"x":"y"]-=150;
var k=this._helperBar;
k.style.display="";
$telerik.setLocation(k,m);
var i=this._resizeExtender;
i._originalBounds=a.extend({},f,m);
this._resizeMode=true;
return true;
},onDragEnd:function(e){if(!this.get_expanded()){return;
}var g=this._isHorizontalSlide()?"x":"y";
var f=this._liveResizePosition[g]-this._cachedResizeHelperBounds[g];
if(f!=0){this._resizeByDelta(f);
}this.get_splitter()._getDragOverlay().style.display="none";
this._helperBar.style.display="none";
Sys.UI.DomElement.removeCssClass(this._helperBarDecoration,"rspHelperBarSlideError");
this._liveResizePosition=null;
this._cachedSplitterBounds=null;
this._cachedResizeHelperBounds=null;
this._resizeMode=false;
},onDrag:function(e){var m=this._cachedSplitterBounds;
if(m.width<1||m.height<1){return false;
}var f=this._helperBarDecoration;
Sys.UI.DomElement.removeCssClass(f,"rspHelperBarSlideError");
var g=this._isHorizontalSlide();
var i=g?"x":"y";
e[i]+=150;
var l=this._cachedResizeHelperBounds;
var k=b.ResizeExtender.containsBounds(m,new Telerik.Web.UI.Bounds(e.x,e.y,l.width,l.height));
if(!k){var h=false;
if(e.x<=m.x){e.x=m.x;
if(g){h=true;
}}else{if(m.x+m.width<=e.x+l.width){e.x=m.x+m.width-l.width;
if(g){h=true;
}}}if(e.y<=m.y){e.y=m.y;
if(!g){h=true;
}}else{if(m.y+m.height<=e.y+l.height){e.y=m.y+m.height-l.height;
if(!g){h=true;
}}}k=true;
if(h){Sys.UI.DomElement.addCssClass(f,"rspHelperBarSlideError");
}}var j=this._resizeStep;
if(j>0){e[i]-=(e[i]-l[i])%j;
}this._liveResizePosition=a.extend({},e);
e[i]-=150;
return k;
},_paneTab_OnMouseDown:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseDown(f);
},_paneTab_OnMouseOver:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseOver(f);
},_paneTab_OnMouseOut:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseOut(f);
},_slidingContainer_OnMouseOut:function(g){if(this.get_docked()||this._resizeMode||this._clickToOpen||!this.get_expanded()){return;
}if($telerik.isMouseOverElementEx(this._popupElement,g)){return;
}var i=this;
var h=function(){var e=i._getSlidingZone();
e._paneTabInMover=null;
e.collapsePane(i.get_id());
};
var j=this._getSlidingZone();
window.clearTimeout(j._paneTabMoutTimeout);
j._paneTabMoutTimeout=window.setTimeout(h,1000);
},_slidingContainer_OnMouseOver:function(f){if(this.get_docked()||this._resizeMode){return;
}var g=this._getSlidingZone();
window.setTimeout(function(){window.clearTimeout(g._paneTabMoutTimeout);
},0);
},_dockElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_expanded()){return;
}var g=this._getSlidingZone();
if(!g.collapsePane(this.get_id(),true)){return;
}g.dockPane(this.get_id());
this.getDockIconElement().className="rspSlideHeaderDockIcon";
},_dockElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_dockElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_undockElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_docked()){return;
}this._getSlidingZone().undockPane(this.get_id());
},_undockElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_undockElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_collapseElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_expanded()){return;
}var g=this._getSlidingZone();
g._paneTabInMover=null;
g.collapsePane(this.get_id());
},_collapseElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_collapseElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_onExpandAnimationEnded:function(){this._tableElement.style.position="static";
if($telerik.isFirefox){this._configureScrolling();
Sys.UI.DomElement.removeCssClass(this._contentElement,"rspHideContentOverflow");
}if($telerik.getVisible(this.get_element())){this._showOverlayElement(true);
}this.setScrollPos(this._scrollLeft,this._scrollTop);
this._element.style.overflow="hidden";
$telerik.repaintChildren(this);
this.raiseEvent("expanded",new Sys.EventArgs());
},_expandSlidingContainer:function(){this._showOverlayElement(false);
if($telerik.isFirefox){var e=this._contentElement;
e.style.overflow="hidden";
Sys.UI.DomElement.addCssClass(e,"rspHideContentOverflow");
}var i=this._tableElement;
var j=$telerik.getOuterSize(i);
var f=b.jSlideDirection.Right;
if(this._getIsLeftDirection()){f=b.jSlideDirection.Left;
i.style.left=j.width+"px";
}else{if(this._isBottomDirection()){f=b.jSlideDirection.Down;
i.style.top=-j.height+"px";
}else{if(this._isTopDirection()){f=b.jSlideDirection.Up;
i.style.top=j.height+"px";
}else{i.style.left=-j.width+"px";
}}}if(!this._animation){var g=new b.AnimationSettings({duration:this._slideDuration});
var h=new b.jSlide(i,g,null,false);
h.initialize();
h.set_direction(f);
this._expandAnimationEndedDelegate=Function.createDelegate(this,this._onExpandAnimationEnded);
h.add_expandAnimationEnded(this._expandAnimationEndedDelegate);
this._animation=h;
}this._animation.expand();
},_collapseSlidingContainer:function(){try{this._animation.stop();
}catch(f){}this._hideSlidingContainer();
this.raiseEvent("collapsed",new Sys.EventArgs());
},_setSlidingContainerSize:function(l,g){var k=$telerik.getSize(this.get_parentPane()._contentElement);
var h=this._isVerticalSlide();
if(l==null){l=(!h)?this.get_width():k.width;
}if(g==null){g=h?this.get_height():k.height;
}var e=this._contentElement;
if($telerik.isSafari){e.style.width=l+"px";
e.style.height=g+"px";
}var i=this._popupElement;
if(parseInt(i.style.width,10)!=l){i.style.width=l+"px";
}if(parseInt(i.style.height,10)!=g){i.style.height=g+"px";
}if(c.ie&&c.version===8){this._setContentOuterSize(d);
}var j=this._getResizeElementSize();
var f={height:(g-this._getHeaderHeight()-(h?j.height:0)),width:(l-(!h?j.width:0))};
this._setContentOuterSize(f);
this._isInitialSizeApplied=true;
},_getHeaderHeight:function(){var e=0;
var f=$telerik.getElementByClassName(this._tableElement,"rspSlideHeader","tr");
if(f){e=$telerik.getOuterSize(f).height;
}return e;
},_getResizeElementSize:function(){var f={width:0,height:0};
if(this._enableResize){var e=this._resizeElement;
if("none"!=$telerik.getCurrentStyle(e,"display","")){f=$telerik.getOuterSize(e);
}}return f;
},_setContentOuterSize:function(i){var f=this._contentElement;
var e=$telerik.getBorderBox(f);
var h=$telerik.getPaddingBox(f);
var g=$telerik.getMarginBox(f);
i.height-=(e.vertical+h.vertical+g.vertical);
if(parseInt(f.style.height,10)!=i.height&&i.height>=0){f.style.height=i.height+"px";
}i.width-=(e.horizontal+h.horizontal+g.horizontal);
if(parseInt(f.style.width,10)!=i.width&&i.width>=0){f.style.width=i.width+"px";
}},_hideSlidingContainer:function(){var e=this._popupElement;
e.style.top="";
e.style.left="";
this._showOverlayElement(false);
},_dockSlidingContainer:function(){this._popupElement.style.position="static";
this._tableElement.style.position="static";
this._showOverlayElement(false);
},_unDockSlidingContainer:function(){this._popupElement.style.position="";
this._tableElement.style.position="";
this._showOverlayElement(true);
},_setSlidingContainerResizable:function(g){var i=this._resizeElement;
var f=this._isVerticalSlide();
if(f){i=i.parentNode;
}if(g&&i.style.display==""){return;
}if(this._enableResize){var h=this._resizeBarSize;
if(null==h){h=this._getResizeElementSize()[f?"height":"width"];
if(h>0){this._resizeBarSize=h;
}}if(g){h*=-1;
}var e=this._contentElement;
if(f){e.style.height=parseInt(e.style.height,10)+h+"px";
}else{e.style.width=parseInt(e.style.width,10)+h+"px";
}}i.style.display=(g)?"":"none";
},_setIconsExpandedState:function(){this._hideAllIcons();
this.getDockIconWrapperElement().style.display=(this.get_enableDock())?"":"none";
this.getCollapseIconWrapperElement().style.display="";
},_setIconsDockedState:function(){this._hideAllIcons();
this.getUnDockIconWrapperElement().style.display="";
},_hideAllIcons:function(){this.getDockIconWrapperElement().style.display="none";
this.getUnDockIconWrapperElement().style.display="none";
this.getCollapseIconWrapperElement().style.display="none";
},_getTitleContainerElement:function(){return $get("RAD_SLIDING_PANE_TEXT_"+this.get_id());
},_dock:function(){if(!this._isInitialSizeApplied){this._setSlidingContainerSize();
}this._setIconsDockedState();
this._setSlidingContainerResizable(false);
this._dockSlidingContainer();
this.setScrollPos(this._scrollLeft,this._scrollTop);
$telerik.repaintChildren(this);
this._isExpanded=false;
this._isDocked=true;
},_undock:function(){this._isExpanded=false;
this._isDocked=false;
this._setSlidingContainerResizable(this._enableResize);
this._unDockSlidingContainer();
this._hideSlidingContainer();
},_expand:function(){var i=this._getSlidingZone().getTabsContainer();
var h=this._popupElement;
if(!this._popupBehavior){var e=(new Date()-100)+"PopupBehavior";
this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:e,parentElement:i,overlay:this._overlay,keepInScreenBounds:false,manageVisibility:false},null,null,h);
}this._setSlidingContainerResizable(this._enableResize);
this._setIconsExpandedState();
var j=0;
var k=0;
var f=this.get_slidingPaneBounds();
var g=$telerik.getSize(i);
if(this._getIsRightDirection()){j=g.width;
}else{if(this._getIsLeftDirection()){j=-f.width;
}else{if(this._isBottomDirection()){k=g.height;
}else{if(this._isTopDirection()){k=-f.height;
}}}}this._show(j,k);
this._expandSlidingContainer();
if(this._isHorizontalSlide()){this._resizeTitleElemWidth(f.width);
}this._isExpanded=true;
this._isDocked=false;
},_collapse:function(){this._isExpanded=false;
this._isDocked=false;
this._collapseSlidingContainer();
},_isLeftDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Left);
},_isRightDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Right);
},_isTopDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Top);
},_isBottomDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Bottom);
},_isHorizontalSlide:function(){return(this._slideDirection==b.SplitterSlideDirection.Left||this._slideDirection==b.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},saveClientState:function(){var j=this.getScrollPos();
var k={_scrollLeft:j.left,_scrollTop:j.top};
var g=["width","height","title","enableResize","minWidth","maxWidth","minHeight","maxHeight","enableDock"];
for(var e=0,f=g.length;
e<f;
e++){var h=g[e];
k[h]=this["get_"+h]();
}return Sys.Serialization.JavaScriptSerializer.serialize(k);
},_getOverlayElement:function(){return this._popupElement._hideWindowedElementsIFrame;
},_showOverlayElement:function(f){var e=this._getOverlayElement();
if(!e){return;
}e.style.display=f?"":"none";
},_getRadioButtons:function(){var e=this._contentElement.getElementsByTagName("input");
var j=[];
for(var f=0,h=e.length;
f<h;
f++){var g=e[f];
if(g.type=="radio"){j.push(g);
}}return j;
},_getRadioButtonsStatus:function(g){var h=[];
for(var e=0,f=g.length;
e<f;
e++){h.push(g[e].getAttribute("checked"));
}return h;
},_restoreRadioButtonsStatus:function(g,f){for(var e=f.length-1;
e>=0;
e--){if(g.length==0){break;
}f[e].setAttribute("checked",g.pop());
}},_moveRootToParent:function(j){if(!$telerik.quirksMode&&!$telerik.isFirefox2){return;
}var e=(j)?this._originalParent:this.get_splitter().get_element();
var i=this._popupElement;
if(!i){return;
}var f=i.parentNode;
var g;
var h;
if(!e||!f||e.id==f.id){return;
}if($telerik.isIE){g=this._getRadioButtons();
h=this._getRadioButtonsStatus(g);
}f.removeChild(i);
e.appendChild(i);
if($telerik.isIE){this._restoreRadioButtonsStatus(h,g);
}},_getBrowserCssPrefix:function(){if($telerik.isFirefox){return"-moz-";
}else{if($telerik.isChrome||$telerik.isSafari){return"-webkit-";
}else{if($telerik.isOpera){return"-o-";
}else{return"";
}}}}};
b.RadSlidingPane._preInitialize=function(g,h,i,f,e){b.RadSplitterController.getInstance()._addSlidingPane(g,h,i,f,e);
};
b.RadSlidingPane.registerClass("Telerik.Web.UI.RadSlidingPane",b.SplitterPaneBase);
})();
